local mod = get_mod("ServoSkullCommander")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	allow_rehooking = true,
	options = {
		widgets = {
			{
				setting_id = "group_auto",
				type = "group",
				sub_widgets = {
					{
						setting_id = "auto_enabled",
						type = "checkbox",
						default_value = false,
						tooltip = "auto_enabled_desc",
					},
					{
						setting_id = "auto_toggle_key",
						type = "keybind",
						default_value = {},
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "sskc_toggle_auto",
						tooltip = "auto_toggle_key_desc",
					},
					{
						setting_id = "auto_interval",
						type = "numeric",
						default_value = 1.0,
						range = { 0.2, 2.2 },
						step_size_value = 0.1,
						decimals_number = 1,
						tooltip = "auto_interval_desc",
					},
					{
						setting_id = "switch_interval",
						type = "numeric",
						default_value = 3.0,
						range = { 0, 15 },
						step_size_value = 0.5,
						decimals_number = 1,
						tooltip = "switch_interval_desc",
					},
					{
						setting_id = "auto_max_distance",
						type = "numeric",
						default_value = 40,
						range = { 15, 150 },
						step_size_value = 1,
						tooltip = "auto_max_distance_desc",
					},
					{
						setting_id = "auto_cone_angle",
						type = "numeric",
						default_value = 120,
						range = { 30, 360 },
						step_size_value = 10,
						tooltip = "auto_cone_angle_desc",
					},
					{
						setting_id = "aim_switch_enabled",
						type = "checkbox",
						default_value = false,
						tooltip = "aim_switch_enabled_desc",
					},
					{
						setting_id = "ignore_unaggroed",
						type = "checkbox",
						default_value = false,
						tooltip = "ignore_unaggroed_desc",
					},
					{
						setting_id = "auto_block_shield",
						type = "checkbox",
						default_value = true,
						tooltip = "auto_block_shield_desc",
					},
					{
						setting_id = "auto_block_smoke",
						type = "checkbox",
						default_value = true,
						tooltip = "auto_block_smoke_desc",
					},
					{
						setting_id = "auto_in_training",
						type = "checkbox",
						default_value = false,
						tooltip = "auto_in_training_desc",
					},
					{
						setting_id = "debug_enabled",
						type = "checkbox",
						default_value = false,
						tooltip = "debug_enabled_desc",
					},
				},
			},
			{
				setting_id = "group_dog",
				type = "group",
				tooltip = "group_dog_desc",
				sub_widgets = {
					{
						setting_id = "dog_max_distance",
						type = "numeric",
						default_value = 25,
						range = { 5, 60 },
						step_size_value = 1,
						tooltip = "dog_max_distance_desc",
					},
					{
						setting_id = "dog_cone_angle",
						type = "numeric",
						default_value = 180,
						range = { 30, 360 },
						step_size_value = 10,
						tooltip = "dog_cone_angle_desc",
					},
					{
						setting_id = "dog_interval",
						type = "numeric",
						default_value = 1.0,
						range = { 0.2, 2.2 },
						step_size_value = 0.1,
						decimals_number = 1,
						tooltip = "dog_interval_desc",
					},
					{
						setting_id = "dog_switch_interval",
						type = "numeric",
						default_value = 5.0,
						range = { 0, 15 },
						step_size_value = 0.5,
						decimals_number = 1,
						tooltip = "dog_switch_interval_desc",
					},
					{
						setting_id = "dog_skip_game_excluded",
						type = "checkbox",
						default_value = true,
						tooltip = "dog_skip_game_excluded_desc",
					},
				},
			},
			{
				setting_id = "group_daemonhost",
				type = "group",
				tooltip = "group_daemonhost_desc",
				sub_widgets = {
					{
						setting_id = "dh_block_auto",
						type = "checkbox",
						default_value = true,
						tooltip = "dh_block_auto_desc",
					},
					{
						setting_id = "dh_block_manual",
						type = "checkbox",
						default_value = true,
						tooltip = "dh_block_manual_desc",
					},
					{
						setting_id = "dh_divert",
						type = "checkbox",
						default_value = true,
						tooltip = "dh_divert_desc",
					},
					{
						setting_id = "dh_dist",
						type = "numeric",
						default_value = 25,
						range = { 5, 60 },
						step_size_value = 1,
						tooltip = "dh_dist_desc",
					},
					{
						setting_id = "dh_include_sleeping",
						type = "checkbox",
						default_value = false,
						tooltip = "dh_include_sleeping_desc",
					},
					{
						setting_id = "dh_divert_interval",
						type = "numeric",
						default_value = 0.8,
						range = { 0.2, 2.0 },
						step_size_value = 0.1,
						decimals_number = 1,
						tooltip = "dh_divert_interval_desc",
					},
					{
						setting_id = "dh_override_gate",
						type = "checkbox",
						default_value = false,
						tooltip = "dh_override_gate_desc",
					},
					{
						setting_id = "dh_full_stop",
						type = "checkbox",
						default_value = false,
						tooltip = "dh_full_stop_desc",
					},
					{
						setting_id = "dh_notify",
						type = "checkbox",
						default_value = true,
						tooltip = "dh_notify_desc",
					},
				},
			},
			{
				setting_id = "group_gate",
				type = "group",
				sub_widgets = {
					{
						setting_id = "gate_enabled",
						type = "checkbox",
						default_value = true,
						tooltip = "gate_enabled_desc",
					},
					{
						setting_id = "gate_charges",
						type = "dropdown",
						default_value = 1,
						tooltip = "gate_charges_desc",
						options = {
							{ text = "gate_charges_0", value = 0 },
							{ text = "gate_charges_1", value = 1 },
							{ text = "gate_charges_2", value = 2 },
							{ text = "gate_charges_3", value = 3 },
							{ text = "gate_charges_4", value = 4 },
							{ text = "gate_charges_5", value = 5 },
						},
					},
					{
						setting_id = "gate_percent",
						type = "numeric",
						default_value = 1,
						range = { 1, 100 },
						step_size_value = 1,
						tooltip = "gate_percent_desc",
					},
					{
						setting_id = "gate_override_disablers",
						type = "checkbox",
						default_value = false,
						tooltip = "gate_override_disablers_desc",
					},
				},
			},
			{
				setting_id = "group_panic",
				type = "group",
				sub_widgets = {
					{
						setting_id = "panic_key",
						type = "keybind",
						default_value = {},
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "sskc_panic",
						tooltip = "panic_key_desc",
					},
					{
						setting_id = "panic_hold",
						type = "checkbox",
						default_value = true,
						tooltip = "panic_hold_desc",
					},
					{
						setting_id = "panic_timed",
						type = "checkbox",
						default_value = false,
						tooltip = "panic_timed_desc",
					},
					{
						setting_id = "panic_duration",
						type = "numeric",
						default_value = 30,
						range = { 10, 120 },
						step_size_value = 5,
						tooltip = "panic_duration_desc",
					},
				},
			},
			{
				setting_id = "group_manual",
				type = "group",
				sub_widgets = {
					{
						setting_id = "manual_pause_enabled",
						type = "checkbox",
						default_value = true,
						tooltip = "manual_pause_enabled_desc",
					},
					{
						setting_id = "manual_pause_time",
						type = "numeric",
						default_value = 2.0,
						range = { 1, 10 },
						step_size_value = 0.5,
						decimals_number = 1,
						tooltip = "manual_pause_time_desc",
					},
					{
						setting_id = "manual_block_busy",
						type = "checkbox",
						default_value = false,
						tooltip = "manual_block_busy_desc",
					},
					{
						setting_id = "manual_block_shield",
						type = "checkbox",
						default_value = true,
						tooltip = "manual_block_shield_desc",
					},
					{
						setting_id = "manual_block_smoke",
						type = "checkbox",
						default_value = true,
						tooltip = "manual_block_smoke_desc",
					},
					{
						setting_id = "manual_block_burster",
						type = "checkbox",
						default_value = false,
						tooltip = "manual_block_burster_desc",
					},
					{
						setting_id = "dist_burster_manual",
						type = "numeric",
						default_value = 10,
						range = { 5, 50 },
						step_size_value = 1,
						tooltip = "dist_burster_manual_desc",
					},
					{
						setting_id = "block_notify",
						type = "checkbox",
						default_value = true,
						tooltip = "block_notify_desc",
					},
				},
			},
			{
				setting_id = "group_priorities",
				type = "group",
				tooltip = "group_priorities_desc",
				sub_widgets = {
					{
						setting_id = "prio_hound_close",
						type = "numeric",
						default_value = 100,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_hound_close_desc",
					},
					{
						setting_id = "dist_hound",
						type = "numeric",
						default_value = 15,
						range = { 1, 100 },
						step_size_value = 1,
						tooltip = "dist_hound_desc",
					},
					{
						setting_id = "prio_hound_far",
						type = "numeric",
						default_value = 40,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_hound_far_desc",
					},
					{
						setting_id = "prio_trapper_close",
						type = "numeric",
						default_value = 100,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_trapper_close_desc",
					},
					{
						setting_id = "dist_trapper",
						type = "numeric",
						default_value = 15,
						range = { 1, 100 },
						step_size_value = 1,
						tooltip = "dist_trapper_desc",
					},
					{
						setting_id = "prio_trapper_far",
						type = "numeric",
						default_value = 40,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_trapper_far_desc",
					},
					{
						setting_id = "prio_mutant",
						type = "numeric",
						default_value = 40,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_mutant_desc",
					},
					{
						setting_id = "prio_flamer_close",
						type = "numeric",
						default_value = 100,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_flamer_close_desc",
					},
					{
						setting_id = "dist_flamer",
						type = "numeric",
						default_value = 15,
						range = { 1, 100 },
						step_size_value = 1,
						tooltip = "dist_flamer_desc",
					},
					{
						setting_id = "prio_sniper",
						type = "numeric",
						default_value = 90,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_sniper_desc",
					},
					{
						setting_id = "prio_bomber",
						type = "numeric",
						default_value = 90,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_bomber_desc",
					},
					{
						setting_id = "prio_shotgunner_close",
						type = "numeric",
						default_value = 80,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_shotgunner_close_desc",
					},
					{
						setting_id = "dist_shotgunner",
						type = "numeric",
						default_value = 15,
						range = { 5, 30 },
						step_size_value = 1,
						tooltip = "dist_shotgunner_desc",
					},
					{
						setting_id = "prio_gunner",
						type = "numeric",
						default_value = 70,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_gunner_desc",
					},
					{
						setting_id = "prio_reaper",
						type = "numeric",
						default_value = 75,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_reaper_desc",
					},
					{
						setting_id = "prio_plasma",
						type = "numeric",
						default_value = 85,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_plasma_desc",
					},
					{
						setting_id = "prio_elite_close",
						type = "numeric",
						default_value = 60,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_elite_close_desc",
					},
					{
						setting_id = "dist_elite",
						type = "numeric",
						default_value = 10,
						range = { 5, 30 },
						step_size_value = 1,
						tooltip = "dist_elite_desc",
					},
					{
						setting_id = "prio_elite_far",
						type = "numeric",
						default_value = 0,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_elite_far_desc",
					},
					{
						setting_id = "burster_never",
						type = "checkbox",
						default_value = false,
						tooltip = "burster_never_desc",
					},
					{
						setting_id = "burster_team_radius",
						type = "checkbox",
						default_value = true,
						tooltip = "burster_team_radius_desc",
					},
					{
						setting_id = "prio_burster_far",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_burster_far_desc",
					},
					{
						setting_id = "dist_burster_forbidden",
						type = "numeric",
						default_value = 10,
						range = { 5, 50 },
						step_size_value = 1,
						tooltip = "dist_burster_forbidden_desc",
					},
					{
						setting_id = "prio_monster",
						type = "numeric",
						default_value = 30,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_monster_desc",
					},
					{
						setting_id = "prio_special_other",
						type = "numeric",
						default_value = 20,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "prio_special_other_desc",
					},
				},
			},
			{
				setting_id = "group_heal",
				type = "group",
				sub_widgets = {
					{
						setting_id = "heal_snap_enabled",
						type = "checkbox",
						default_value = true,
						tooltip = "heal_snap_enabled_desc",
					},
					{
						setting_id = "heal_snap_speed",
						type = "numeric",
						default_value = 360,
						range = { 30, 720 },
						step_size_value = 10,
						tooltip = "heal_snap_speed_desc",
					},
					{
						setting_id = "heal_snap_cone",
						type = "numeric",
						default_value = 120,
						range = { 30, 360 },
						step_size_value = 10,
						tooltip = "heal_snap_cone_desc",
					},
					{
						setting_id = "heal_auto_launch",
						type = "checkbox",
						default_value = true,
						tooltip = "heal_auto_launch_desc",
					},
					{
						setting_id = "heal_block_second",
						type = "checkbox",
						default_value = true,
						tooltip = "heal_block_second_desc",
					},
					{
						setting_id = "heal_outline_enabled",
						type = "checkbox",
						default_value = true,
						tooltip = "heal_outline_enabled_desc",
					},
				},
			},
			{
				setting_id = "group_revive_prio",
				type = "group",
				tooltip = "group_revive_prio_desc",
				sub_widgets = {
					{
						setting_id = "heal_ignore_bots",
						type = "checkbox",
						default_value = false,
						tooltip = "heal_ignore_bots_desc",
					},
					{
						setting_id = "heal_bots_last",
						type = "checkbox",
						default_value = true,
						tooltip = "heal_bots_last_desc",
					},
					{
						setting_id = "heal_prio_ogryn",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "heal_prio_ogryn_desc",
					},
					{
						setting_id = "heal_prio_zealot",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "heal_prio_zealot_desc",
					},
					{
						setting_id = "heal_prio_veteran",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "heal_prio_veteran_desc",
					},
					{
						setting_id = "heal_prio_psyker",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "heal_prio_psyker_desc",
					},
					{
						setting_id = "heal_prio_adamant",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "heal_prio_adamant_desc",
					},
					{
						setting_id = "heal_prio_cryptic",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "heal_prio_cryptic_desc",
					},
					{
						setting_id = "heal_prio_broker",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "heal_prio_broker_desc",
					},
				},
			},
		},
	},
}
