local mod = get_mod("FpsDoctor")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "show_overlay",
				type = "checkbox",
				default_value = true,
				tooltip = "show_overlay_desc",
			},
			{
				setting_id = "toggle_overlay_key",
				type = "keybind",
				default_value = { "f6" },
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "toggle_overlay",
				tooltip = "toggle_overlay_key_desc",
			},
			{
				setting_id = "anchor",
				type = "dropdown",
				default_value = "top_left",
				tooltip = "anchor_desc",
				options = {
					{ text = "anchor_top_left",     value = "top_left" },
					{ text = "anchor_top_right",    value = "top_right" },
					{ text = "anchor_bottom_left",  value = "bottom_left" },
					{ text = "anchor_bottom_right", value = "bottom_right" },
				},
			},
			{
				setting_id = "pos_x",
				type = "numeric",
				default_value = 24,
				range = { 0, 600 },
				tooltip = "pos_x_desc",
			},
			{
				setting_id = "pos_y",
				type = "numeric",
				default_value = 24,
				range = { 0, 600 },
				tooltip = "pos_y_desc",
			},
			{
				setting_id = "overlay_scale",
				type = "numeric",
				default_value = 100,
				range = { 50, 300 },
				tooltip = "overlay_scale_desc",
			},
			{
				setting_id = "opacity_text",
				type = "numeric",
				default_value = 100,
				range = { 10, 100 },
				tooltip = "opacity_text_desc",
			},
			{
				setting_id = "opacity_bg",
				type = "numeric",
				default_value = 60,
				range = { 0, 100 },
				tooltip = "opacity_bg_desc",
			},

			{
				setting_id = "show_fps",
				type = "checkbox",
				default_value = true,
				tooltip = "show_fps_desc",
			},
			{
				setting_id = "show_low",
				type = "checkbox",
				default_value = true,
				tooltip = "show_low_desc",
			},
			{
				setting_id = "show_frame_ms",
				type = "checkbox",
				default_value = true,
				tooltip = "show_frame_ms_desc",
			},
			{
				setting_id = "show_heap",
				type = "checkbox",
				default_value = true,
				tooltip = "show_heap_desc",
			},
			{
				setting_id = "show_mission",
				type = "checkbox",
				default_value = true,
				tooltip = "show_mission_desc",
			},
			{
				setting_id = "show_hitch",
				type = "checkbox",
				default_value = true,
				tooltip = "show_hitch_desc",
			},
			{
				setting_id = "hitch_ms",
				type = "numeric",
				default_value = 50,
				range = { 20, 200 },
				tooltip = "hitch_ms_desc",
			},
			{
				setting_id = "show_gc_mode",
				type = "checkbox",
				default_value = true,
				tooltip = "show_gc_mode_desc",
			},

			{
				setting_id = "reset_stats_key",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "reset_stats",
				tooltip = "reset_stats_key_desc",
			},
			{
				setting_id = "auto_reset",
				type = "checkbox",
				default_value = false,
				tooltip = "auto_reset_desc",
			},
			{
				setting_id = "auto_reset_minutes",
				type = "numeric",
				default_value = 10,
				range = { 1, 60 },
				tooltip = "auto_reset_minutes_desc",
			},

			{
				setting_id = "gc_mode",
				type = "dropdown",
				default_value = "balanced",
				tooltip = "gc_mode_desc",
				options = {
					{ text = "gc_mode_off",        value = "off" },
					{ text = "gc_mode_map_only",   value = "map_only" },
					{ text = "gc_mode_balanced",   value = "balanced" },
					{ text = "gc_mode_pacer",      value = "pacer" },
					{ text = "gc_mode_aggressive", value = "aggressive" },
				},
			},
			{
				setting_id = "smooth_collect",
				type = "checkbox",
				default_value = true,
				tooltip = "smooth_collect_desc",
			},
			{
				setting_id = "gc_pause",
				type = "numeric",
				default_value = 150,
				range = { 100, 400 },
				tooltip = "gc_pause_desc",
			},
			{
				setting_id = "gc_stepmul",
				type = "numeric",
				default_value = 200,
				range = { 100, 1000 },
				tooltip = "gc_stepmul_desc",
			},
			{
				setting_id = "gc_budget_us",
				type = "numeric",
				default_value = 1000,
				range = { 200, 4000 },
				tooltip = "gc_budget_us_desc",
			},
			{
				setting_id = "periodic_minutes",
				type = "numeric",
				default_value = 10,
				range = { 1, 30 },
				tooltip = "periodic_minutes_desc",
			},
			{
				setting_id = "threshold_mb",
				type = "numeric",
				default_value = 1024,
				range = { 256, 2048 },
				tooltip = "threshold_mb_desc",
			},
			{
				setting_id = "force_gc_key",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "force_gc",
				tooltip = "force_gc_key_desc",
			},
			{
				setting_id = "silent",
				type = "checkbox",
				default_value = false,
				tooltip = "silent_desc",
			},
		},
	},
}
