---@class DarkLib
---@field icons DL_Icons

---@param mod mod
return function(mod)

	---@class DL_Icons
	local Icons = {
		icons = {
			check = "",
			padlock_closed = "",
			padlock_open = "",
			skull_emblem = "",
			person = "",
			chevrons_up = "",
			stopwatch = "",
			caret_up = "",
			caret_right = "",
			caret_down = "",
			caret_left = "",
			number_0 = "",
			number_1 = "",
			number_2 = "",
			number_3 = "",
			number_4 = "",
			number_5 = "",
			number_6 = "",
			number_7 = "",
			number_8 = "",
			number_9 = "",
			skull_laurel = "",
			emblem_zealot = "",
			emblem_psyker_alt = "",
			skull_circle_chain = "",
			skull_simple = "",
			rank = "",
			flame = "",
			skull_radiating = "",
			emblem_veteran = "",
			emblem_psyker = "",
			emblem_ogryn = "",
			sword_down = "",
			bolt = "",
			check_badge = "",
			settings_wrench = "",
			star = "",
			plasteel = "",
			diamantine = "",
			aquila = "",
			coins = "",
			pin_badge = "",
			tickets = "",
			aquila_bars = "",
			laurel = "",
			profile_circle = "",
			skull = "",
			voice_bars_circle = "",
			aquila_badge = "",
			swords_diamond = "",
			magnifying_glass = "",
			soldier_silhouette = "",
			crown = "",
			havoc_rank = "",
			emblem_arbitrator = "",
			emblem_hive_scum = "",
			engine_cog = "",
			usb = "",
			emblem_skitarii = "",
			internet_globe = "",
			copy = "",
			happy_face = "",
			sad_face = "",
			envelope = "",
			gamepad = "",
			steam_icon = "",
			xbox_icon = "",
			playstation_icon = "",
			keyboard_icon = "",
		},
	}

	return Icons
end
