

return {
	classes = {
		Binding = {
			{ name = "kind", type = "\"fixed\"|\"source\"|\"code\"|\"thresholds\"|\"conditions\"|\"off\"|\"patch\"" },
			{ name = "on", type = "boolean?", note = "visible field: the eye override (nil = auto)" },
			{ name = "conditions", type = "ConditionSpec?", note = "conditions kind: the rule list + linger/delay", ref = "ConditionSpec" },
			{ name = "source", type = "string?", note = "source kind: source id" },
			{ name = "field", type = "string?", note = "source kind: field within the source" },
			{ name = "body", type = "string?", note = "code kind: the stored expression body" },
			{ name = "value", type = "any?", note = "nested binding, fixed kind: the static value" },
			{ name = "thresholds", type = "ThresholdSpec?", note = "thresholds kind: the bands + their current/max", ref = "ThresholdSpec" },
		},
		Block = {
			{ name = "name", type = "string", note = "block identity (== filename); derived slug of label" },
			{ name = "label", type = "string?", note = "human-readable display label (name is the slug of this)" },
			{ name = "offset", type = "number[]", note = "{ x, y } from screen center" },
			{ name = "nodes", type = "Node[]", ref = "Node" },
			{ name = "visible", type = "Binding?", note = "block-level visibility { kind, on?, body? }", ref = "Binding" },
			{ name = "folder", type = "string?", note = "folder membership (nil == root); see schema" },
			{ name = "trashed_from", type = "string?", note = "trashed blocks: the folder to restore into" },
			{ name = "deleted_nodes", type = "Node[]?", note = "the block's deleted-node bin; never compiled", ref = "Node" },
			{ name = "gamemodes", type = "table<string, boolean>?", note = "allowed gamemodes (nil == all); { mission?, mourningstar?, meatgrinder? }" },
			{ name = "classes", type = "table<string, boolean>?", note = "allowed archetype ids (nil == all)" },
			{ name = "players", type = "table<string, table<string, boolean>>?", note = "per-party-slot state filter (nil == none)" },
			{ name = "scale", type = "Binding?", note = "block-level zoom { kind = \"fixed\"|\"code\", value?, body? }", ref = "Binding" },
			{ name = "transition", type = "{ fade_in: number?, fade_out: number?, ease: string? }?", note = "block-level fade in/out" },
			{ name = "origin", type = "BlockOrigin?", note = "present == shipped by a mod; its content is that author's" },
			{ name = "script", type = "{ body: string? }?", note = "block script: code run once per frame, before everything else" },
			{ name = "state", type = "table", note = "the block script's scratch, readable from every binding as block.state" },
		},
		BlockData = {
			{ name = "version", type = "integer" },
			{ name = "name", type = "string", note = "identity AND filename; safe slug, unique" },
			{ name = "label", type = "string?", note = "optional display label (name is canonical)" },
			{ name = "offset", type = "number[]", note = "{ x, y } from screen center, 1080p px" },
			{ name = "nodes", type = "Node[]", note = "array order == Z order", ref = "Node" },
			{ name = "visible", type = "Binding?", note = "block-level visibility; nil == visible (default true)", ref = "Binding" },
			{ name = "scale", type = "Binding?", note = "block-level zoom multiplier, applied to every node's offset and geometry about the block's own origin", ref = "Binding" },
			{ name = "transition", type = "TransitionData?", note = "block-level fade in/out; nil == instant", ref = "TransitionData" },
			{ name = "script", type = "{ body: string? }?", note = "block script: code run once per frame before the block's" },
			{ name = "gamemodes", type = "table<string, boolean>?", note = "allowed gamemodes set (nil == all); { mission?, mourningstar?, meatgrinder? }" },
			{ name = "classes", type = "table<string, boolean>?", note = "allowed archetype-id set (nil == all)" },
			{ name = "players", type = "table<string, table<string, boolean>>?", note = "player-state quick filter, keyed by party slot" },
		},
		CallbackSlot = {
			{ name = "fields", type = "string[]?", note = "value slot: which node fields it binds" },
			{ name = "scope", type = "string[]", note = "names in scope, for the editor legend" },
		},
		CanvasData = {
			{ name = "version", type = "integer" },
			{ name = "grid_rows", type = "integer", note = "canvas grid row count (0 == none)" },
			{ name = "grid_cols", type = "integer", note = "canvas grid column count (0 == none)" },
			{ name = "vanilla", type = "table<string, boolean>?", note = "vanilla-HUD element toggles keyed by element id; false == that" },
			{ name = "hide_hidden_in_editor", type = "boolean?", note = "true == blocks that resolve hidden are left off the editor" },
			{ name = "buffs_offset", type = "number[]?", note = "opt-in { x, y } design-px nudge applied to the vanilla buff" },
			{ name = "folders", type = "table<string, FolderData>?", note = "Folders, keyed by name. A key existing IS the", ref = "FolderData" },
		},
		ConditionOp = {
			{ name = "id", type = "string" },
			{ name = "label", type = "string", note = "the panel dropdown's wording, and the sentence preview's verb" },
			{ name = "loc", type = "string", note = "localization key for the caption (resolved at call time:" },
			{ name = "arity", type = "integer", note = "rhs slots the row shows (0 | 1 | 2)" },
			{ name = "types", type = "table<string, boolean>", note = "DataTypes primitives this op is offered for" },
			{ name = "fn", type = "fun(lhs: any, rhs: any, rhs2: any): boolean", note = "nil for the stateful `changed`" },
			{ name = "stateful", type = "boolean?", note = "the op must run every frame, even on a short-circuited row" },
			{ name = "compare", type = "fun(previous: number, current: number): boolean|nil", note = "stateful ops only: the" },
		},
		ConditionRow = {
			{ name = "join", type = "\"and\"|\"or\"" },
			{ name = "negate", type = "boolean?" },
			{ name = "lhs", type = "Binding", ref = "Binding" },
			{ name = "op", type = "string", note = "an operator id (Conditions.OP_BY_ID)" },
			{ name = "rhs", type = "Binding?", ref = "Binding" },
			{ name = "rhs2", type = "Binding?", ref = "Binding" },
		},
		ConditionSpec = {
			{ name = "rows", type = "ConditionRow[]", ref = "ConditionRow" },
			{ name = "linger", type = "number?" },
			{ name = "delay", type = "number?" },
		},
		Context = {
			{ name = "t", type = "number", note = "game time this frame" },
			{ name = "dt", type = "number", note = "delta time this frame" },
			{ name = "player", type = "any?", note = "the local player" },
			{ name = "player_unit", type = "any?", note = "the local player's unit, if alive" },
			{ name = "gamemode", type = "string?", note = "this frame's gamemode key (\"mission\"|\"mourningstar\"|\"meatgrinder\"); set by the canvas" },
			{ name = "archetype", type = "string?", note = "the local player's canonical archetype id, or nil; set by the canvas" },
			{ name = "extensions", type = "table", note = "per-frame extension handle cache (lazy, by source)" },
			{ name = "frame_id", type = "number?", note = "monotonic frame counter; stamped by Registry.begin_frame" },
		},
		Draw = {
			{ name = "ui_renderer", type = "UIRenderer" },
			{ name = "cx", type = "number", note = "cursor x, design px (refreshed each frame via set_pointer)" },
			{ name = "cy", type = "number", note = "cursor y, design px" },
			{ name = "pressed", type = "boolean", note = "left mouse pressed edge, this frame" },
			{ name = "hold", type = "boolean", note = "left mouse held, this frame" },
			{ name = "active_id", type = "any", note = "id of the widget currently owning the press (IMGUI arbitration)" },
			{ name = "hot_id", type = "any", note = "id claiming topmost-hover this frame (last draw wins)" },
			{ name = "hot_id_prev", type = "any", note = "last frame's hot_id winner; what hover is actually gated on" },
		},
		FieldShape = {
			{ name = "type", type = "DataType", note = "the primitive the editor filters + binds on" },
			{ name = "note", type = "string|nil", note = "developer-facing description (currently unshown)" },
		},
		FolderData = {
			{ name = "visible", type = "boolean?", note = "false == every member block is forced hidden. Absent == visible." },
			{ name = "collapsed", type = "boolean?", note = "editor-only: member rows folded away. Absent == expanded." },
			{ name = "index", type = "integer?", note = "the folder's place in the tree, ascending from the top." },
		},
		FormControl = {
			{ name = "kind", type = "string", note = "\"text\"|\"numeric\"|\"dropdown\"|\"checkbox\"|\"rgba\"|\"button\"|\"readonly\"|\"note\"" },
			{ name = "label", type = "string|nil" },
			{ name = "disabled", type = "boolean|nil", note = "draws as normal but takes no input (mirrors a value owned elsewhere)" },
			{ name = "text", type = "string|nil", note = "button face text" },
			{ name = "action", type = "string|nil", note = "button semantic action the editor handles (e.g. \"delete_node\")" },
			{ name = "tooltip", type = "string|nil", note = "button: hover label, for a face too small to carry its wording" },
			{ name = "trailing", type = "boolean|nil", note = "laid on the previous control's line, pinned right at a fixed square width" },
			{ name = "token", type = "string|nil", note = "focus id for text/numeric entry (unique per node)" },
			{ name = "get", type = "fun():any|nil" },
			{ name = "set", type = "fun(v:any)|nil" },
			{ name = "value", type = "fun():string|nil", note = "readonly/note display text" },
			{ name = "wrap", type = "boolean|nil", note = "note: word-wrap the text to the column (help text) instead of one line" },
			{ name = "options", type = "table[]|fun():table[]|nil", note = "dropdown options, or a function returning them (cascading)" },
			{ name = "step", type = "number|nil", note = "numeric" },
			{ name = "min", type = "number|nil" },
			{ name = "max", type = "number|nil" },
			{ name = "decimals", type = "number|nil" },
			{ name = "right_column", type = "boolean|nil", note = "plain row: laid out in the group right column (indented past the mode dropdown), so it reads as part of the group above it" },
			{ name = "hidden", type = "fun():boolean|nil", note = "layout skips the row/control while this returns true (dynamic show/hide)" },
			{ name = "rebinds", type = "boolean|nil", note = "set() changes a binding, so the host must recompile the block after" },
		},
		FormGroup = {
			{ name = "group", type = "boolean", note = "true (marks a group row for layout)" },
			{ name = "field", type = "string" },
			{ name = "label", type = "string" },
			{ name = "mode", type = "FormControl", note = "the left-column binding-mode dropdown", ref = "FormControl" },
			{ name = "controls", type = "FormControl[]", note = "every possible right-column control (hidden-gated by mode)", ref = "FormControl" },
			{ name = "hidden", type = "fun():boolean|nil", note = "whole-group hide (e.g. under the style-patch toggle)" },
		},
		FormSection = {
			{ name = "key", type = "string" },
			{ name = "title", type = "string" },
			{ name = "flat", type = "boolean|nil", note = "no collapsible header; rows sit at the panel root, always shown" },
			{ name = "rows", type = "table[]", note = "FormControl (plain row) or FormGroup" },
		},
		Index = {
			{ name = "version", type = "integer" },
			{ name = "blocks", type = "string[]", note = "active block names, draw order == Z" },
		},
		Node = {
			{ name = "id", type = "string", note = "block-local, stable; keys the node's widget" },
			{ name = "label", type = "string", note = "node label" },
			{ name = "type", type = "string", note = "node-type id (indexes blocks/registry)" },
			{ name = "offset", type = "number[]", note = "{ x, y } from the block" },
			{ name = "style", type = "table<string, any>", note = "static base style (reset target each frame); style.visible == false hides the node (default true). style.transition is a TransitionData for fade in/out. Text node: style.align (\"left\"|\"center\"|\"right\", default left) is the horizontal alignment/grow direction." },
			{ name = "values", type = "table<string, any>", note = "static fallback values. The text node also stores its value-mode here: values.value_mode (\"single\"|\"chain\"); Chain adds per-segment slots text<i>/loc_id<i>/mode<i> (i 2..10), each mirroring the base text/loc_id/mode; each segment also gets its own rounding knob in style (style.decimals for segment 1, style.decimals<i> after it). See blocks/node_types/text." },
			{ name = "callbacks", type = "NodeCallbacks?", note = "per-slot bindings", ref = "NodeCallbacks" },
			{ name = "players", type = "table<string, table<string, boolean>>?", note = "player-state quick filter, keyed by party slot" },
		},
		NodeCallbacks = {
			{ name = "value", type = "table<string, Binding>?", ref = "Binding" },
			{ name = "style", type = "Binding?", ref = "Binding" },
		},
		PlayerField = {
			{ name = "fields", type = "table<string, FieldShape|table<string, FieldShape>>", note = "this provider's slice of the player leaf shape; a DataTypes.field(...) leaf is scalar, a nested table is a grouped field (e.g. ability -> {name, cooldown_progress, ...})" },
			{ name = "sections", type = "{ id: string, label: string }[]?", note = "optional Field-dropdown headings for this provider's own leaves; pooled across providers by players.lua and handed to the source (see Source.sections)" },
			{ name = "field_meta", type = "table<string, {label: string?, section: string?}>?", note = "optional per-leaf dropdown overrides, keyed by the full \"group.leaf\" path (e.g. \"equipment.ammo_mag_max\"); pooled the same way" },
			{ name = "write", type = "fun(values: table, player: DL_PlayerObject?, unit: Unit?, time_now: number)", note = "populate its leaves in place" },
		},
		SessionEntry = {
			{ name = "data", type = "BlockData", ref = "BlockData" },
			{ name = "block", type = "Block", ref = "Block" },
		},
		Source = {
			{ name = "id", type = "string", note = "key code binds by, and the accessor key (e.g. \"health\")" },
			{ name = "kind", type = "SourceKind", note = "\"pull\" reads state each frame; \"event\" subscribes + accumulates" },
			{ name = "category", type = "string?", note = "top-level grouping for the editor's cascading dropdown (e.g. \"player\")" },
			{ name = "label", type = "string?", note = "human name for the dropdown / palette" },
			{ name = "fields", type = "table<string, FieldShape|table<string, FieldShape>>?", note = "field name -> leaf shape (DataTypes.field) or a grouped field's leaf table; the dropdown's leaf level and the code palette" },
			{ name = "sections", type = "{ id: string, label: string }[]?", note = "ordered headings for the Field dropdown; they head the LEAVES INSIDE a group (never the top level), and a leaf with no section lists first, unheaded" },
			{ name = "field_meta", type = "table<string, {label: string?, section: string?}>?", note = "per-field dropdown overrides keyed by field path, \"group.leaf\" for the leaves a section can order (label: shown instead of the localized key; section: which heading it sits under). Validated against `fields` at register." },
			{ name = "example", type = "string?", note = "example expression, for the code palette" },
			{ name = "setup", type = "fun(bus: any)?", note = "event sources: subscribe here (mission start)" },
			{ name = "teardown", type = "fun()?", note = "event sources: unsubscribe here (mission end)" },
			{ name = "resolve", type = "fun(ctx: Context): table", note = "produce this source's value table (fields -> values)" },
		},
		TextFieldContext = {
			{ name = "token", type = "string" },
			{ name = "text", type = "string" },
			{ name = "caret", type = "integer", note = "1-based; 1 = before first char, len+1 = end" },
			{ name = "anchor", type = "integer", note = "selection anchor; == caret means no selection" },
			{ name = "on_commit", type = "fun(text: string)|nil" },
			{ name = "multiline", type = "boolean", note = "Enter inserts \\n (commit is Ctrl+Enter / click-away)" },
			{ name = "wrap_w", type = "number|nil", note = "soft-wrap width in design px; nil = no wrap" },
			{ name = "desired_col", type = "integer|nil", note = "sticky column for successive Up/Down (see move_vertical)" },
			{ name = "scroll_x", type = "number", note = "single-line horizontal scroll offset in design px (see scroll_x)" },
		},
		ThresholdEntry = {
			{ name = "pct", type = "number", note = "the band's lower edge (a percent, or a raw value)" },
			{ name = "color", type = "number[]", note = "{ a, r, g, b }" },
		},
		ThresholdSpec = {
			{ name = "list", type = "ThresholdEntry[]", ref = "ThresholdEntry" },
			{ name = "scale", type = "\"percent\"|\"number\"|\"boolean\"|nil", note = "nil reads as \"percent\"" },
			{ name = "current", type = "Binding?", ref = "Binding" },
			{ name = "max", type = "Binding?", ref = "Binding" },
		},
		TransitionData = {
			{ name = "fade_in", type = "number?", note = "duration in seconds to fade in; nil == instant" },
			{ name = "fade_out", type = "number?", note = "duration in seconds to fade out; nil == instant" },
			{ name = "ease", type = "\"linear\"|\"in_out\"?", note = "easing curve; nil / \"linear\" == linear" },
		},
		ValueEditor = {
			{ name = "kind", type = "string", note = "e.g. \"material_browser\" | \"text\" | \"number\"" },
			{ name = "modes", type = "string[]?", note = "text: e.g. { \"fixed\", \"localized\" }" },
		},
		VisualLoadoutExtension = {
			{ name = "weapon_template_from_slot", type = "fun(self: VisualLoadoutExtension, slot: string): table | nil" },
		},
	},
	params = {
		t = { type = "number", note = "game time this frame (seconds)" },
		dt = { type = "number", note = "delta time since last frame (seconds)" },
		state = { type = "table", note = "per-node persistent scratch; the one slot your code may write to (persists across frames)" },
		block = { type = "Block", note = "the block this node belongs to", ref = "Block" },
	},
	runtime = {
		sources = { type = "sources", note = "live data sources, indexed by id -- e.g. sources.player_1.status.health (or read the bare id: player_1.status.health)" },
		value = { type = "any", note = "this field's resolved value so far (style code runs after value code)" },
		style = { type = "table", note = "the style patch table; assign keys to override style (color, font_size, ...)" },
	},
	globals = {
		{ name = "math", type = "table", note = "Lua standard math library" },
		{ name = "string", type = "table", note = "Lua standard string library" },
		{ name = "table", type = "table", note = "Lua standard table library" },
		{ name = "tostring", type = "function", note = "Lua builtin" },
		{ name = "tonumber", type = "function", note = "Lua builtin" },
		{ name = "pairs", type = "function", note = "Lua builtin" },
		{ name = "ipairs", type = "function", note = "Lua builtin" },
		{ name = "select", type = "function", note = "Lua builtin" },
		{ name = "type", type = "function", note = "Lua builtin" },
		{ name = "mod", type = "DL_Mod", note = "the hud_studio mod handle (mod:localize, ...)" },
		{ name = "get_mod", type = "function", note = "fetch another mod's handle for cross-mod reads" },
		{ name = "Unit", type = "Unit", note = "read-only game Unit API" },
		{ name = "ScriptUnit", type = "ScriptUnit", note = "read-only ScriptUnit extension access" },
		{ name = "Managers", type = "Managers", note = "read-only game Managers" },
		{ name = "Color", type = "Color", note = "game Color constructor, e.g. Color.white(255, true)" },
	},
}
