local localization = {
    mod_name = {
        en = "Mechanica Automation",
        es = "Automatizacion Mechanica",
        ["pt-br"] = "Automacao Mechanica",
    },
    mod_description = {
        en = "Safe servo-skull automation for Skitarii auto ping, puzzles/tasks, and Noospheric Command.",
        es = "Automatizacion segura del servocraneo para auto ping, puzzles/tareas y Comando Noosferico.",
        ["pt-br"] = "Automacao segura do servocranio para auto ping, puzzles/tasks e Comando Noosferico.",
    },
    seconds = { en = "seconds", es = "segundos", ["pt-br"] = "segundos" },
    meters = { en = "m", es = "m", ["pt-br"] = "m" },
    percent = { en = "%%", es = "%%", ["pt-br"] = "%%" },
    degrees = { en = "deg", es = "grados", ["pt-br"] = "graus" },
    units = { en = "units", es = "unidades", ["pt-br"] = "unidades" },
    requests = { en = "requests", es = "solicitudes", ["pt-br"] = "solicitacoes" },

    language_en = { en = "English", es = "Ingles", ["pt-br"] = "Ingles" },
    language_es = { en = "Spanish", es = "Espanol", ["pt-br"] = "Espanhol" },
    language_pt_br = { en = "Portuguese Brazil", es = "Portugues Brasil", ["pt-br"] = "Portugues Brasil" },

    general_settings = { en = "General Settings", es = "Configuracion General", ["pt-br"] = "Configuracoes Gerais" },
    panel_language = { en = "Panel Language", es = "Idioma del Panel", ["pt-br"] = "Idioma do Painel" },
    panel_language_tooltip = {
        en = "Language used by Mechanica Automation notifications. DMF menu labels still follow the game language.",
        es = "Idioma usado por las notificaciones del mod. Las etiquetas del menu DMF siguen el idioma del juego.",
        ["pt-br"] = "Idioma usado pelas notificacoes do mod. Os textos do menu DMF seguem o idioma do jogo.",
    },
    toggle_mod = { en = "Enable Mod", es = "Activar Mod", ["pt-br"] = "Ativar Mod" },
    toggle_mod_tooltip = { en = "Master switch for all automation.", es = "Interruptor geral de toda automatizacion.", ["pt-br"] = "Chave geral de toda a automacao." },
    auto_ping_enabled = { en = "Auto Ping", es = "Auto Ping", ["pt-br"] = "Auto Ping" },
    auto_ping_enabled_tooltip = { en = "Enables automatic servo-skull enemy marking. The mod still requires Skitarii/Cryptic and visible line of sight.", es = "Activa la marcacion automatica de enemigos con servocraneo. El mod aun requiere Skitarii/Cryptic y linea de vision.", ["pt-br"] = "Liga a marcacao automatica de inimigos com servocranio. O mod ainda exige Skitarii/Cryptic e linha de visao." },
    toggle_mod_keybind = { en = "Toggle Keybind", es = "Tecla de Alternar", ["pt-br"] = "Tecla de Alternar" },
    toggle_notifications = { en = "Notifications", es = "Notificaciones", ["pt-br"] = "Notificacoes" },
    toggle_notifications_tooltip = { en = "Show small chat notifications when the mod is toggled.", es = "Muestra notificaciones pequenas cuando el mod cambia de estado.", ["pt-br"] = "Mostra notificacoes pequenas quando o mod muda de estado." },
    debug_mode = { en = "Debug Mode", es = "Modo Debug", ["pt-br"] = "Modo Debug" },
    debug_mode_tooltip = { en = "Print internal decisions to the mod log/chat.", es = "Imprime decisiones internas en el log/chat del mod.", ["pt-br"] = "Imprime decisoes internas no log/chat do mod." },
    global_command_cooldown = { en = "Global Command Cooldown", es = "Cooldown Global de Orden", ["pt-br"] = "Cooldown Global de Ordem" },
    global_command_cooldown_tooltip = { en = "Minimum time between servo-skull orders from this mod.", es = "Tiempo minimo entre ordenes del servocraneo hechas por este mod.", ["pt-br"] = "Tempo minimo entre ordens do servocranio feitas por este mod." },
    replace_basic_enemy_tags = { en = "Replace Basic Enemy Tags", es = "Reemplazar Marcas Basicas", ["pt-br"] = "Substituir Marcacoes Basicas" },
    replace_basic_enemy_tags_tooltip = { en = "Cancel a normal enemy ping before applying a servo-skull order on the same target.", es = "Cancela un ping normal antes de aplicar la orden del servocraneo al mismo objetivo.", ["pt-br"] = "Cancela um ping normal antes de aplicar a ordem do servocranio no mesmo alvo." },

    task_settings = { en = "Servo Artificer Puzzles", es = "Puzzles del Servo Artifice", ["pt-br"] = "Puzzles do Servo Artifice" },
    auto_tasks_enabled = { en = "Auto Puzzle / Task Orders", es = "Auto Ordenes de Puzzle / Tarea", ["pt-br"] = "Auto Ordens de Puzzle / Task" },
    auto_tasks_enabled_tooltip = { en = "Sends the servo-skull to visible hacking, objective, puzzle, scan, or interactable units that expose companion orders.", es = "Envia el servocraneo a objetivos visibles de hackeo, puzzle, escaneo o interaccion que exponen orden de companero.", ["pt-br"] = "Envia o servocranio para hacking, puzzle, scan, objetivo ou interagiveis visiveis que exponham ordem de companheiro." },
    task_interval = { en = "Puzzle Scan Interval", es = "Intervalo de Escaneo de Puzzle", ["pt-br"] = "Intervalo de Scan de Puzzle" },
    task_interval_tooltip = { en = "How often the mod searches for a puzzle/task target when no fresh contextual target was detected.", es = "Frequencia con que el mod busca un objetivo de puzzle/tarea cuando no hay contexto reciente.", ["pt-br"] = "Frequencia com que o mod procura um alvo de puzzle/task quando nao ha contexto recente." },
    task_max_range = { en = "Puzzle Max Range", es = "Alcance Maximo de Puzzle", ["pt-br"] = "Alcance Maximo de Puzzle" },
    task_max_range_tooltip = { en = "Maximum distance for automatic puzzle/task orders. Skitarii servo-skull puzzle orders are clamped to 15m for reliability.", es = "Distancia maxima para ordenes automaticas de puzzle/tarea. Las ordenes de puzzle del servocraneo Skitarii se limitan a 15m por confiabilidad.", ["pt-br"] = "Distancia maxima para ordens automaticas de puzzle/task. As ordens de puzzle do servocranio Skitarii ficam limitadas a 15m por confiabilidade." },
    task_prefer_crosshair = { en = "Prefer Crosshair Target", es = "Preferir Objetivo en Mira", ["pt-br"] = "Preferir Alvo na Mira" },
    task_prefer_crosshair_tooltip = { en = "Checks the smart-tagging target under your crosshair before other task sources.", es = "Revisa primero el objetivo smart-tag bajo tu mira antes de otras fuentes de tarea.", ["pt-br"] = "Verifica primeiro o alvo de smart-tag sob sua mira antes de outras fontes de task." },
    task_use_interactor_target = { en = "Use Interaction Focus", es = "Usar Foco de Interaccion", ["pt-br"] = "Usar Foco de Interacao" },
    task_use_interactor_target_tooltip = { en = "Also checks the interactable currently focused by the game.", es = "Tambien revisa el interactuable actualmente enfocado por el juego.", ["pt-br"] = "Tambem verifica o interagivel atualmente focado pelo jogo." },
    task_use_scannable_units = { en = "Use Objective Scan Units", es = "Usar Unidades de Objetivo", ["pt-br"] = "Usar Unidades de Objetivo" },
    task_use_scannable_units_tooltip = { en = "Also checks active auspex/scannable objective units when the mission exposes them.", es = "Tambien revisa objetivos activos de auspex/escaneo cuando la mision los expone.", ["pt-br"] = "Tambem verifica objetivos ativos de auspex/scan quando a missao expoe esses alvos." },
    task_require_los = { en = "Require Line of Sight", es = "Requerir Linea de Vision", ["pt-br"] = "Exigir Linha de Visao" },
    task_require_los_tooltip = { en = "Only send puzzle/task orders to visible targets.", es = "Solo envia ordenes de puzzle/tarea a objetivos visibles.", ["pt-br"] = "So envia ordens de puzzle/task para alvos visiveis." },
    task_ignore_pickups = { en = "Ignore Pickups / Materials", es = "Ignorar Pickups / Materiales", ["pt-br"] = "Ignorar Pickups / Materiais" },
    task_ignore_pickups_tooltip = { en = "Blocks ammo, materials, medicae, and generic pickups from being treated as puzzle/task targets.", es = "Bloquea municion, materiales, medicae y pickups genericos para no tratarlos como puzzles/tareas.", ["pt-br"] = "Bloqueia municao, materiais, medicae e pickups genericos para nao trata-los como puzzle/task." },
    task_context_memory = { en = "Context Memory", es = "Memoria de Contexto", ["pt-br"] = "Memoria de Contexto" },
    task_context_memory_tooltip = { en = "How long a manually exposed companion-order puzzle target stays cached for quick retry.", es = "Cuanto tiempo un objetivo de puzzle con orden de companero queda en cache para reintento rapido.", ["pt-br"] = "Por quanto tempo um alvo de puzzle com ordem de companheiro fica em cache para retentativa rapida." },
    task_fast_retry_on_new_context = { en = "Instant Retry on New Puzzle", es = "Reintento Instantaneo en Nuevo Puzzle", ["pt-br"] = "Retentativa Instantanea em Novo Puzzle" },
    task_fast_retry_on_new_context_tooltip = { en = "When the game exposes a fresh puzzle/task companion order, reset the task timer so the servo-skull can be sent immediately.", es = "Cuando el juego expone una nueva orden de puzzle/tarea, reinicia el temporizador para enviar el servocraneo de inmediato.", ["pt-br"] = "Quando o jogo expuser uma nova ordem de puzzle/task, zera o timer para enviar o servocranio imediatamente." },
    task_cancel_burst_on_invalid_target = { en = "Cancel Invalid Puzzle Burst", es = "Cancelar Rafaga Invalida", ["pt-br"] = "Cancelar Rajada Invalida" },
    task_cancel_burst_on_invalid_target_tooltip = { en = "Stops queued puzzle/task request pulses if the target disappears or can no longer receive smart tags.", es = "Detiene pulsos de puzzle/tarea en cola si el objetivo desaparece o ya no acepta smart tags.", ["pt-br"] = "Para pulsos de puzzle/task em fila se o alvo sumir ou nao aceitar mais smart tags." },
    task_burst_attempts = { en = "Puzzle Request Burst", es = "Rafaga de Solicitudes de Puzzle", ["pt-br"] = "Rajada de Solicitacoes de Puzzle" },
    task_burst_attempts_tooltip = { en = "How many companion-order pulses are fired when a valid puzzle/task target is found. Internally capped for stability.", es = "Cuantos pulsos de orden de companero se disparan cuando un puzzle/tarea valido es encontrado. Limitado internamente por estabilidad.", ["pt-br"] = "Quantos pulsos de ordem de companheiro sao disparados quando um puzzle/task valido e encontrado. Limitado internamente por estabilidade." },
    task_burst_spacing = { en = "Puzzle Burst Spacing", es = "Intervalo de Rafaga de Puzzle", ["pt-br"] = "Intervalo da Rajada de Puzzle" },
    task_burst_spacing_tooltip = { en = "Delay between puzzle/task request pulses. Very low values are blocked to avoid frame hitches.", es = "Demora entre pulsos de puzzle/tarea. Valores muy bajos son bloqueados para evitar tirones.", ["pt-br"] = "Intervalo entre pulsos de puzzle/task. Valores muito baixos sao bloqueados para evitar travadas de frame." },
    task_trigger_interaction = { en = "Experimental Puzzle Confirm", es = "Confirmacion Experimental de Puzzle", ["pt-br"] = "Confirmar Puzzle Experimental" },
    task_trigger_interaction_tooltip = { en = "Advanced and disabled by default. Also calls tag interaction after a puzzle/task mark. Keep off if any crash or stutter appears.", es = "Avanzado y desactivado por defecto. Tambien llama la interaccion de marca despues de un puzzle/tarea. Manten apagado si aparece crash o tiron.", ["pt-br"] = "Avancado e desligado por padrao. Tambem chama a interacao da marca depois de um puzzle/task. Mantenha desligado se houver crash ou travada." },

    noosphere_settings = { en = "Noospheric Command", es = "Comando Noosferico", ["pt-br"] = "Comando Noosferico" },
    noosphere_enabled = { en = "Auto Noospheric Re-Order", es = "Auto Reorden Noosferica", ["pt-br"] = "Auto Reordem Noosferica" },
    noosphere_enabled_tooltip = { en = "Repeats servo-skull enemy orders while the target is visible, refreshing Noospheric Command as often as configured.", es = "Repite ordenes del servocraneo mientras el objetivo esta visible.", ["pt-br"] = "Repete ordens do servocranio enquanto o alvo esta visivel." },
    noosphere_interval = { en = "Auto Mark Interval", es = "Intervalo de Auto Mark", ["pt-br"] = "Intervalo do Auto Mark" },
    noosphere_interval_tooltip = { en = "Seconds between Noospheric Command refreshes on the current visible enemy. The 1.60s default is aggressive and the mod forces a refresh if 2s are exceeded.", es = "Segundos entre refrescos del Comando Noosferico en el enemigo visible actual. El valor 1,60s es agresivo y el mod fuerza refresco si pasa de 2s.", ["pt-br"] = "Segundos entre renovacoes do Comando Noosferico no inimigo visivel atual. O padrao 1,60s e agressivo e o mod forca renovacao se passar de 2s." },
    noosphere_scan_interval = { en = "Visible Target Scan", es = "Escaneo de Objetivo Visible", ["pt-br"] = "Scan de Alvo Visivel" },
    noosphere_scan_interval_tooltip = { en = "How fast the mod refreshes the best visible enemy candidate. The default balances quick switching with lower hitch risk.", es = "Velocidad para actualizar el mejor candidato visible. El valor por defecto equilibra cambio rapido y menor riesgo de tirones.", ["pt-br"] = "Velocidade para atualizar o melhor candidato visivel. O padrao equilibra troca rapida com menor risco de travadas." },
    noosphere_max_range = { en = "Enemy Max Range", es = "Alcance Maximo de Enemigo", ["pt-br"] = "Alcance Maximo de Inimigo" },
    noosphere_max_range_tooltip = { en = "Maximum enemy distance for noospheric re-orders.", es = "Distancia maxima de enemigos para reordenes noosfericas.", ["pt-br"] = "Distancia maxima de inimigos para reordens noosfericas." },
    noosphere_cone_degrees = { en = "Visible Forward Cone", es = "Cono Frontal Visible", ["pt-br"] = "Cone Frontal Visivel" },
    noosphere_cone_degrees_tooltip = { en = "Auto ping can choose enemies visible inside this broad forward cone, so the crosshair does not need to sit on the enemy.", es = "Auto ping puede elegir enemigos visibles dentro de este cono frontal amplio, sin exigir que la mira este encima.", ["pt-br"] = "O auto ping pode escolher inimigos visiveis dentro deste cone frontal amplo, sem exigir que a mira esteja em cima." },
    noosphere_peripheral_scan = { en = "Peripheral Awareness Scan", es = "Escaneo de Conciencia Periferica", ["pt-br"] = "Scan de Consciencia Periferica" },
    noosphere_peripheral_scan_tooltip = { en = "Also checks visible enemies around you inside the radius, catching threats near screen edges without requiring crosshair aim.", es = "Tambien revisa enemigos visibles alrededor dentro del radio, capturando amenazas en los bordes de la pantalla sin exigir apuntar.", ["pt-br"] = "Tambem verifica inimigos visiveis ao redor dentro do raio, pegando ameacas nas bordas da tela sem exigir mirar em cima." },
    noosphere_peripheral_radius = { en = "Peripheral Radius", es = "Radio Periferico", ["pt-br"] = "Raio Periferico" },
    noosphere_peripheral_radius_tooltip = { en = "Visible enemy awareness radius used for fast target switching. The default 40m prepares targets before they enter the central view.", es = "Radio de conciencia de enemigos visibles usado para cambio rapido de objetivo. El valor 40m prepara objetivos antes de entrar en la vista central.", ["pt-br"] = "Raio de consciencia de inimigos visiveis usado para troca rapida de alvo. O padrao de 40m prepara alvos antes de entrarem no centro da visao." },
    noosphere_sticky_manual_target = { en = "Hold Current Target", es = "Mantener Objetivo Actual", ["pt-br"] = "Manter Alvo Atual" },
    noosphere_sticky_manual_target_tooltip = { en = "Keep refreshing the current servo-skull enemy target until it dies, becomes invalid, or leaves line of sight.", es = "Sigue refrescando el objetivo actual del servocraneo hasta que muera, se invalide o salga de linea de vision.", ["pt-br"] = "Continua renovando o alvo atual do servocranio ate ele morrer, invalidar ou sair da linha de visao." },
    noosphere_release_health_percent = { en = "Release Enemy Below HP", es = "Soltar Enemigo Bajo HP", ["pt-br"] = "Soltar Inimigo Abaixo de HP" },
    noosphere_release_health_percent_tooltip = { en = "Enemy health percentage at which the mod may stop refreshing the current marked enemy and choose another target. 0%% means never release by health.", es = "Porcentaje de vida del enemigo marcado donde el mod puede dejar de refrescar ese objetivo y elegir otro. 0%% significa nunca soltar por vida.", ["pt-br"] = "Percentual de vida do inimigo marcado em que o mod pode parar de renovar esse alvo e escolher outro. 0%% significa nunca soltar por vida." },
    noosphere_auto_target = { en = "Auto Pick Enemy", es = "Auto Elegir Enemigo", ["pt-br"] = "Auto Escolher Inimigo" },
    noosphere_auto_target_tooltip = { en = "If no sticky manual target exists, pick the best visible threat.", es = "Se no hay objetivo manual fixo, elige la mejor amenaza visible.", ["pt-br"] = "Se nao houver alvo manual fixo, escolhe a melhor ameaca visivel." },
    noosphere_trapper_max_priority = { en = "Trapper Maximum Priority", es = "Trapper Prioridad Maxima", ["pt-br"] = "Trapper Prioridade Maxima" },
    noosphere_trapper_max_priority_tooltip = { en = "Any visible trapper/netgunner outranks every other enemy.", es = "Cualquier trapper/netgunner visible supera todos los enemigos.", ["pt-br"] = "Qualquer trapper/netgunner visivel supera todos os inimigos." },
    noosphere_keep_until_dead = { en = "Keep Until Dead", es = "Mantener Hasta Morir", ["pt-br"] = "Manter Ate Morrer" },
    noosphere_keep_until_dead_tooltip = { en = "Clear sticky target only when dead, invalid, or out of sight/range.", es = "Limpia objetivo fijo solo al morir, invalidarse o salir de vision/alcance.", ["pt-br"] = "Limpa alvo fixo apenas ao morrer, invalidar ou sair da visao/alcance." },
    noosphere_skip_passive_daemonhost = { en = "Skip Passive Daemonhost", es = "Ignorar Demonhost Pasivo", ["pt-br"] = "Ignorar Demonhost Passivo" },
    noosphere_skip_passive_daemonhost_tooltip = { en = "Avoid ordering the servo-skull onto dormant daemonhosts when detectable.", es = "Evita ordenar el servocraneo contra daemonhosts dormidos cuando detectable.", ["pt-br"] = "Evita ordenar o servocranio contra daemonhosts dormentes quando detectavel." },
    smart_pox_settings = { en = "Smart Pox", es = "Pox Inteligente", ["pt-br"] = "Pox Inteligente" },
    smart_pox_enabled = { en = "Enable Smart Pox", es = "Activar Pox Inteligente", ["pt-br"] = "Ativar Pox Inteligente" },
    smart_pox_enabled_tooltip = { en = "Allows the servo-skull to prioritize pox bursters only when they are safely far away and no ally is inside the safety radius.", es = "Permite que el servocraneo priorice pox explosivos solo cuando estan a distancia segura y ningun aliado esta dentro del radio seguro.", ["pt-br"] = "Permite que o servocranio priorize pox explosivo somente quando esta longe com seguranca e sem aliado dentro do raio seguro." },
    smart_pox_max_range = { en = "Smart Pox Max Range", es = "Alcance Maximo Pox", ["pt-br"] = "Alcance Maximo do Pox" },
    smart_pox_max_range_tooltip = { en = "Maximum distance where Smart Pox may choose a pox burster.", es = "Distancia maxima donde Pox Inteligente puede elegir un pox explosivo.", ["pt-br"] = "Distancia maxima em que o Pox Inteligente pode escolher um pox explosivo." },
    smart_pox_min_distance = { en = "Minimum Kill Distance", es = "Distancia Minima de Abate", ["pt-br"] = "Distancia Minima de Abate" },
    smart_pox_min_distance_tooltip = { en = "The servo-skull never targets a pox burster at or below this distance. Minimum locked at 10m so the player can push it instead.", es = "El servocraneo nunca apunta a un pox explosivo en esta distancia o menos. Minimo bloqueado en 10m para que el jugador pueda empujarlo.", ["pt-br"] = "O servocranio nunca mira em pox explosivo nesta distancia ou menos. Minimo travado em 10m para o jogador poder empurrar." },
    smart_pox_ally_safe_radius = { en = "Ally Safety Radius", es = "Radio Seguro de Aliados", ["pt-br"] = "Raio Seguro de Aliados" },
    smart_pox_ally_safe_radius_tooltip = { en = "If any ally is this close to the pox burster, Smart Pox will not target it.", es = "Si algun aliado esta a esta distancia del pox explosivo, Pox Inteligente no lo apunta.", ["pt-br"] = "Se algum aliado estiver nesta distancia do pox explosivo, o Pox Inteligente nao mira nele." },
    smart_pox_require_los = { en = "Require Pox Line of Sight", es = "Exigir Linea de Vision Pox", ["pt-br"] = "Exigir Linha de Visao do Pox" },
    smart_pox_require_los_tooltip = { en = "Only use Smart Pox when the pox burster is visible.", es = "Usa Pox Inteligente solo cuando el pox explosivo esta visible.", ["pt-br"] = "Usa o Pox Inteligente somente quando o pox explosivo esta visivel." },
    advanced_settings = { en = "HUD Alerts", es = "Alertas HUD", ["pt-br"] = "Alertas HUD" },
    alert_hud_enabled = { en = "Threat HUD Alerts", es = "Alertas HUD de Amenaza", ["pt-br"] = "Alertas HUD de Ameaca" },
    alert_hud_enabled_tooltip = { en = "Shows a safe DMF HUD notification for nearby trappers and pox bursters, without registering custom HUD elements.", es = "Muestra una notificacion HUD segura de DMF para trappers y pox explosivos cercanos, sin registrar elementos HUD personalizados.", ["pt-br"] = "Mostra uma notificacao HUD segura do DMF para trappers e pox explosivos proximos, sem registrar elementos HUD customizados." },
    alert_hud_range = { en = "Alert Range", es = "Rango de Alerta", ["pt-br"] = "Alcance do Alerta" },
    alert_hud_range_tooltip = { en = "Maximum distance for trapper/pox alert notifications.", es = "Distancia maxima para notificaciones de trapper/pox.", ["pt-br"] = "Distancia maxima para notificacoes de trapper/pox." },
    alert_hud_interval = { en = "Alert Refresh", es = "Refresco de Alerta", ["pt-br"] = "Atualizacao do Alerta" },
    alert_hud_interval_tooltip = { en = "Minimum time between repeated threat alerts.", es = "Tiempo minimo entre alertas repetidas de amenaza.", ["pt-br"] = "Tempo minimo entre alertas repetidos de ameaca." },

    enemy_scan_budget = { en = "Enemy Scan Budget", es = "Presupuesto de Escaneo", ["pt-br"] = "Orcamento de Scan" },
    enemy_scan_budget_tooltip = { en = "Maximum enemies inspected per logic tick. The default is conservative to reduce render/physics hitch risk.", es = "Maximo de enemigos revisados por tick. El valor por defecto es conservador para reducir tirones de render/fisica.", ["pt-br"] = "Maximo de inimigos revisados por tick. O padrao e conservador para reduzir risco de travadas de render/fisica." },
    los_cache_frames = { en = "LOS Cache Frames", es = "Frames de Cache LOS", ["pt-br"] = "Frames de Cache LOS" },
    los_cache_frames_tooltip = { en = "Reuse line-of-sight results for this many fixed frames.", es = "Reutiliza resultados de linea de vision por esta cantidad de frames.", ["pt-br"] = "Reutiliza resultados de linha de visao por esta quantidade de frames." },
    physics_safe_commands = { en = "Physics-Safe Commands", es = "Ordenes Physics-Safe", ["pt-br"] = "Ordens Physics-Safe" },
    physics_safe_commands_tooltip = { en = "Schedule servo-skull orders through the game's physics-safe callback when available.", es = "Agenda ordenes por callback seguro de fisica cuando disponible.", ["pt-br"] = "Agenda ordens pelo callback seguro de fisica quando disponivel." },
    disable_in_hub = { en = "Disable in Hub", es = "Desactivar en Hub", ["pt-br"] = "Desativar no Hub" },
    disable_in_hub_tooltip = { en = "Do not run mission automation in social/prologue hubs.", es = "No ejecuta automatizacion en hubs sociales/prologo.", ["pt-br"] = "Nao executa automacao em hubs sociais/prologo." },
}

return localization
