local mod = get_mod("scores")
return {
	name = mod:localize("mod_title"),
	description = mod:localize("mod_description"),
	is_togglable = false,
	allow_rehooking = true,
	options = {
		widgets = {
			{["setting_id"] = "group_general",
				["type"] = "group",
				["text"] = "group_general",
				["sub_widgets"] = {
					{["setting_id"] = "tactical_overview",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip_text"] = "tactical_overview_description",
					},
					{["setting_id"] = "show_scoreboard_on_mission_end",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip_text"] = "show_scoreboard_on_mission_end_description",
					},
					{["setting_id"] = "toggle_end_scoreboard_visibility",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "toggle_end_scoreboard_visibility",
						["tooltip_text"] = "toggle_end_scoreboard_visibility_description",
					},
					{["setting_id"] = "hide_legacy_ui",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip_text"] = "hide_legacy_ui_description",
					},
					{["setting_id"] = "me_first",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip_text"] = "me_first_description",
					},
				},
			},
			{["setting_id"] = "group_display",
				["type"] = "group",
				["text"] = "display_header",
				["sub_widgets"] = {
					{["setting_id"] = "player_name_display",
						["type"] = "dropdown",
						["default_value"] = "character",
						["tooltip_text"] = "player_name_display_description",
						["options"] = {
							{["text"] = "player_name_display_character", ["value"] = "character", ["show_widgets"] = {}},
							{["text"] = "player_name_display_account", ["value"] = "account", ["show_widgets"] = {}},
							{["text"] = "player_name_display_both", ["value"] = "both", ["show_widgets"] = {}},
						},
					},
					{["setting_id"] = "zero_values",
						["type"] = "dropdown",
						["default_value"] = 1,
						["tooltip_text"] = "zero_values_description",
						["options"] = {
							{["text"] = "zero_values_normal", ["value"] = 1, ["show_widgets"] = {}},
							{["text"] = "zero_values_hide", ["value"] = 2, ["show_widgets"] = {}},
							{["text"] = "zero_values_dark", ["value"] = 3, ["show_widgets"] = {}},
						},
					},
					{["setting_id"] = "worst_values",
						["type"] = "dropdown",
						["default_value"] = 1,
						["tooltip_text"] = "worst_values_description",
						["options"] = {
							{["text"] = "worst_values_normal", ["value"] = 1, ["show_widgets"] = {}},
							{["text"] = "worst_values_dark", ["value"] = 2, ["show_widgets"] = {}},
						},
					},
					{["setting_id"] = "row_backgrounds",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip_text"] = "row_backgrounds_description",
					},
					{["setting_id"] = "opaque_scoreboard_backdrop",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip_text"] = "opaque_scoreboard_backdrop_description",
					},
				},
			},
			{["setting_id"] = "group_stat_options",
				["type"] = "group",
				["text"] = "stat_options_header",
				["sub_widgets"] = {
					{["setting_id"] = "ammo_efficiency",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip_text"] = "ammo_efficiency_description",
					},
					{["setting_id"] = "split_damage_dealt",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip_text"] = "split_damage_dealt_description",
					},
					{["setting_id"] = "split_resources_collected",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip_text"] = "split_resources_collected_description",
					},
					{["setting_id"] = "show_melee_ranged_kills",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip_text"] = "show_melee_ranged_kills_description",
					},
					{["setting_id"] = "detailed_kill_split",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip_text"] = "detailed_kill_split_description",
					},
				},
			},
			{["setting_id"] = "group_row_toggles",
				["type"] = "group",
				["text"] = "row_toggle_header",
				["sub_widgets"] = {
					{["setting_id"] = "group_row_toggles_offense",
						["type"] = "group",
						["text"] = "section_offense",
						["sub_widgets"] = {
							{["setting_id"] = "show_weakspot_hits",
								["type"] = "checkbox",
								["default_value"] = false,
							},
							{["setting_id"] = "show_weakspot_hit_percent",
								["type"] = "checkbox",
								["default_value"] = true,
								["tooltip_text"] = "show_weakspot_hit_percent_description",
							},
							{["setting_id"] = "show_accuracy",
								["type"] = "checkbox",
								["default_value"] = true,
								["tooltip_text"] = "show_accuracy_description",
							},
							{["setting_id"] = "show_critical_hits",
								["type"] = "checkbox",
								["default_value"] = false,
								["tooltip_text"] = "show_critical_hits_description",
							},
							{["setting_id"] = "show_boss_damage_dealt",
								["type"] = "checkbox",
								["default_value"] = false,
							},
						},
					},
					{["setting_id"] = "group_row_toggles_defense",
						["type"] = "group",
						["text"] = "section_defense",
						["sub_widgets"] = {
							{["setting_id"] = "show_times_downed",
								["type"] = "checkbox",
								["default_value"] = true,
							},
							{["setting_id"] = "show_deaths",
								["type"] = "checkbox",
								["default_value"] = false,
							},
							{["setting_id"] = "show_times_disabled",
								["type"] = "checkbox",
								["default_value"] = false,
							},
							{["setting_id"] = "show_attacks_blocked",
								["type"] = "checkbox",
								["default_value"] = false,
							},
							{["setting_id"] = "show_heal_station_used",
								["type"] = "checkbox",
								["default_value"] = false,
							},
						},
					},
					{["setting_id"] = "group_row_toggles_support",
						["type"] = "group",
						["text"] = "section_support",
						["sub_widgets"] = {
							{["setting_id"] = "show_revived_rescued",
								["type"] = "checkbox",
								["default_value"] = true,
							},
							{["setting_id"] = "show_team_saves",
								["type"] = "checkbox",
								["default_value"] = true,
							},
							{["setting_id"] = "show_coherency_efficiency",
								["type"] = "checkbox",
								["default_value"] = false,
							},
							{["setting_id"] = "show_ammo_collected",
								["type"] = "checkbox",
								["default_value"] = false,
							},
							{["setting_id"] = "show_resources_collected",
								["type"] = "checkbox",
								["default_value"] = false,
							},
						},
					},
				},
			},
			{["setting_id"] = "group_scoreboard_history",
				["type"] = "group",
				["text"] = "scoreboard_history_header",
				["sub_widgets"] = {
					{["setting_id"] = "open_scoreboard_history",
						["type"] = "keybind",
						["default_value"] = {"f5"},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "open_scoreboard_history",
						["tooltip_text"] = "open_scoreboard_history_description",
					},
					{["setting_id"] = "history_save_mode",
						["type"] = "dropdown",
						["default_value"] = 2,
						["tooltip_text"] = "history_save_mode_description",
						["options"] = {
							{["text"] = "history_save_mode_none", ["value"] = 1, ["show_widgets"] = {}},
							{["text"] = "history_save_mode_all", ["value"] = 2, ["show_widgets"] = {}},
							{["text"] = "history_save_mode_havoc", ["value"] = 3, ["show_widgets"] = {}},
						},
					},
				},
			},
			{["setting_id"] = "group_layout",
				["type"] = "group",
				["text"] = "layout_options_header",
				["sub_widgets"] = {
					{["setting_id"] = "end_scoreboard_vertical_offset",
						["type"] = "numeric",
						["default_value"] = 0,
						["range"] = {-200, 200},
						["tooltip_text"] = "end_scoreboard_vertical_offset_description",
					},
				},
			},
			{["setting_id"] = "group_developer_options",
				["type"] = "group",
				["text"] = "developer_options_header",
				["sub_widgets"] = {
					{["setting_id"] = "dev_mode",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip_text"] = "dev_mode_description",
						["sub_widgets"] = {
							{["setting_id"] = "open_scoreboard",
								["type"] = "keybind",
								["default_value"] = {"f6"},
								["keybind_trigger"] = "pressed",
								["keybind_type"] = "function_call",
								["function_name"] = "open_scoreboard",
								["tooltip_text"] = "open_scoreboard_description",
							},
							{["setting_id"] = "developer_diagnostics",
								["type"] = "keybind",
								["default_value"] = {},
								["keybind_trigger"] = "pressed",
								["keybind_type"] = "function_call",
								["function_name"] = "developer_diagnostics",
								["tooltip_text"] = "developer_diagnostics_description",
							},
						},
					},
				},
			},
		},
	},
}


