return {
    mod_name = {
        en = "Zip It!",
        ["zh-cn"] = "闭嘴！",
        de = "Sei Leise!",
        fr = "La ferme!",
        ru = "Заткнись!",
    },
	mod_description = {
		en = "Tell those characters to ZIP IT!\nAllows toggling of in-game dialog from NPCs, characters, and enemies.",
		["zh-cn"] = "让那些角色闭嘴！允许切换NPC、角色和敌人的游戏对话。",
		de = "Sag diesen Charakteren, sie sollen den Mund halten!\nErmöglicht das Umschalten von In-Game-Dialogen von NPCs, Charakteren und Feinden.",
		fr = "Dites à ces personnages de SE TAIRE !\nPermet de désactiver les dialogues en jeu des PNJ, des personnages et des ennemis.",
		ru = "Заставьте этих персонажей ЗАТКНУТЬСЯ!\nПозволяет переключать игровые диалоги NPC, персонажей и врагов.",
	},
	disableAll = {
		en = "Disable All Dialogue",
		de = "Alle Dialoge deaktivieren",
		fr = "Désactiver tous les dialogues",
		ru = "Отключить весь диалог",
		["zh-cn"] = "禁用所有对话",
	},
	subtitles = {
		en = "Subtitles",
		["zh-cn"] = "字幕",
		de = "Untertitel",
		fr = "Sous-titres",
		ru = "Субтитры",
	},
	subtitles_description = {
		en = "When disabled, subtitles will not show when dialog is suppressed.",
		["zh-cn"] = "禁用时，抑制对话时不会显示字幕。",
		de = "Wenn deaktiviert, werden Untertitel nicht angezeigt, wenn Dialoge unterdrückt werden.",
		fr = "Lorsqu'il est désactivé, les sous-titres ne s'affichent pas lorsque les dialogues sont supprimés.",
		ru = "Когда отключено, субтитры не будут отображаться при подавлении диалогов.",
	},
	debug = {
		en = "Debug Mode",
		["zh-cn"] = "调试模式",
		de = "Debug-Modus",
		fr = "Mode Debug",
		ru = "Режим отладки",
	},
	debug_description = {
		en = "Enable this to show a message when unhandled dialog plays, in case a certain voiceline still plays. Only useful if you want to report to the mod page!",
		["zh-cn"] = "启用此选项以在未处理的对话播放时显示消息，以防某些语音仍会播放。仅在您想报告给模组页面时有用！",
		de = "Aktiviere dies, um eine Nachricht anzuzeigen, wenn unverwalteter Dialog abgespielt wird, falls eine bestimmte Sprachzeile noch abgespielt wird. Nur nützlich, wenn du dies der Mod-Seite melden möchtest!",
		fr = "Activez ceci pour afficher un message lorsqu'un dialogue non géré est joué, au cas où une certaine ligne de dialogue serait toujours jouée. Utile uniquement si vous souhaitez le signaler sur la page du mod !",
		ru = "Включите это, чтобы показать сообщение, когда воспроизводится необработанный диалог, на случай, если какая-то определенная реплика все еще воспроизводится. Полезно только в том случае, если вы хотите сообщить об этом на странице мода!",
	},
	hub_toggles = {
		en = "Mourningstar",
		["zh-cn"] = "晨星",
		de = "Morgenstern",
		fr = "Mourningstar",
		ru = "Утренняя звезда",
	},
	hub_toggles_tooltip = {
		en = "Turn off/on voicelines within the lobby",
		["zh-cn"] = "关闭/开启大厅中的语音",
		de = "Sprachzeilen in der Lobby ein-/ausschalten",
		fr = "Activer/désactiver les répliques vocales dans le hall",
		ru = "Включить/выключить реплики в лобби",
	},
	mission_toggles = {
		en = "Mission",
		["zh-cn"] = "任务",
		de = "Mission",
		fr = "Mission",
		ru = "Миссия",
	},
	mission_toggles_tooltip = {
		en = "Turn off/on voicelines during a mission",
		["zh-cn"] = "关闭/开启任务中的语音",
		de = "Sprachzeilen während einer Mission ein-/ausschalten",
		fr = "Activer/désactiver les répliques vocales pendant une mission",
		ru = "Включить/выключить реплики во время миссии",
	},
	enemy_toggles = {
		en = "Enemy",
		["zh-cn"] = "敌人",
		de = "Feind",
		fr = "Ennemi",
		ru = "Враг",
	},
	enemy_toggles_tooltip = {
		en = "Turn off/on voicelines of enemies",
		["zh-cn"] = "关闭/开启敌人的语音",
		de = "Sprachzeilen von Feinden ein-/ausschalten",
		fr = "Activer/désactiver les répliques vocales des ennemis",
		ru = "Включить/выключить реплики врагов",
	},
	player_toggles = {
		en = "Player character",
		["zh-cn"] = "玩家角色",
		de = "Spielercharakter",
		fr = "Personnage joueur",
		ru = "Персонаж игрока",
	},
	player_toggles_tooltip = {
		en = "Turn off/on voicelines of your character",
		["zh-cn"] = "关闭/开启你角色的语音",
		de = "Sprachzeilen deines Charakters ein-/ausschalten",
		fr = "Activer/désactiver les répliques vocales de votre personnage",
		ru = "Включить/выключить реплики вашего персонажа",
	},
	team_toggles = {
		en = "Team characters",
		["zh-cn"] = "队伍角色",
		de = "Teamcharaktere",
		fr = "Personnages de l'équipe",
		ru = "Персонажи команды",
	},
	team_toggles_tooltip = {
		en = "Turn off/on voicelines of your team characters",
		["zh-cn"] = "关闭/开启你队伍角色的语音",
		de = "Sprachzeilen deiner Teamcharaktere ein-/ausschalten",
		fr = "Activer/désactiver les répliques vocales de vos personnages d'équipe",
		ru = "Включить/выключить реплики персонажей вашей команды",
	},
	hub_radio = {
		en = "Radio",
		["zh-cn"] = "广播",
		de = "Radio",
		fr = "Radio",
		ru = "Радио",
	},
	hub_vox = {
		en = "Vox Announcements",
		["zh-cn"] = "Vox公告",
		de = "Vox-Ankündigungen",
		fr = "Annonces Vox",
		ru = "Объявления Vox",
	},
	hub_soldier = {
		en = "Soldier commentary",
		["zh-cn"] = "士兵评论",
		de = "Soldatenkommentare",
		fr = "Commentaire du soldat",
		ru = "Комментарий солдата",
	},
	hub_conversation = {
		en = "Conversation",
		["zh-cn"] = "对话",
		de = "Gespräch",
		fr = "Conversation",
		ru = "Разговор",
	},
	hub_hallowette = {
		en = "The Commodore's Vestures",
		["zh-cn"] = "准将的服饰",
		de = "Die Gewänder des Kommodore",
		fr = "Les Habits du Commodore",
		ru = "Одеяния Коммодора",
	},
	hub_siremelk = {
		en = "Sire Melk's Requisitorium",
		["zh-cn"] = "梅尔克大人的征用处",
		de = "Sire Melks Requisitorium",
		fr = "Requisitorium de Sire Melk",
		ru = "Реквизиторий Сира Мелка",
	},
	hub_commissary = {
		en = "Commissary",
		["zh-cn"] = "军需处",
		de = "Kommissariat",
		fr = "Commissariat",
		ru = "Комиссариат",
	},
	hub_krall = {
		en = "Barber-Chirurgeon",
		["zh-cn"] = "外科医生",
		de = "Barbier-Chirurg",
		fr = "Barbier-Chirurgien",
		ru = "Цирюльник-хирург",
	},
	hub_armoury = {
		en = "Armoury Exchange",
		["zh-cn"] = "军械交换",
		de = "Rüstungsaustausch",
		fr = "Échange d'armurerie",
		ru = "Обмен оружием",
	},
	hub_hadron = {
		en = "Shrine of the Omnissiah",
		["zh-cn"] = "Omnissiah神殿",
		de = "Schrein des Omnissiah",
		fr = "Sanctuaire de l'Omnissiah",
		 ru = "Святилище Омниссии",
	},
	hub_sefoni = {
		en = "Psykhanium",
		["zh-cn"] = "心灵秘境",
		de = "Psykhanium",
		fr = "Psykhanium",
		ru = "Психаниум",
	},
	hub_hestia = {
		en = "Shrine Penitentax",
		["zh-cn"] = "忏悔者神殿",
		de = "Schrein Penitentax",
		fr = "Sanctuaire Penitentax",
		ru = "Святилище Покаяния",
	},
	mission_brief = {
		en = "Briefing",
		["zh-cn"] = "简报",
		de = "Briefing",
		fr = "Briefing",
		ru = "Инструктаж",
	},
	mission_info = {
		en = "Mission information",
		["zh-cn"] = "任务信息",
		de = "Missionsinformationen",
		fr = "Informations de mission",
		ru = "Информация о миссии",
	},
	mission_conversation = {
		en = "Mission conversation",
		["zh-cn"] = "任务对话",
		de = "Missionsgespräch",
		fr = "Conversation de mission",
		ru = "Разговор о миссии",
	},
	mission_lore = {
		en = "Lore",
		["zh-cn"] = "背景知识",
		de = "Überlieferung",
		fr = "Tradition",
		ru = "Лор",
	},
	enemy_demonhost = {
		en = "Daemonhost",
		["zh-cn"] = "恶魔宿主",
		de = "Daemonenwirt",
		fr = "Hôte Daemon",
		ru = "Демонический хозяин",
	},
	enemy_flamer = {
		en = "Flamer",
		["zh-cn"] = "火焰喷射兵",
		de = "Flammenwerfer",
		fr = "Lance-flammes",
		ru = "Огнеметчик",
	},
	enemy_flamer_spawned = {
		en = "Flamer Spawn",
		["zh-cn"] = "火焰喷射兵生成",
		de = "Flammenwerfer Spawn",
		fr = "Génération Lance-flammes",
		ru = "Появление огнеметчика",
	},
	enemy_fire_grenadier = {
		en = "Fire Bomber",
		["zh-cn"] = "火焰轰炸机",
		de = "Feuerbomber",
		fr = "Bombardier de feu",
		ru = "Огненный бомбардировщик",
	},
	enemy_gas_grenadier = {
		en = "Gas Bomber",
		["zh-cn"] = "毒气轰炸机",
		de = "Gasbomber",
		fr = "Bombardier de gaz",
		ru = "Газовый бомбардировщик",
	},
	enemy_fire_grenadier_spawn = {
		en = "Fire Bomber Spawn",
		["zh-cn"] = "火焰轰炸机生成",
		de = "Feuerbomber Spawn",
		fr = "Génération Bombardier de feu",
		ru = "Появление огненного бомбардировщика",
	},
	enemy_gas_grenadier_spawn = {
		en = "Gas Bomber Spawn",
		["zh-cn"] = "毒气轰炸机生成",
		de = "Gasbomber Spawn",
		fr = "Génération Bombardier de gaz",
		ru = "Появление газового бомбардировщика",
	},
	enemy_gunner = {
		en = "Gunner",
		["zh-cn"] = "枪手",
		de = "Schütze",
		fr = "Artilleur",
		ru = "Стрелок",
	},
	enemy_berzerker = {
		en = "Rager",
		["zh-cn"] = "狂战士",
		de = "Wüter",
		fr = "Furieux",
		ru = "Яростный",
	},
	enemy_netgunner = {
		en = "Trapper",
		["zh-cn"] = "陷阱者",
		de = "Fänger",
		fr = "Trappeur",
		ru = "Ловчий",
	},
	enemy_netgunner_spawn = {
		en = "Trapper Spawn",
		["zh-cn"] = "陷阱者生成",
		de = "Fänger Spawn",
		fr = "Génération Trappeur",
		ru = "Появление ловчего",
	},
	enemy_infantry = {
		en = "Infantry",
		["zh-cn"] = "步兵",
		de = "Infanterie",
		fr = "Infanterie",
		ru = "Пехота",
	},
	enemy_mauler = {
		en = "Mauler",
		["zh-cn"] = "狂暴者",
		de = "Schläger",
		fr = "Massacreur",
		ru = "Измельчитель",
	},
	enemy_shooter = {
		en = "Shooter",
		["zh-cn"] = "射手",
		de = "Schütze",
		fr = "Tireur",
		ru = "Стрелок",
	},
	enemy_shotgunner = {
		en = "Shotgunner",
		["zh-cn"] = "霰弹枪手",
		de = "Schrotflintenschütze",
		fr = "Fusilier",
		ru = "Дробовик",
	},
	enemy_bulwark = {
		en = "Bulwark",
		["zh-cn"] = "壁垒",
		de = "Bollwerk",
		fr = "Rempart",
		ru = "Оплот",
	},
	enemy_crusher = {
		en = "Crusher",
		["zh-cn"] = "粉碎者",
		de = "Brecher",
		fr = "Écraseur",
		ru = "Дробитель",
	},
	enemy_reaper = {
		en = "Reaper",
		["zh-cn"] = "收割者",
		de = "Schnitter",
		fr = "Faucheur",
		ru = "Жнец",
	},
	player_death = {
		en = "Death",
		["zh-cn"] = "死亡",
		de = "Tod",
		fr = "Mort",
		ru = "Смерть",
	},
	player_ability = {
		en = "Ability",
		["zh-cn"] = "能力",
		de = "Fähigkeit",
		fr = "Capacité",
		ru = "Способность",
	},
	player_kill = {
		en = "Enemy kill",
		["zh-cn"] = "击杀敌人",
		de = "Feind töten",
		fr = "Tuer l'ennemi",
		ru = "Убить врага",
	},
	player_headshot = {
		en = "Headshot",
		["zh-cn"] = "爆头",
		de = "Kopfschuss",
		fr = "Tir à la tête",
		ru = "Выстрел в голову",
	},
	player_horde = {
		en = "Horde",
		["zh-cn"] = "暴民",
		de = "Horde",
		fr = "Horde",
		ru = "Орда",
	},
	player_tag_item = {
		en = "Tag item",
		["zh-cn"] = "标记物品",
		de = "Gegenstand markieren",
		fr = "Marquer l'objet",
		ru = "Пометить предмет",
	},
	player_tag_enemy = {
		en = "Tag enemy",
		["zh-cn"] = "标记敌人",
		de = "Feind markieren",
		fr = "Marquer l'ennemi",
		ru = "Пометить врага",
	},
	player_look = {
		en = "Guidance",
		["zh-cn"] = "指导",
		de = "Anleitung",
		fr = "Orientation",
		ru = "Руководство",
	},
	player_throw = {
		en = "Throw",
		["zh-cn"] = "投掷",
		de = "Werfen",
		fr = "Lancer",
		ru = "Бросать",
	},
	player_wheel = {
		en = "Communication wheel",
		["zh-cn"] = "沟通轮盘",
		de = "Kommunikationsrad",
		fr = "Roue de communication",
		ru = "Колесо общения",
	},
	player_blitz = {
		en = "Blitz",
		["zh-cn"] = "闪电战",
		de = "Blitz",
		fr = "Blitz",
		ru = "Блиц",
	},
	player_info = {
		en = "Info",
		["zh-cn"] = "信息",
		de = "Info",
		fr = "Info",
		ru = "Информация",
	},
	team_advice = {
		en = "Come Back",
		de = "Komm zurück",
		fr = "Reviens",
		ru = "Вернись",
		["zh-cn"] = "回来",
	},
	team_help = {
		en = "Help",
		["zh-cn"] = "帮助",
		de = "Hilfe",
		fr = "Aide",
		ru = "Помощь",
	},
	team_warning = {
		en = "Warning",
		["zh-cn"] = "警告",
		de = "Warnung",
		fr = "Avertissement",
		ru = "Предупреждение",
	},
	team_hacking = {
		en = "Hacking",
		["zh-cn"] = "黑客",
		de = "Hacken",
		fr = "Pirater",
		ru = "Взлом",
	},
	team_revive = {
		en = "Revive",
		["zh-cn"] = "复活",
		de = "Wiederbeleben",
		fr = "Réanimer",
		ru = "Возрождать",
	},
	team_downed = {
		en = "Downed",
		["zh-cn"] = "击倒",
		de = "Niedergeschlagen",
		fr = "Abattu",
		ru = "Повержен",
	},
	team_monster = {
		en = "Monster",
		["zh-cn"] = "怪物",
		de = "Monster",
		fr = "Monstre",
		ru = "Монстр",
	},
	misc = {
		en = "Misc",
		de = "Verschiedenes",
		fr = "Divers",
		ru = "Разное",
		["zh-cn"] = "杂项",
	},
	misc_medicae = {
		en = "Health",
		de = "Gesundheit",
		fr = "Santé",
		ru = "Здоровье",
		["zh-cn"] = "生命值",
	},
}