return {
	mod_name = {
		en = "Health Scaling",
		de = "Gesundheitsskalierung",
		fr = "Échelonnage de Santé",
		ru = "Масштабирование Здоровья",
		["zh-cn"] = "生命值缩放",
	},
	mod_description = {
		en = "Scales health and toughness bars based on their maximum values.",
		de = "Skaliert die Gesundheits- und Zähigkeitsbalken basierend auf ihren Maximalwerten.",
		fr = "Échelonne les barres de santé et de robustesse en fonction de leurs valeurs maximales.",
		ru = "Масштабирует полоски здоровья и стойкости на основе их максимальных значений.",
		["zh-cn"] = "根据最大值缩放生命值和韧性条。",
	},
	toughnessScale = {
		en = "Toughness Bar Scalar",
		de = "Zähigkeitsbalken-Skalar",
		fr = "Échelle de Barre de Robustesse",
		ru = "Масштаб полосы стойкости",
		["zh-cn"] = "韧性条缩放",
	},
	toughnessAnimation = {
		en = "Toughness Bar Animation",
		de = "Zähigkeitsbalken-Animation",
		fr = "Animation de la Barre de Robustesse",
		ru = "Анимация полосы стойкости",
		["zh-cn"] = "韧性条动画",
	},
	animationSpeed = {
		en = "Animation Speed",
		de = "Animationsgeschwindigkeit",
		fr = "Vitesse de l'animation",
		ru = "Скорость анимации",
		["zh-cn"] = "动画速度",
	},
	healthScale = {
		en = "Health Bar Scalar",
		de = "Gesundheitsbalken-Skalar",
		fr = "Échelle de Barre de Santé",
		ru = "Масштаб полосы здоровья",
		["zh-cn"] = "生命条缩放",
	},
	logScaling = {
		en = "Use Logarithmic Scaling",
		de = "Logarithmische Skalierung verwenden",
		fr = "Utiliser l'échelle logarithmique",
		ru = "Использовать логарифмическое масштабирование",
		["zh-cn"] = "使用对数缩放",
	},
	logScale = {
		en = "Logarithmic Scalar",
		de = "Logarithmischer Skalar",
		fr = "Échelle logarithmique",
		ru = "Логарифмический скаляр",
		["zh-cn"] = "对数缩放",
	},
	moveBuffs = {
		en = "Move Buffs Icons",
		de = "Verschieben der Buff-Symbole",
		fr = "Déplacer les icônes de buffs",
		ru = "Переместить иконки баффов",
		["zh-cn"] = "移动增益图标",
	},
	moveCoherency = {
		en = "Move Coherency Icons",
		de = "Verschieben der Kohärenz-Symbole",
		fr = "Déplacer les icônes de cohérence",
		ru = "Переместить иконки сплочённости",
		["zh-cn"] = "移动连队图标",
	},
	toughnessScale_description = {
		en = "Scales the size of toughness bars.\nFor log scaling, use larger values.",
		de = "Skaliert die Größe der Zähigkeitsbalken.\nFür logarithmische Skalierung größere Werte verwenden.",
		fr = "Échelonne la taille des barres de robustesse.\nPour un échelonnage logarithmique, utilisez des valeurs plus grandes.",
		ru = "Изменяет размер полос стойкости.\nДля логарифмического масштабирования используйте большие значения.",
		["zh-cn"] = "缩放韧性条的大小。\n对数缩放请使用更大的值。",
	},
	toughnessAnimation_description = {
		en = "Animates the size increase/decrease of the toughness bar from bonus toughness.",
		de = "Animiert die Vergrößerung/Verkleinerung des Zähigkeitsbalkens durch Bonuszähigkeit.",
		fr = "Anime l'augmentation/diminution de la taille de la barre de robustesse en fonction du bonus de robustesse.",
		ru = "Анимирует увеличение/уменьшение полосы стойкости за счёт бонусной стойкости.",
		["zh-cn"] = "为韧性条的增减提供动画效果，源自额外的韧性加成。",
	},
	healthScale_description = {
		en = "Scales the size of health bars.\nFor log scaling, use larger values.",
		de = "Skaliert die Größe der Gesundheitsbalken.\nFür logarithmische Skalierung größere Werte verwenden.",
		fr = "Échelonne la taille des barres de santé.\nPour un échelonnage logarithmique, utilisez des valeurs plus grandes.",
		ru = "Изменяет размер полос здоровья.\nДля логарифмического масштабирования используйте большие значения.",
		["zh-cn"] = "缩放生命条的大小。\n对数缩放请使用更大的值。",
	},
	logScaling_description = {
		en = "Compresses health bars based on their size.\nHelps prevent massive health bars from getting too large.",
		de = "Komprimiert Gesundheitsbalken basierend auf ihrer Größe.\nHilft, zu große Gesundheitsbalken zu vermeiden.",
		fr = "Comprime les barres de santé en fonction de leur taille.\nAide à éviter que les grandes barres de santé ne deviennent trop volumineuses.",
		ru = "Сжимает полоски здоровья в зависимости от их размера.\nПомогает предотвратить чрезмерное увеличение больших полос здоровья.",
		["zh-cn"] = "根据大小压缩生命条。\n有助于防止巨大的生命条变得太大。",
	},
	logScale_description = {
		en = "Strength of log scaling.\nThe bigger the number, the stronger the compression, which means less size difference between small and large bars.",
		de = "Stärke der logarithmischen Skalierung.\nJe größer die Zahl, desto stärker die Kompression, was zu einem geringeren Größenunterschied zwischen kleinen und großen Balken führt.",
		fr = "Force de l'échelle logarithmique.\nPlus le nombre est grand, plus la compression est forte, ce qui signifie moins de différence de taille entre les petites et grandes barres.",
		ru = "Сила логарифмического масштабирования.\nЧем больше число, тем сильнее сжатие, что уменьшает разницу в размере между маленькими и большими полосками.",
		["zh-cn"] = "对数缩放强度。\n数值越大，压缩越强，小条和大条的大小差异越小。",
	},
	moveBuffs_description = {
		en = "Moves player buff icons out of the way of the health/toughness bar.",
		de = "Verschiebt die Buff-Symbole des Spielers aus dem Weg des Gesundheits-/Zähigkeitsbalkens.",
		fr = "Déplace les icônes de buffs du joueur pour qu'elles ne gênent pas la barre de santé/robustesse.",
		ru = "Перемещает иконки баффов игрока, чтобы они не заслоняли полоску здоровья/стойкости.",
		["zh-cn"] = "将玩家的增益图标移出生命值/韧性条的路径。",
	},
	moveCoherency_description = {
		en = "Moves teammate coherency icons out of the way of their health/toughness bars.",
		de = "Verschiebt die Kohärenz-Symbole der Teamkollegen aus dem Weg ihrer Gesundheits-/Zähigkeitsbalken.",
		fr = "Déplace les icônes de cohérence des coéquipiers pour qu'elles ne gênent pas leurs barres de santé/robustesse.",
		ru = "Перемещает иконки сплочённости союзников, чтобы они не заслоняли полоски их здоровья/стойкости.",
		["zh-cn"] = "将队友的连队图标移出生命值/韧性条的路径。",
	},

}
