-- weakspots_localization.lua
return {
mod_name = {
en = "{#color(93,101,50)}Weak Spots{#reset()}",
de = "{#color(93,101,50)}Schwachstellen{#reset()}",
fr = "{#color(93,101,50)}Points faibles{#reset()}",
ru = "{#color(93,101,50)}Слабые места{#reset()}",
["zh-cn"] = "{#color(93,101,50)}弱点{#reset()}",
es = "{#color(93,101,50)}Puntos débiles{#reset()}",
ja = "{#color(93,101,50)}弱点{#reset()}",
},
mod_description = {
en = "Shows weak spots on enemies",
de = "Zeigt Schwachstellen bei Gegnern an",
fr = "Affiche les points faibles des ennemis",
ru = "Показывает слабые места врагов",
["zh-cn"] = "显示敌人的弱点",
es = "Muestra los puntos débiles de los enemigos",
ja = "敵の弱点を表示します",
},
marker_range = {
en = "Maximum reticle range",
de = "Maximale Fadenkreuzreichweite",
fr = "Portée maximale du réticule",
ru = "Максимальная дальность прицельной метки",
["zh-cn"] = "最大准星范围",
es = "Alcance máximo de la retícula",
ja = "レティクルの最大距離",
},
marker_range_10 = {
en = "10 metres",
de = "10 Meter",
fr = "10 mètres",
ru = "10 метров",
["zh-cn"] = "10 米",
es = "10 metros",
ja = "10 メートル",
},
marker_range_20 = {
en = "20 metres",
de = "20 Meter",
fr = "20 mètres",
ru = "20 метров",
["zh-cn"] = "20 米",
es = "20 metros",
ja = "20 メートル",
},
marker_range_30 = {
en = "30 metres",
de = "30 Meter",
fr = "30 mètres",
ru = "30 метров",
["zh-cn"] = "30 米",
es = "30 metros",
ja = "30 メートル",
},
marker_range_40 = {
en = "40 metres",
de = "40 Meter",
fr = "40 mètres",
ru = "40 метров",
["zh-cn"] = "40 米",
es = "40 metros",
ja = "40 メートル",
},
boss_only = {
en = "Bosses only",
de = "Nur Bosse",
fr = "Boss uniquement",
ru = "Только боссы",
["zh-cn"] = "仅首领",
es = "Solo jefes",
ja = "ボスのみ",
},
boss_only_tooltip = {
en = "{#color(93,101,50)}Only bosses have weak spots marked. Overrides range distance option.{#reset()}",
de = "{#color(93,101,50)}Nur die Schwachstellen von Bossen werden markiert. Überschreibt die Reichweitenoption.{#reset()}",
fr = "{#color(93,101,50)}Seuls les points faibles des boss sont marqués. Remplace l’option de distance de portée.{#reset()}",
ru = "{#color(93,101,50)}Отмечаются слабые места только боссов. Переопределяет настройку дальности.{#reset()}",
["zh-cn"] = "{#color(93,101,50)}仅标记首领的弱点。此选项会覆盖距离范围设置。{#reset()}",
es = "{#color(93,101,50)}Solo se marcan los puntos débiles de los jefes. Anula la opción de distancia de alcance.{#reset()}",
ja = "{#color(93,101,50)}ボスの弱点のみを表示します。距離範囲の設定より優先されます。{#reset()}",
},
}