local mod = get_mod("SmoothTide")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "debug_enabled",
				type = "checkbox",
				default_value = false,
				text = mod:localize("debug_enabled"),
				tooltip = mod:localize("debug_enabled_description"),
			},
			{
				setting_id = "combat_echo",
				type = "checkbox",
				default_value = false,
				text = mod:localize("combat_echo"),
				tooltip = mod:localize("combat_echo_description"),
			},
			{
				setting_id = "combat_timeout",
				type = "numeric",
				range = {1, 10},
				default_value = 4,
				text = mod:localize("combat_timeout"),
				tooltip = mod:localize("combat_timeout_description"),
			},
			{
				setting_id = "combat_range",
				type = "numeric",
				range = {5, 30},
				default_value = 12,
				text = mod:localize("combat_range"),
				tooltip = mod:localize("combat_range_description"),
			},
			{
				setting_id = "suppress_hit_indicators",
				type = "checkbox",
				default_value = true,
				text = mod:localize("suppress_hit_indicators"),
				tooltip = mod:localize("suppress_hit_indicators_description"),
			},
			{
				setting_id = "suppress_damage_overlay",
				type = "checkbox",
				default_value = true,
				text = mod:localize("suppress_damage_overlay"),
				tooltip = mod:localize("suppress_damage_overlay_description"),
			},
			{
				setting_id = "particle_thinning",
				type = "checkbox",
				default_value = true,
				text = mod:localize("particle_thinning"),
				tooltip = mod:localize("particle_thinning_description"),
			},
			{
				setting_id = "particle_keep_chance",
				type = "numeric",
				range = {1, 100},
				default_value = 60,
				text = mod:localize("particle_keep_chance"),
				tooltip = mod:localize("particle_keep_chance_description"),
			},
			{
				setting_id = "enable_panic_mode",
				type = "checkbox",
				default_value = true,
				text = mod:localize("enable_panic_mode"),
				tooltip = mod:localize("enable_panic_mode_description"),
			},
			{
				setting_id = "panic_enemy_count",
				type = "numeric",
				range = {1, 40},
				default_value = 14,
				text = mod:localize("panic_enemy_count"),
				tooltip = mod:localize("panic_enemy_count_description"),
			},
			{
				setting_id = "panic_particle_keep_chance",
				type = "numeric",
				range = {1, 100},
				default_value = 35,
				text = mod:localize("panic_particle_keep_chance"),
				tooltip = mod:localize("panic_particle_keep_chance_description"),
			},
			{
				setting_id = "panic_hide_hit_indicators",
				type = "checkbox",
				default_value = true,
				text = mod:localize("panic_hide_hit_indicators"),
				tooltip = mod:localize("panic_hide_hit_indicators_description"),
			},
			{
				setting_id = "panic_hide_damage_overlay",
				type = "checkbox",
				default_value = true,
				text = mod:localize("panic_hide_damage_overlay"),
				tooltip = mod:localize("panic_hide_damage_overlay_description"),
			},
			{
				setting_id = "enable_ultra_panic_mode",
				type = "checkbox",
				default_value = true,
				text = mod:localize("enable_ultra_panic_mode"),
				tooltip = mod:localize("enable_ultra_panic_mode_description"),
			},
			{
				setting_id = "ultra_panic_enemy_count",
				type = "numeric",
				range = {1, 60},
				default_value = 24,
				text = mod:localize("ultra_panic_enemy_count"),
				tooltip = mod:localize("ultra_panic_enemy_count_description"),
			},
			{
				setting_id = "ultra_panic_particle_keep_chance",
				type = "numeric",
				range = {1, 100},
				default_value = 20,
				text = mod:localize("ultra_panic_particle_keep_chance"),
				tooltip = mod:localize("ultra_panic_particle_keep_chance_description"),
			},
			{
				setting_id = "ultra_panic_force_performance",
				type = "checkbox",
				default_value = true,
				text = mod:localize("ultra_panic_force_performance"),
				tooltip = mod:localize("ultra_panic_force_performance_description"),
			},
			{
				setting_id = "boss_safe_mode",
				type = "checkbox",
				default_value = true,
				text = mod:localize("boss_safe_mode"),
				tooltip = mod:localize("boss_safe_mode_description"),
			},
			{
				setting_id = "mode_hotkey_enabled",
				type = "checkbox",
				default_value = true,
				text = mod:localize("mode_hotkey_enabled"),
				tooltip = mod:localize("mode_hotkey_enabled_description"),
			},
			{
				setting_id = "default_mode",
				type = "dropdown",
				default_value = "cinematic",
				options = {
					{text = mod:localize("default_mode_cinematic"), value = "cinematic"},
					{text = mod:localize("default_mode_performance"), value = "performance"},
				},
				text = mod:localize("default_mode"),
				tooltip = mod:localize("default_mode_description"),
			},
			{
				setting_id = "force_cinematic_mode",
				type = "checkbox",
				default_value = false,
				text = mod:localize("force_cinematic_mode"),
				tooltip = mod:localize("force_cinematic_mode_description"),
			},
			{
				setting_id = "force_performance_mode",
				type = "checkbox",
				default_value = false,
				text = mod:localize("force_performance_mode"),
				tooltip = mod:localize("force_performance_mode_description"),
			},
			{
				setting_id = "enable_smart_mode",
				type = "checkbox",
				default_value = true,
				text = mod:localize("enable_smart_mode"),
				tooltip = mod:localize("enable_smart_mode_description"),
			},
			{
				setting_id = "smart_mode_fps_threshold",
				type = "numeric",
				range = {30, 144},
				default_value = 72,
				text = mod:localize("smart_mode_fps_threshold"),
				tooltip = mod:localize("smart_mode_fps_threshold_description"),
			},
			{
				setting_id = "smart_mode_restore_fps",
				type = "numeric",
				range = {30, 165},
				default_value = 90,
				text = mod:localize("smart_mode_restore_fps"),
				tooltip = mod:localize("smart_mode_restore_fps_description"),
			},
			{
				setting_id = "auto_cinematic_when_calm",
				type = "checkbox",
				default_value = true,
				text = mod:localize("auto_cinematic_when_calm"),
				tooltip = mod:localize("auto_cinematic_when_calm_description"),
			},
			{
				setting_id = "calm_enemy_threshold",
				type = "numeric",
				range = {0, 10},
				default_value = 0,
				text = mod:localize("calm_enemy_threshold"),
				tooltip = mod:localize("calm_enemy_threshold_description"),
			},
			{
				setting_id = "calm_restore_delay",
				type = "numeric",
				range = {1, 10},
				decimals_number = 1,
				default_value = 2.5,
				text = mod:localize("calm_restore_delay"),
				tooltip = mod:localize("calm_restore_delay_description"),
			},
			{
				setting_id = "auto_performance_in_hordes",
				type = "checkbox",
				default_value = true,
				text = mod:localize("auto_performance_in_hordes"),
				tooltip = mod:localize("auto_performance_in_hordes_description"),
			},
			{
				setting_id = "horde_enemy_threshold",
				type = "numeric",
				range = {5, 40},
				default_value = 10,
				text = mod:localize("horde_enemy_threshold"),
				tooltip = mod:localize("horde_enemy_threshold_description"),
			},
			{
				setting_id = "enable_dynamic_resolution",
				type = "checkbox",
				default_value = true,
				text = mod:localize("enable_dynamic_resolution"),
				tooltip = mod:localize("enable_dynamic_resolution_description"),
			},
			{
				setting_id = "dynamic_resolution_min_scale",
				type = "numeric",
				range = {50, 100},
				default_value = 70,
				text = mod:localize("dynamic_resolution_min_scale"),
				tooltip = mod:localize("dynamic_resolution_min_scale_description"),
			},
			{
				setting_id = "dynamic_resolution_max_scale",
				type = "numeric",
				range = {50, 100},
				default_value = 100,
				text = mod:localize("dynamic_resolution_max_scale"),
				tooltip = mod:localize("dynamic_resolution_max_scale_description"),
			},
			{
				setting_id = "dynamic_resolution_fps_floor",
				type = "numeric",
				range = {30, 120},
				default_value = 55,
				text = mod:localize("dynamic_resolution_fps_floor"),
				tooltip = mod:localize("dynamic_resolution_fps_floor_description"),
			},
			{
				setting_id = "dynamic_resolution_fps_target",
				type = "numeric",
				range = {30, 144},
				default_value = 72,
				text = mod:localize("dynamic_resolution_fps_target"),
				tooltip = mod:localize("dynamic_resolution_fps_target_description"),
			},
			{
				setting_id = "toggle_smoothtide_mode_hotkey",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "toggle_smoothtide_mode_hotkey",
				text = mod:localize("toggle_smoothtide_mode_hotkey"),
				tooltip = mod:localize("toggle_smoothtide_mode_hotkey_description"),
			},
			{
				setting_id = "toggle_performance_mode_hotkey",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "toggle_performance_mode_hotkey",
				text = mod:localize("toggle_performance_mode_hotkey"),
				tooltip = mod:localize("toggle_performance_mode_hotkey_description"),
			},
			{
				setting_id = "toggle_cinematic_mode_hotkey",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "toggle_cinematic_mode_hotkey",
				text = mod:localize("toggle_cinematic_mode_hotkey"),
				tooltip = mod:localize("toggle_cinematic_mode_hotkey_description"),
			},
		},
	},
}