local history_back = {en = "Back to scoreboard history", ["zh-cn"] = "返回计分板历史列表"}
get_mod("RealmScoreboardExtend"):add_global_localize_strings({sr_history_back = history_back})

return {
    mod_name = {en = "RealmScoreboardExtend", ["zh-cn"] = "RealmScoreboardExtend"},
    mod_description = {en = "Extend mission, end-screen and historical scoreboards to 1–12 players per page, with equipment rows and automatic scaling. Requires scoreboard. Disable ScoreboardRoster and RealmsScoreboard8.", ["zh-cn"] = "将局内、结算和历史计分板扩展至每页 1–12 人，支持装备行及自动缩放。依赖 scoreboard；请停用 ScoreboardRoster 和 RealmsScoreboard8。"},
    equipment_perk_limit = {en="Visible perks per weapon", ["zh-cn"]="每把武器可见专长条数"},
    equipment_blessing_limit = {en="Visible blessings per weapon", ["zh-cn"]="每把武器可见祝福条数"},
    equipment_melee = {en="Melee weapon", ["zh-cn"]="近战武器"},
    equipment_ranged = {en="Ranged weapon", ["zh-cn"]="远程武器"},
    equipment_perks = {en="Perks", ["zh-cn"]="武器专长"},
    equipment_traits = {en="Blessings", ["zh-cn"]="武器祝福"},
    equipment_feats = {en="Ability / Blitz / Aura / Keystone", ["zh-cn"]="技能／闪击／光环／基石"},
    equipment_missing = {en="Not recorded", ["zh-cn"]="未记录"},
    equipment_more = {en="%d more", ["zh-cn"]="另有 %d 项"},
    sr_history_back = history_back,
    debug_logging = {en = "Diagnostic logging (state changes and paging)", ["zh-cn"] = "诊断日志（界面切换、布局与翻页）"},
    max_players = {en = "In-mission players per page", ["zh-cn"] = "对局中每页最大显示人数"},
    end_players = {en = "End screen players per page", ["zh-cn"] = "结算每页最大显示人数"},
    history_players = {en = "History players per page", ["zh-cn"] = "历史每页最大显示人数"},
    width_percent = {en = "Panel width (%%) — capped to available screen", ["zh-cn"] = "面板宽度百分比（不超过屏幕可用宽度）"},
    font_percent = {en = "Font size (%%)", ["zh-cn"] = "字体大小百分比"},
    previous_page = {en = "Previous player page", ["zh-cn"] = "上一页玩家"},
    next_page = {en = "Next player page", ["zh-cn"] = "下一页玩家"},
    player_bot = {en = "BOT", ["zh-cn"] = "机器人"},
    player_offline = {en = "Offline", ["zh-cn"] = "离线"},
    page_hint = {en = "%d / %d   [%s / %s]", ["zh-cn"] = "第 %d / %d 页   [%s / %s]"},
    key_page_up = {en = "PgUp", ["zh-cn"] = "上翻页"},
    key_page_down = {en = "PgDn", ["zh-cn"] = "下翻页"},
    key_unbound = {en = "Unbound", ["zh-cn"] = "未绑定"},
    error_previous_mod = {en = "RealmScoreboardExtend: remove ScoreboardRoster from mod_load_order.txt and restart the game.", ["zh-cn"] = "RealmScoreboardExtend：请从 mod_load_order.txt 移除 ScoreboardRoster，然后重启游戏。"},
    error_legacy_mod = {en = "RealmScoreboardExtend: disable RealmsScoreboard8 and restart the game.", ["zh-cn"] = "RealmScoreboardExtend：请停用 RealmsScoreboard8，然后重启游戏。"},
    error_missing_scoreboard = {en = "RealmScoreboardExtend: scoreboard is required. Install and load scoreboard before this mod.", ["zh-cn"] = "RealmScoreboardExtend：缺少 scoreboard。请安装并将 scoreboard 放在本 Mod 之前加载。"},
    error_scoreboard_api = {en = "RealmScoreboardExtend: this scoreboard version is missing the required row interface. Check the installed scoreboard version.", ["zh-cn"] = "RealmScoreboardExtend：当前 scoreboard 缺少所需的统计行接口，请检查安装版本。"},
    status_yes = {en = "Yes", ["zh-cn"] = "是"},
    status_no = {en = "No", ["zh-cn"] = "否"},
    view_hud = {en = "In-mission scoreboard", ["zh-cn"] = "局内计分板"},
    view_end = {en = "End-screen scoreboard", ["zh-cn"] = "结算计分板"},
    view_history = {en = "Historical scoreboard", ["zh-cn"] = "历史计分板"},
    status_summary = {en = "RealmScoreboardExtend %s: retained players=%d, current players=%d, view open=%s, layout ready=%s", ["zh-cn"] = "RealmScoreboardExtend %s：保留玩家=%d，当前玩家=%d，视图已打开=%s，布局已就绪=%s"},
    status_layout = {en = "%s: page=%d/%d, displayed=%d/%d, columns=%d, panel width=%.0f, label width=%.0f, scale=%.3f", ["zh-cn"] = "%s：页码=%d/%d，显示人数=%d/%d，列数=%d，面板宽度=%.0f，标题宽度=%.0f，缩放=%.3f"},
    command_status = {en = "Show RealmScoreboardExtend diagnostics", ["zh-cn"] = "显示 RealmScoreboardExtend 诊断信息"},
    command_next = {en = "Show the next scoreboard player page", ["zh-cn"] = "显示计分板的下一页玩家"},
    command_previous = {en = "Show the previous scoreboard player page", ["zh-cn"] = "显示计分板的上一页玩家"},
    command_alias = {en = "Alias for %s", ["zh-cn"] = "%s 的兼容别名"},
}
