return {
    end_board_preference = {en = "Mission-end board", de = "Anzeige am Missionsende"},
    end_board_preference_description = {en = "Choose which board is displayed at mission end. Improve Yourself uses Scores as its host, preserving Scores data finalization, reward-screen movement, and end-view lifecycle.", de = "Wähle, welche Anzeige am Missionsende dargestellt wird. Improve Yourself nutzt Scores als Host und erhält dessen Datenfinalisierung, Bewegung neben der Belohnungsanzeige und Endansichts-Lebenszyklus."},
    end_board_improve_yourself = {en = "Improve Yourself victory board", de = "Improve-Yourself-Siegesanzeige"},
    end_board_regular_scoreboard = {en = "Regular Scores board", de = "Reguläres Scores-Board"},
    tactical_overlay_preference = {en = "Tactical Overlay", de = "Taktisches Overlay"},
    tactical_overlay_preference_description = {en = "Choose whether the Tactical Overlay shows Improve Yourself performance bars or Scores' numerical rows.", de = "Wähle, ob das taktische Overlay die Leistungsbalken von Improve Yourself oder die Zahlenreihen von Scores anzeigt."},
    tactical_overlay_improve_yourself = {en = "Improve Yourself tactical overlay", de = "Improve-Yourself-Overlay"},
    tactical_overlay_scores = {en = "Scores tactical overlay", de = "Scores-Overlay"},
    history_start_view = {en = "Scores History", de = "Scores-Verlauf"},
    history_start_view_description = {en = "Choose whether a selected match initially shows Scores' numbers or Improve Yourself's bars. You can still toggle between both views inside History.", de = "Wähle, ob ein ausgewähltes Spiel zuerst die Zahlen von Scores oder die Balken von Improve Yourself zeigt. Im Verlauf kann weiterhin zwischen beiden Ansichten gewechselt werden."},
    history_start_view_numbers = {en = "Start with numbers", de = "Mit Zahlen starten"},
    history_start_view_bars = {en = "Start with bars", de = "Mit Balken starten"},
    color_scheme = {en = "Color scheme", de = "Farbschema"},
    color_scheme_description = {en = "Choose whether your result colors are based on your configured goals or on your position within the team. Other players remain neutral. This changes colors only; goals, praise, role evaluation, and progress scoring remain goal-based.", de = "Wähle, ob deine Ergebnisfarben auf deinen eingestellten Zielen oder auf deiner Platzierung im Team basieren. Andere Spieler bleiben neutral. Dies ändert nur die Farben; Ziele, Lob, Rollenbewertung und Fortschrittswertung bleiben zielbasiert."},
    color_scheme_goal_oriented = {en = "Goal Oriented", de = "Zielorientiert"},
    color_scheme_team_comparison = {en = "Team Comparison Oriented", de = "Teamvergleich"},
    mod_title = {en = "Improve Yourself", de = "Improve Yourself"},
    mod_description = {en = "Visualizes Scores data as goal-oriented Tactical, Victory, and selected-match boards. Scores remains the sole owner of collection and history.", de = "Visualisiert Scores-Daten als zielorientierte Taktik-, Sieges- und Spielansichten. Scores bleibt allein für Datenerfassung und Verlauf zuständig."},
    settings_general = {en = "General", de = "Allgemein"},
    group_general = {en = "General", de = "Allgemein"},
    group_developer = {en = "Developer Options", de = "Entwickleroptionen"},
    auto_damage_diagnostics = {en = "Automatic damage diagnostic per mission", de = "Automatische Schadensdiagnose pro Mission"},
    auto_damage_diagnostics_description = {en = "When enabled, writes one timestamped full damage diagnostic file for every mission, including failed or aborted missions. The file is saved in Scores' writable history folder.", de = "Wenn aktiviert, wird für jede Mission eine vollständige Schadensdiagnose als Datei mit Zeitstempel gespeichert, auch bei fehlgeschlagenen oder abgebrochenen Missionen. Die Datei wird im beschreibbaren Verlaufsordner von Scores gespeichert."},
    group_role_generalist = {en = "Generalist", de = "Allrounder"},
    group_role_frontline = {en = "Melee Anchor", de = "Nahkampf-Anker"},
    group_role_horde_control = {en = "Horde Control", de = "Hordenkontrolle"},
    group_role_ranged_specialist = {en = "Ranged Specialist", de = "Fernkampf-Spezialist"},
    group_role_elite_boss = {en = "Elite & Boss", de = "Elite & Boss"},
    group_role_support_control = {en = "Support & Control", de = "Support & Kontrolle"},
    default_role = {en = "Default role", de = "Standardrolle"},
    default_role_description = {en = "The role selected automatically whenever the dashboard opens. You can still switch roles inside the dashboard.", de = "Die Rolle, die beim Öffnen der Übersicht automatisch ausgewählt wird. In der Übersicht kann weiterhin gewechselt werden."},
    goal_setting_description = {en = "Goals are your target share of the squad total. 25%% means equal contribution across four players; 100%% means only you contributed to that metric. Values are prefilled with the built-in recommendation.", de = "Ziele geben deinen angestrebten Anteil an der Teamgesamtleistung an. 25 %% entsprechen einem gleichen Anteil bei vier Spielern; 100 %% bedeuten, dass nur du zu diesem Wert beigetragen hast. Die Werte sind mit der integrierten Empfehlung vorbelegt."},
    role_generalist = {en = "Generalist", de = "Allrounder"},
    role_frontline = {en = "Melee Anchor", de = "Nahkampf-Anker"},
    role_horde_control = {en = "Horde Control", de = "Hordenkontrolle"},
    role_ranged_specialist = {en = "Ranged Specialist", de = "Fernkampf-Spezialist"},
    role_elite_boss = {en = "Elite & Boss Killer", de = "Elite- & Boss-Killer"},
    role_support_control = {en = "Support & Control", de = "Support & Kontrolle"},
    settings_section_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_generalist_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_generalist_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_generalist_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_frontline_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_frontline_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_frontline_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_horde_control_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_horde_control_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_horde_control_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_ranged_specialist_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_ranged_specialist_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_ranged_specialist_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_elite_boss_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_elite_boss_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_elite_boss_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_support_control_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_support_control_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_support_control_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    settings_section_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    settings_section_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    goal_generalist_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_frontline_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_horde_control_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_ranged_specialist_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_elite_boss_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_support_control_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_generalist_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_frontline_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_horde_control_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_ranged_specialist_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_elite_boss_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_support_control_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_generalist_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_frontline_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_horde_control_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_ranged_specialist_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_elite_boss_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_support_control_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_generalist_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_frontline_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_horde_control_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_ranged_specialist_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_elite_boss_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_support_control_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_generalist_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_frontline_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_horde_control_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_ranged_specialist_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_elite_boss_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_support_control_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_generalist_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_frontline_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_horde_control_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_ranged_specialist_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_elite_boss_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_support_control_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_generalist_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_frontline_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_horde_control_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_ranged_specialist_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_elite_boss_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_support_control_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_generalist_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_frontline_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_horde_control_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_ranged_specialist_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_elite_boss_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_support_control_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_generalist_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_frontline_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_horde_control_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_ranged_specialist_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_elite_boss_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_support_control_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_generalist_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_frontline_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_horde_control_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_ranged_specialist_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_elite_boss_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_support_control_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_generalist_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_frontline_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_horde_control_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_ranged_specialist_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_elite_boss_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_support_control_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_generalist_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_frontline_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_horde_control_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_ranged_specialist_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_elite_boss_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_support_control_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_generalist_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_frontline_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_horde_control_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_ranged_specialist_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_elite_boss_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_support_control_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_generalist_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_frontline_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_horde_control_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_ranged_specialist_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_elite_boss_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_support_control_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_generalist_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_frontline_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_horde_control_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_ranged_specialist_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_elite_boss_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_support_control_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_generalist_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_frontline_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_horde_control_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_ranged_specialist_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_elite_boss_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_support_control_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    loc_improve_yourself_show_bars = {en = "Show bars", de = "Balken anzeigen"},
    loc_improve_yourself_show_numbers = {en = "Show numbers", de = "Zahlen anzeigen"},
}
