local localization = {
    end_board_preference = {en = "Mission-end board", de = "Anzeige am Missionsende"},
    end_board_preference_description = {en = "Choose which board is displayed at mission end. Improve Yourself uses Scores as its host, preserving Scores data finalization, reward-screen movement, and end-view lifecycle.", de = "Wähle, welche Anzeige am Missionsende dargestellt wird. Improve Yourself nutzt Scores als Host und erhält dessen Datenfinalisierung, Bewegung neben der Belohnungsanzeige und Endansichts-Lebenszyklus."},
    end_board_improve_yourself = {en = "Improve Yourself victory board", de = "Improve-Yourself-Siegesanzeige"},
    end_board_regular_scoreboard = {en = "Regular Scores board", de = "Reguläres Scores-Board"},
    tactical_overlay_preference = {en = "Tactical Overlay", de = "Taktisches Overlay"},
    tactical_overlay_preference_description = {en = "Choose whether the Tactical Overlay shows Improve Yourself performance bars or Scores' numerical rows.", de = "Wähle, ob das taktische Overlay die Leistungsbalken von Improve Yourself oder die Zahlenreihen von Scores anzeigt."},
    tactical_overlay_improve_yourself = {en = "Improve Yourself tactical overlay", de = "Improve-Yourself-Overlay"},
    tactical_overlay_scores = {en = "Scores tactical overlay", de = "Scores-Overlay"},
    history_start_view = {en = "Scores History", de = "Scores-Verlauf"},
    history_start_view_description = {en = "Choose whether a selected match initially shows Scores' numbers or Improve Yourself's bars. You can still toggle between both views inside History.", de = "Wähle, ob ein ausgewähltes Spiel zuerst die Zahlen von Scores oder die Balken von Improve Yourself zeigt. Im Verlauf kann weiterhin zwischen beiden Ansichten gewechselt werden."},
    history_start_view_numbers = {en = "Start with numbers", de = "Mit Zahlen starten"},
    history_start_view_bars = {en = "Start with bars", de = "Mit Balken starten"},
    color_scheme = {en = "Color scheme", de = "Farbschema"},
    color_scheme_description = {en = "Choose whether your result colors are based on your configured goals or on your position within the team. Other players remain neutral. This changes colors only; goals, praise, role evaluation, and progress scoring remain goal-based.", de = "Wähle, ob deine Ergebnisfarben auf deinen eingestellten Zielen oder auf deiner Platzierung im Team basieren. Andere Spieler bleiben neutral. Dies ändert nur die Farben; Ziele, Lob, Rollenbewertung und Fortschrittswertung bleiben zielbasiert."},
    color_scheme_goal_oriented = {en = "Goal Oriented", de = "Zielorientiert"},
    color_scheme_team_comparison = {en = "Team Comparison Oriented", de = "Teamvergleich"},
    mod_title = {en = "Improve Yourself", de = "Improve Yourself"},
    mod_description = {en = "Visualizes Scores data as goal-oriented Tactical, Victory, and selected-match boards. Scores remains the sole owner of collection and history.", de = "Visualisiert Scores-Daten als zielorientierte Taktik-, Sieges- und Spielansichten. Scores bleibt allein für Datenerfassung und Verlauf zuständig."},
    settings_general = {en = "General", de = "Allgemein"},
    group_general = {en = "General", de = "Allgemein"},
    group_developer = {en = "Developer Options", de = "Entwickleroptionen"},
    auto_damage_diagnostics = {en = "Automatic damage diagnostic per mission", de = "Automatische Schadensdiagnose pro Mission"},
    auto_damage_diagnostics_description = {en = "When enabled, writes one timestamped full damage diagnostic file for every mission, including failed or aborted missions. The file is saved in Scores' writable history folder.", de = "Wenn aktiviert, wird für jede Mission eine vollständige Schadensdiagnose als Datei mit Zeitstempel gespeichert, auch bei fehlgeschlagenen oder abgebrochenen Missionen. Die Datei wird im beschreibbaren Verlaufsordner von Scores gespeichert."},
    group_role_generalist = {en = "Generalist", de = "Allrounder"},
    group_role_frontline = {en = "Melee Anchor", de = "Nahkampf-Anker"},
    group_role_horde_control = {en = "Horde Control", de = "Hordenkontrolle"},
    group_role_ranged_specialist = {en = "Ranged Specialist", de = "Fernkampf-Spezialist"},
    group_role_elite_boss = {en = "Elite & Boss", de = "Elite & Boss"},
    group_role_support_control = {en = "Support & Control", de = "Support & Kontrolle"},
    default_role = {en = "Default role", de = "Standardrolle"},
    default_role_description = {en = "The role selected automatically whenever the dashboard opens. You can still switch roles inside the dashboard.", de = "Die Rolle, die beim Öffnen der Übersicht automatisch ausgewählt wird. In der Übersicht kann weiterhin gewechselt werden."},
    goal_setting_description = {en = "Goals are your target share of the squad total. 25%% means equal contribution across four players; 100%% means only you contributed to that metric. Values are prefilled with the built-in recommendation.", de = "Ziele geben deinen angestrebten Anteil an der Teamgesamtleistung an. 25 %% entsprechen einem gleichen Anteil bei vier Spielern; 100 %% bedeuten, dass nur du zu diesem Wert beigetragen hast. Die Werte sind mit der integrierten Empfehlung vorbelegt."},
    role_generalist = {en = "Generalist", de = "Allrounder"},
    role_frontline = {en = "Melee Anchor", de = "Nahkampf-Anker"},
    role_horde_control = {en = "Horde Control", de = "Hordenkontrolle"},
    role_ranged_specialist = {en = "Ranged Specialist", de = "Fernkampf-Spezialist"},
    role_elite_boss = {en = "Elite & Boss Killer", de = "Elite- & Boss-Killer"},
    role_support_control = {en = "Support & Control", de = "Support & Kontrolle"},
    settings_section_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_generalist_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_generalist_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_generalist_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_frontline_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_frontline_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_frontline_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_horde_control_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_horde_control_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_horde_control_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_ranged_specialist_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_ranged_specialist_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_ranged_specialist_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_elite_boss_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_elite_boss_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_elite_boss_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    section_support_control_defense = {en = "Defense - Lower to improve yourself", de = "Verteidigung – Weniger ist besser"},
    section_support_control_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    section_support_control_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    settings_section_offense = {en = "Offense - Raise to improve yourself", de = "Offensive – Mehr ist besser"},
    settings_section_team = {en = "Team Contribution - Raise to improve yourself", de = "Teambeitrag – Mehr ist besser"},
    goal_generalist_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_frontline_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_horde_control_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_ranged_specialist_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_elite_boss_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_support_control_damage_taken = {en = "Damage taken goal", de = "Ziel: erlittener Schaden"},
    goal_generalist_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_frontline_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_horde_control_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_ranged_specialist_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_elite_boss_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_support_control_times_downed = {en = "Times downed goal", de = "Ziel: Niederschläge"},
    goal_generalist_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_frontline_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_horde_control_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_ranged_specialist_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_elite_boss_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_support_control_times_disabled = {en = "Times disabled goal", de = "Ziel: Ausschaltungen"},
    goal_generalist_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_frontline_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_horde_control_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_ranged_specialist_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_elite_boss_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_support_control_deaths = {en = "Deaths goal", de = "Ziel: Tode"},
    goal_generalist_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_frontline_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_horde_control_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_ranged_specialist_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_elite_boss_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_support_control_damage_dealt = {en = "Total damage goal", de = "Ziel: Gesamtschaden"},
    goal_generalist_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_frontline_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_horde_control_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_ranged_specialist_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_elite_boss_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_support_control_weakspot_hits = {en = "Weakspot hits goal", de = "Ziel: Schwachstellentreffer"},
    goal_generalist_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_frontline_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_horde_control_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_ranged_specialist_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_elite_boss_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_support_control_melee_kills = {en = "Melee kills goal", de = "Ziel: Nahkampfkills"},
    goal_generalist_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_frontline_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_horde_control_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_ranged_specialist_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_elite_boss_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_support_control_ranged_kills = {en = "Ranged kills goal", de = "Ziel: Fernkampfkills"},
    goal_generalist_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_frontline_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_horde_control_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_ranged_specialist_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_elite_boss_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_support_control_lesser_enemies = {en = "Swarmers killed goal", de = "Ziel: Schwarmgegner"},
    goal_generalist_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_frontline_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_horde_control_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_ranged_specialist_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_elite_boss_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_support_control_melee_ranged_threats = {en = "Elites killed goal", de = "Ziel: Elitegegner"},
    goal_generalist_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_frontline_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_horde_control_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_ranged_specialist_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_elite_boss_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_support_control_special_threats = {en = "Specials killed goal", de = "Ziel: Spezialisten"},
    goal_generalist_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_frontline_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_horde_control_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_ranged_specialist_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_elite_boss_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_support_control_boss_damage_dealt = {en = "Boss damage goal", de = "Ziel: Bossschaden"},
    goal_generalist_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_frontline_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_horde_control_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_ranged_specialist_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_elite_boss_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_support_control_coherency_efficiency = {en = "Coherency goal", de = "Ziel: Kohärenz"},
    goal_generalist_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_frontline_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_horde_control_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_ranged_specialist_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_elite_boss_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_support_control_revived_operative = {en = "Revives goal", de = "Ziel: Wiederbelebungen"},
    goal_generalist_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_frontline_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_horde_control_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_ranged_specialist_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_elite_boss_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_support_control_team_saves = {en = "Saves goal", de = "Ziel: Rettungen"},
    goal_generalist_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_frontline_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_horde_control_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_ranged_specialist_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_elite_boss_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    goal_support_control_ammo_score = {en = "Ammo score goal", de = "Ziel: Munitionswert"},
    loc_improve_yourself_show_bars = {en = "Show bars", de = "Balken anzeigen"},
    loc_improve_yourself_show_numbers = {en = "Show numbers", de = "Zahlen anzeigen"},

    -- Shared visual-board strings. Keeping these here prevents Tactical and
    -- Victory/History from drifting into separate translation sets.
    iy_title = {en = "IMPROVE YOURSELF!", de = "VERBESSERE DICH!"},
    iy_victory = {en = "VICTORY", de = "SIEG"},
    iy_lost = {en = "LOST", de = "VERLOREN"},
    iy_current_performance = {en = "CURRENT PERFORMANCE", de = "AKTUELLE LEISTUNG"},
    iy_live_mission_progress = {en = "LIVE MISSION PROGRESS", de = "LIVE-MISSIONSFORTSCHRITT"},
    iy_current_mission = {en = "CURRENT MISSION", de = "AKTUELLE MISSION"},
    iy_havoc_rank = {en = "Havoc %d", de = "Verderben %d"},
    iy_difficulty_1 = {en = "Sedition", de = "Aufruhr"},
    iy_difficulty_2 = {en = "Uprising", de = "Aufstand"},
    iy_difficulty_3 = {en = "Malice", de = "Bosheit"},
    iy_difficulty_4 = {en = "Heresy", de = "Häresie"},
    iy_difficulty_5 = {en = "Damnation", de = "Verdammnis"},
    iy_waiting_for_scores = {en = "WAITING FOR LIVE SCORES DATA", de = "WARTE AUF LIVE-DATEN VON SCORES"},
    iy_live_footer = {en = "Live values update while the tactical overlay is open.", de = "Live-Werte werden aktualisiert, solange das taktische Overlay geöffnet ist."},
    iy_unknown = {en = "Unknown", de = "Unbekannt"},
    iy_operative = {en = "Operative", de = "Operative"},
    iy_no_data = {en = "NO DATA", de = "KEINE DATEN"},

    iy_section_defense = {en = "DEFENSE", de = "VERTEIDIGUNG"},
    iy_section_offense = {en = "OFFENSE", de = "OFFENSIVE"},
    iy_section_teamplay = {en = "TEAMPLAY", de = "TEAMPLAY"},
    iy_combat_quality = {en = "COMBAT QUALITY", de = "KAMPFQUALITÄT"},
    iy_goal = {en = "GOAL", de = "ZIEL"},
    iy_best = {en = "BEST", de = "BESTE"},
    iy_worst = {en = "WORST", de = "SCHLECHTESTE"},
    iy_outstanding = {en = "OUTSTANDING!", de = "HERAUSRAGEND!"},
    iy_impressive = {en = "IMPRESSIVE!", de = "BEEINDRUCKEND!"},
    iy_goals_count = {en = "%d/%d goals", de = "%d/%d Ziele"},
    iy_no_goals = {en = "No goals", de = "Keine Ziele"},
    iy_met_count = {en = "%d met", de = "%d erreicht"},
    iy_close_count = {en = "%d close", de = "%d knapp"},
    iy_missed_count = {en = "%d missed", de = "%d verfehlt"},
    iy_best_of_match = {en = "Best of match: %s", de = "Beste im Spiel: %s"},
    iy_improve_metrics = {en = "Improve: %s", de = "Verbessern: %s"},
    iy_all_goals_close = {en = "All goals within reach", de = "Alle Ziele in Reichweite"},

    iy_metric_damage_taken = {en = "Damage taken", de = "Erlittener Schaden"},
    iy_metric_times_downed = {en = "Times downed", de = "Niedergänge"},
    iy_metric_times_disabled = {en = "Times disabled", de = "Ausschaltungen"},
    iy_metric_deaths = {en = "Deaths", de = "Tode"},
    iy_metric_damage_total = {en = "Damage total", de = "Gesamtschaden"},
    iy_metric_weakspot_hits = {en = "Weakspot hits", de = "Schwachstellentreffer"},
    iy_metric_weakspot_short = {en = "Weakspot", de = "Schwachstelle"},
    iy_metric_melee_kills = {en = "Melee kills", de = "Nahkampfkills"},
    iy_metric_melee_short = {en = "Melee", de = "Nahkampf"},
    iy_metric_ranged_kills = {en = "Ranged kills", de = "Fernkampfkills"},
    iy_metric_ranged_short = {en = "Ranged", de = "Fernkampf"},
    iy_metric_swarmers = {en = "Swarmers", de = "Schwärmer"},
    iy_metric_elites = {en = "Elites", de = "Eliten"},
    iy_metric_specials = {en = "Specials", de = "Spezialisten"},
    iy_metric_boss = {en = "Boss", de = "Boss"},
    iy_metric_coherency = {en = "Coherency", de = "Kohärenz"},
    iy_metric_saves = {en = "Saves", de = "Rettungen"},
    iy_metric_revives = {en = "Revives", de = "Wiederbelebungen"},
    iy_metric_ammo = {en = "Ammo", de = "Munition"},
    iy_metric_healthstations = {en = "Healthstations", de = "Medicae-Stationen"},
    iy_metric_objectives = {en = "Objectives", de = "Ziele"},
    iy_metric_currency = {en = "Currency", de = "Ressourcen"},
    iy_metric_weakspot_percent = {en = "Weakspot hit %%", de = "Schwachstellentreffer %%"},
    iy_metric_critical_percent = {en = "Critical hits %%", de = "Kritische Treffer %%"},
    iy_metric_accuracy = {en = "Ranged accuracy", de = "Fernkampfpräzision"},
    iy_damage_area = {en = "Area of Effect", de = "Flächenschaden"},
    iy_damage_melee = {en = "Melee Damage", de = "Nahkampfschaden"},
    iy_damage_ranged = {en = "Ranged Damage", de = "Fernkampfschaden"},
    iy_damage_other = {en = "Other Damage", de = "Anderer Schaden"},
    iy_attacks_blocked = {en = "Attacks Blocked", de = "Geblockte Angriffe"},
    iy_counter_downed = {en = "Downed", de = "Niedergänge"},
    iy_counter_disabled = {en = "Disabled", de = "Ausschaltungen"},
    iy_counter_deaths = {en = "Deaths", de = "Tode"},

    iy_source_falling = {en = "Falling", de = "Sturz"},
    iy_source_corruption = {en = "Corruption", de = "Verderbnis"},
    iy_source_warp = {en = "Warp", de = "Warp"},
    iy_source_overheat = {en = "Overheat", de = "Überhitzung"},
    iy_source_netted = {en = "Netted", de = "Netz"},
    iy_source_untracked = {en = "Untracked", de = "Nicht erfasst"},
    iy_source_self_damage = {en = "Self Damage", de = "Eigenschaden"},
    iy_source_armored_hound = {en = "Armored Hound", de = "Gepanzerter Hund"},
    iy_source_beast_of_nurgle = {en = "Beast of Nurgle", de = "Bestie des Nurgle"},
    iy_source_hound = {en = "Hound", de = "Poxhund"},
    iy_source_mutated_poxwalker = {en = "Mutated Poxwalker", de = "Mutierter Poxwalker"},
    iy_source_groaner = {en = "Groaner", de = "Stöhner"},
    iy_source_bulwark = {en = "Bulwark", de = "Bollwerk"},
    iy_source_crusher = {en = "Crusher", de = "Crusher"},
    iy_source_reaper = {en = "Reaper", de = "Reaper"},
    iy_source_houndmaster = {en = "Houndmaster", de = "Hundemeister"},
    iy_source_plague_ogryn = {en = "Plague Ogryn", de = "Seuchen-Ogryn"},
    iy_source_poxwalker = {en = "Poxwalker", de = "Poxwalker"},
    iy_source_poxburster = {en = "Poxburster", de = "Poxburster"},
    iy_source_chaos_spawn = {en = "Chaos Spawn", de = "Chaosbrut"},
    iy_source_shotgunner = {en = "Shotgunner", de = "Schrotflintenschütze"},
    iy_source_rager = {en = "Rager", de = "Rager"},
    iy_source_captain = {en = "Captain", de = "Captain"},
    iy_source_flamer = {en = "Flamer", de = "Flamer"},
    iy_source_bomber = {en = "Bomber", de = "Bomber"},
    iy_source_gunner = {en = "Gunner", de = "Gunner"},
    iy_source_bruiser = {en = "Bruiser", de = "Bruiser"},
    iy_source_mutant = {en = "Mutant", de = "Mutant"},
    iy_source_mauler = {en = "Mauler", de = "Mauler"},
    iy_source_shooter = {en = "Shooter", de = "Schütze"},
    iy_source_sniper = {en = "Sniper", de = "Sniper"},
    iy_source_pox_gas = {en = "Pox Gas", de = "Poxgas"},
    iy_source_barrel_fire = {en = "Barrel Fire", de = "Fassfeuer"},
    iy_source_barrel_explosion = {en = "Barrel Explosion", de = "Fassexplosion"},
    iy_source_flamer_fire = {en = "Flamer Fire", de = "Flamer-Feuer"},
    iy_source_beast_slime = {en = "Beast Slime", de = "Bestienschleim"},
    iy_source_ground_slam = {en = "Ground Slam", de = "Bodenschlag"},
    iy_source_explosion = {en = "Explosion", de = "Explosion"},
    iy_source_area_effect = {en = "Area Effect", de = "Flächeneffekt"},
    iy_source_ranged_attack = {en = "Ranged Attack", de = "Fernkampfangriff"},
    iy_source_melee_attack = {en = "Melee Attack", de = "Nahkampfangriff"},
    iy_source_other = {en = "Other", de = "Sonstiges"},
}

-- Simplified Chinese follows Scores' own `zh-cn` locale and terminology where
-- the same metrics exist. English remains the fallback for any future key that
-- has not yet received a translation.
local zh_cn = {
    end_board_preference = "任务结算面板",
    end_board_preference_description = "选择任务结束时显示的面板。Improve Yourself 以 Scores 为宿主，并保留 Scores 的数据结算、奖励界面移动和结算界面生命周期。",
    end_board_improve_yourself = "Improve Yourself 胜利面板",
    end_board_regular_scoreboard = "常规 Scores 面板",
    tactical_overlay_preference = "战术面板",
    tactical_overlay_preference_description = "选择战术面板显示 Improve Yourself 的表现条形图，还是 Scores 的数字统计行。",
    tactical_overlay_improve_yourself = "Improve Yourself 战术面板",
    tactical_overlay_scores = "Scores 战术面板",
    history_start_view = "Scores 历史记录",
    history_start_view_description = "选择打开一场历史比赛时，首先显示 Scores 的数字还是 Improve Yourself 的条形图。你仍可在历史记录中切换两种视图。",
    history_start_view_numbers = "默认显示数字",
    history_start_view_bars = "默认显示条形图",
    color_scheme = "配色方案",
    color_scheme_description = "选择结果颜色依据自定义目标还是队伍排名。其他玩家保持中性色。此设置只改变颜色；目标、评价、角色评估和进度评分仍以目标为准。",
    color_scheme_goal_oriented = "目标导向",
    color_scheme_team_comparison = "队伍对比",
    mod_title = "Improve Yourself",
    mod_description = "将 Scores 数据可视化为目标导向的战术、胜利和历史比赛面板。数据收集与历史记录仍完全由 Scores 负责。",
    settings_general = "常规",
    group_general = "常规",
    group_developer = "开发者选项",
    auto_damage_diagnostics = "每场任务自动生成伤害诊断",
    auto_damage_diagnostics_description = "启用后，每场任务都会生成一份带时间戳的完整伤害诊断文件，包括失败或中止的任务。文件保存在 Scores 可写入的历史记录文件夹中。",
    group_role_generalist = "全能型",
    group_role_frontline = "近战支柱",
    group_role_horde_control = "群潮控制",
    group_role_ranged_specialist = "远程专精",
    group_role_elite_boss = "精英与首领",
    group_role_support_control = "支援与控制",
    default_role = "默认角色",
    default_role_description = "每次打开面板时自动选择的角色。你仍可在面板内切换角色。",
    goal_setting_description = "目标表示你希望占小队总成绩的比例。四人队伍中，25%% 表示平均贡献；100%% 表示该项数据全部由你贡献。数值已预设为内置推荐值。",
    role_generalist = "全能型",
    role_frontline = "近战支柱",
    role_horde_control = "群潮控制",
    role_ranged_specialist = "远程专精",
    role_elite_boss = "精英与首领杀手",
    role_support_control = "支援与控制",
    settings_section_defense = "防御——越低越好",
    settings_section_offense = "进攻——越高越好",
    settings_section_team = "团队贡献——越高越好",
    loc_improve_yourself_show_bars = "显示条形图",
    loc_improve_yourself_show_numbers = "显示数字",

    iy_title = "提升自我！",
    iy_victory = "胜利",
    iy_lost = "失败",
    iy_current_performance = "当前表现",
    iy_live_mission_progress = "实时任务进度",
    iy_current_mission = "当前任务",
    iy_havoc_rank = "浩劫 %d",
    iy_difficulty_1 = "煽动",
    iy_difficulty_2 = "起义",
    iy_difficulty_3 = "恶意",
    iy_difficulty_4 = "异端",
    iy_difficulty_5 = "诅咒",
    iy_waiting_for_scores = "正在等待 Scores 实时数据",
    iy_live_footer = "战术面板打开时，实时数据会持续更新。",
    iy_unknown = "未知",
    iy_operative = "特工",
    iy_no_data = "无数据",
    iy_section_defense = "防御",
    iy_section_offense = "进攻",
    iy_section_teamplay = "团队协作",
    iy_combat_quality = "战斗质量",
    iy_goal = "目标",
    iy_best = "最佳",
    iy_worst = "最低",
    iy_outstanding = "卓越！",
    iy_impressive = "出色！",
    iy_goals_count = "%d/%d 项目标",
    iy_no_goals = "无目标",
    iy_met_count = "%d 项达成",
    iy_close_count = "%d 项接近",
    iy_missed_count = "%d 项未达成",
    iy_best_of_match = "全场最佳：%s",
    iy_improve_metrics = "需要提升：%s",
    iy_all_goals_close = "所有目标都触手可及",
    iy_metric_damage_taken = "承受伤害",
    iy_metric_times_downed = "倒地次数",
    iy_metric_times_disabled = "被控制次数",
    iy_metric_deaths = "死亡次数",
    iy_metric_damage_total = "总伤害",
    iy_metric_weakspot_hits = "命中弱点",
    iy_metric_weakspot_short = "弱点",
    iy_metric_melee_kills = "近战击杀",
    iy_metric_melee_short = "近战",
    iy_metric_ranged_kills = "远程击杀",
    iy_metric_ranged_short = "远程",
    iy_metric_swarmers = "杂兵",
    iy_metric_elites = "精英",
    iy_metric_specials = "特殊敌人",
    iy_metric_boss = "首领",
    iy_metric_coherency = "连携",
    iy_metric_saves = "救援",
    iy_metric_revives = "救起",
    iy_metric_ammo = "弹药",
    iy_metric_healthstations = "医疗站",
    iy_metric_objectives = "目标",
    iy_metric_currency = "资源",
    iy_metric_weakspot_percent = "弱点命中 %%",
    iy_metric_critical_percent = "暴击 %%",
    iy_metric_accuracy = "远程命中率",
    iy_damage_area = "范围伤害",
    iy_damage_melee = "近战伤害",
    iy_damage_ranged = "远程伤害",
    iy_damage_other = "其他伤害",
    iy_attacks_blocked = "格挡攻击",
    iy_counter_downed = "倒地",
    iy_counter_disabled = "被控制",
    iy_counter_deaths = "死亡",
    iy_source_falling = "坠落",
    iy_source_corruption = "腐败",
    iy_source_warp = "亚空间",
    iy_source_overheat = "过热",
    iy_source_netted = "被网住",
    iy_source_untracked = "未追踪",
    iy_source_self_damage = "自身伤害",
    iy_source_armored_hound = "装甲猎犬",
    iy_source_beast_of_nurgle = "纳垢兽",
    iy_source_hound = "猎犬",
    iy_source_mutated_poxwalker = "变异瘟疫行者",
    iy_source_groaner = "呻吟者",
    iy_source_bulwark = "盾卫",
    iy_source_crusher = "粉碎者",
    iy_source_reaper = "收割者",
    iy_source_houndmaster = "驯犬师",
    iy_source_plague_ogryn = "瘟疫欧格林",
    iy_source_poxwalker = "瘟疫行者",
    iy_source_poxburster = "瘟疫爆破者",
    iy_source_chaos_spawn = "混沌卵",
    iy_source_shotgunner = "霰弹枪手",
    iy_source_rager = "狂战士",
    iy_source_captain = "队长",
    iy_source_flamer = "火焰兵",
    iy_source_bomber = "投弹兵",
    iy_source_gunner = "枪手",
    iy_source_bruiser = "斗殴者",
    iy_source_mutant = "变种人",
    iy_source_mauler = "重击兵",
    iy_source_shooter = "射手",
    iy_source_sniper = "狙击手",
    iy_source_pox_gas = "瘟疫毒气",
    iy_source_barrel_fire = "燃烧桶",
    iy_source_barrel_explosion = "爆炸桶",
    iy_source_flamer_fire = "火焰兵烈焰",
    iy_source_beast_slime = "纳垢兽黏液",
    iy_source_ground_slam = "地面重击",
    iy_source_explosion = "爆炸",
    iy_source_area_effect = "范围效果",
    iy_source_ranged_attack = "远程攻击",
    iy_source_melee_attack = "近战攻击",
    iy_source_other = "其他",
}

local roles = {"generalist", "frontline", "horde_control", "ranged_specialist", "elite_boss", "support_control"}
local section_translations = {
    defense = "防御——越低越好",
    offense = "进攻——越高越好",
    team = "团队贡献——越高越好",
}
local goal_translations = {
    damage_taken = "承受伤害目标",
    times_downed = "倒地次数目标",
    times_disabled = "被控制次数目标",
    deaths = "死亡次数目标",
    damage_dealt = "总伤害目标",
    weakspot_hits = "弱点命中目标",
    melee_kills = "近战击杀目标",
    ranged_kills = "远程击杀目标",
    lesser_enemies = "杂兵击杀目标",
    melee_ranged_threats = "精英击杀目标",
    special_threats = "特殊敌人击杀目标",
    boss_damage_dealt = "首领伤害目标",
    coherency_efficiency = "连携目标",
    revived_operative = "救起目标",
    team_saves = "救援目标",
    ammo_score = "弹药得分目标",
}

for _, role in ipairs(roles) do
    for section, translation in pairs(section_translations) do
        zh_cn["section_" .. role .. "_" .. section] = translation
    end
    for metric, translation in pairs(goal_translations) do
        zh_cn["goal_" .. role .. "_" .. metric] = translation
    end
end

for key, entry in pairs(localization) do
    entry["zh-cn"] = zh_cn[key] or entry.en
end

return localization
