-- Widget titles resolve from the setting_id key; tooltips from "<setting_id>_description".

-- Resolve an official game term in the player's language, falling back to our own wording.
-- Localize never returns nil: an unknown key yields "<unlocalized ...>", the manager returns
-- "" until its string bundles are ready, and the global itself is false before it exists.
local function game_term(key, fallback)
	if not Localize then
		return fallback
	end
	local text = Localize(key)
	if not text or text == "" or string.sub(text, 1, 1) == "<" then
		return fallback
	end
	return text
end

local PERIL             = game_term("loc_ranged_warp_charge", "Peril")
local RELOAD            = game_term("loc_ingame_weapon_reload", "Reload")
local SCRIERS_GAZE      = game_term("loc_talent_psyker_combat_ability_overcharge_stance", "Scrier's Gaze")
local CRYSTALLINE_WILL  = game_term("loc_talent_psyker_alternative_peril_explosion", "Crystalline Will")
local BLITZ             = game_term("loc_tactical_overlay_build_blitz", "Blitz")
-- The base shout; Venting Shriek is the talent that upgrades it to vent Peril.
local PSYKINETICS_WRATH = game_term("loc_talent_psyker_2_combat", "Psykinetic's Wrath")
local VENTING_SHRIEK    = game_term("loc_talent_psyker_shout_vent_warp_charge", "Venting Shriek")
-- Inferred key: the talent granting psychic_fortress. Unverified in-game.
local WARP_UNBOUND      = game_term("loc_talent_psyker_overcharge_infinite_casting", "Warp Unbound")

-- Weapon categories stay hand-written: the game only names staffs per pattern
-- (forcestaff_p1..p4), and this mod covers all of them.

local LANGUAGES = { "en", "de", "es", "fr", "it", "pl", "ru", "ja", "ko", "pt-br", "zh-cn", "zh-tw" }

-- The on-screen indicator words, reused below as the two word dropdowns' defaults.
local TXT_SAFE = {
	en = "SAFE", de = "SICHER", es = "SEGURO", fr = "SÛR", it = "SICURO", pl = "BEZPIECZNIE",
	ru = "БЕЗОПАСНО", ja = "安全", ko = "안전", ["pt-br"] = "SEGURO", ["zh-cn"] = "安全", ["zh-tw"] = "安全",
}
local TXT_UNSAFE = {
	en = "UNSAFE", de = "UNSICHER", es = "PELIGRO", fr = "DANGER", it = "PERICOLO", pl = "NIEBEZPIECZNIE",
	ru = "ОПАСНО", ja = "危険", ko = "위험", ["pt-br"] = "PERIGO", ["zh-cn"] = "危险", ["zh-tw"] = "危險",
}

local WORD_DEFAULT = {
	en = "Default", de = "Standard", es = "Predeterminado", fr = "Défaut", it = "Predefinito",
	pl = "Domyślnie", ru = "По умолчанию", ja = "既定値", ko = "기본값", ["pt-br"] = "Padrão",
	["zh-cn"] = "默认", ["zh-tw"] = "預設",
}
local WORD_ON = {
	en = "On", de = "An", es = "Activado", fr = "Activé", it = "Attivo", pl = "Wł.",
	ru = "Вкл.", ja = "オン", ko = "켜짐", ["pt-br"] = "Ligado", ["zh-cn"] = "开启", ["zh-tw"] = "開啟",
}
local WORD_OFF = {
	en = "Off", de = "Aus", es = "Desactivado", fr = "Désactivé", it = "Disattivo", pl = "Wył.",
	ru = "Выкл.", ja = "オフ", ko = "꺼짐", ["pt-br"] = "Desligado", ["zh-cn"] = "关闭", ["zh-tw"] = "關閉",
}
local WORD_REACTIVE = {
	en = "Reactive", de = "Reaktiv", es = "Reactivo", fr = "Réactif", it = "Reattivo", pl = "Reaktywny",
	ru = "Реактивно", ja = "リアクティブ", ko = "반응형", ["pt-br"] = "Reativo", ["zh-cn"] = "响应式", ["zh-tw"] = "回應式",
}
local WORD_PROACTIVE = {
	en = "Proactive", de = "Proaktiv", es = "Proactivo", fr = "Proactif", it = "Proattivo", pl = "Proaktywny",
	ru = "Проактивно", ja = "プロアクティブ", ko = "선제형", ["pt-br"] = "Proativo", ["zh-cn"] = "主动式", ["zh-tw"] = "主動式",
}

-- Every tooltip ends with the widget's default, e.g. "... (Default = On)". `default` is one
-- display string for all languages, or a table keyed by language. `translations` may be empty
-- for settings whose tooltip is only the default.
local function with_default(default, translations)
	local out = {}
	for i = 1, #LANGUAGES do
		local lang = LANGUAGES[i]
		local value = type(default) == "table" and (default[lang] or default.en) or default
		local suffix = string.format("(%s = %s)", WORD_DEFAULT[lang] or WORD_DEFAULT.en, value)
		local text = translations[lang]
		out[lang] = text and (text .. " " .. suffix) or suffix
	end
	return out
end

return {
	mod_name = {
		en = "No More Overloads",
		de = "No More Overloads",
		es = "No More Overloads",
		fr = "No More Overloads",
		it = "No More Overloads",
		pl = "No More Overloads",
		ru = "No More Overloads",
		ja = "No More Overloads",
		ko = "No More Overloads",
		["pt-br"] = "No More Overloads",
		["zh-cn"] = "No More Overloads",
		["zh-tw"] = "No More Overloads",
	},
	mod_description = {
		en = string.format("Psyker anti-overload assistant. Blocks the %s actions that would trigger an Overload, warns on the HUD, and can quell %s or use %s / %s / %s for you. Only acts when an Overload would be unrecoverable.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		de = string.format("Psyker-Overload-Schutz. Blockiert die %s-Aktionen, die einen Overload auslösen würden, warnt im HUD und kann für dich %s entladen oder %s / %s / %s einsetzen. Greift nur ein, wenn ein Overload nicht mehr abwendbar wäre.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		es = string.format("Asistente antioverload para el Psyker. Bloquea las acciones de %s que provocarían un Overload, avisa en el HUD y puede sofocar %s o usar %s / %s / %s por ti. Solo actúa cuando un overload sería irrecuperable.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		fr = string.format("Assistant anti-overload pour le Psyker. Bloque les actions de %s qui déclencheraient un Overload, alerte sur l'ATH et peut apaiser le %s ou utiliser %s / %s / %s à votre place. N'agit que si un overload serait irrécupérable.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		it = string.format("Assistente anti-overload per lo Psyker. Blocca le azioni di %s che causerebbero un Overload, avvisa sull'HUD e può sfogare il %s o usare %s / %s / %s al posto tuo. Agisce solo quando un overload sarebbe irrecuperabile.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		pl = string.format("Asystent anty-overload dla Psykera. Blokuje akcje %s, które wywołałyby Overload, ostrzega na HUD-zie i może za ciebie wygasić %s lub użyć %s / %s / %s. Działa tylko wtedy, gdy overloadu nie dałoby się cofnąć.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ru = string.format("Помощник против Overload для Псайкера. Блокирует действия %s, которые вызвали бы Overload, предупреждает на HUD и может усмирить %s или применить %s / %s / %s за вас. Вмешивается, только если Overload стал бы неотвратимым.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ja = string.format("サイカー用オーバーロード防止アシスト。Overload を引き起こす %s アクションをブロックし、HUD で警告し、代わりに %s のクエルや %s / %s / %s の発動も行えます。Overload を回避できない場合にのみ介入します。", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ko = string.format("사이커용 오버로드 방지 도우미. Overload를 유발하는 %s 행동을 차단하고, HUD로 경고하며, 대신 %s를 진정하거나 %s / %s / %s를 사용할 수 있습니다. Overload를 되돌릴 수 없을 때만 개입합니다.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["pt-br"] = string.format("Assistente anti-overload para o Psyker. Bloqueia as ações de %s que causariam um Overload, avisa no HUD e pode dissipar %s ou usar %s / %s / %s por você. Só age quando um overload seria irrecuperável.", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["zh-cn"] = string.format("灵能者防过载助手。拦截会触发 Overload 的 %s 动作，在 HUD 上警告，并可代你平息 %s 或发动 %s / %s / %s。仅在 Overload 已无法挽回时才介入。", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["zh-tw"] = string.format("靈能者防過載助手。攔截會觸發 Overload 的 %s 動作，在 HUD 上警告，並可代你平息 %s 或發動 %s / %s / %s。僅在 Overload 已無法挽回時才介入。", PERIL, PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
	},

	-- On-screen indicator words (defaults)
	txt_safe = TXT_SAFE,
	txt_unsafe = TXT_UNSAFE,

	-- Groups
	group_blocking = {
		en = "Input Blocking",
		de = "Eingabe-Blockierung",
		es = "Bloqueo de entradas",
		fr = "Blocage des entrées",
		it = "Blocco degli input",
		pl = "Blokowanie wejść",
		ru = "Блокировка ввода",
		ja = "入力ブロック",
		ko = "입력 차단",
		["pt-br"] = "Bloqueio de entrada",
		["zh-cn"] = "输入拦截",
		["zh-tw"] = "輸入攔截",
	},
	group_smart_triggers = {
		en = "Auto Recovery",
		de = "Automatische Rettung",
		es = "Recuperación automática",
		fr = "Récupération auto",
		it = "Recupero automatico",
		pl = "Automatyczne ratowanie",
		ru = "Автоматическое спасение",
		ja = "自動リカバリー",
		ko = "자동 회복",
		["pt-br"] = "Recuperação automática",
		["zh-cn"] = "自动自救",
		["zh-tw"] = "自動自救",
	},
	group_indicator = {
		en = "HUD Indicator",
		de = "HUD-Anzeige",
		es = "Indicador del HUD",
		fr = "Indicateur ATH",
		it = "Indicatore HUD",
		pl = "Wskaźnik HUD",
		ru = "Индикатор HUD",
		ja = "HUD 表示",
		ko = "HUD 표시기",
		["pt-br"] = "Indicador do HUD",
		["zh-cn"] = "HUD 指示器",
		["zh-tw"] = "HUD 指示器",
	},

	-- Input Blocking
	block_staffs = {
		en = "Block Force Staffs",
		de = "Force Staffs blockieren",
		es = "Bloquear Force Staffs",
		fr = "Bloquer les Force Staffs",
		it = "Blocca le Force Staff",
		pl = "Blokuj Force Staffy",
		ru = "Блокировать Force Staff",
		ja = "Force Staff をブロック",
		ko = "Force Staff 차단",
		["pt-br"] = "Bloquear Force Staffs",
		["zh-cn"] = "拦截 Force Staff",
		["zh-tw"] = "攔截 Force Staff",
	},
	block_staffs_description = with_default(WORD_ON, {}),
	block_blitzes = {
		en = string.format("Block %s", BLITZ),
		de = string.format("%s blockieren", BLITZ),
		es = string.format("Bloquear %s", BLITZ),
		fr = string.format("Bloquer le %s", BLITZ),
		it = string.format("Blocca il %s", BLITZ),
		pl = string.format("Blokuj %s", BLITZ),
		ru = string.format("Блокировать %s", BLITZ),
		ja = string.format("%s をブロック", BLITZ),
		ko = string.format("%s 차단", BLITZ),
		["pt-br"] = string.format("Bloquear %s", BLITZ),
		["zh-cn"] = string.format("拦截 %s", BLITZ),
		["zh-tw"] = string.format("攔截 %s", BLITZ),
	},
	block_blitzes_description = with_default(WORD_ON, {}),
	block_force_swords = {
		en = "Block Force Swords",
		de = "Force Swords blockieren",
		es = "Bloquear Force Swords",
		fr = "Bloquer les Force Swords",
		it = "Blocca le Force Sword",
		pl = "Blokuj Force Swordy",
		ru = "Блокировать Force Sword",
		ja = "Force Sword をブロック",
		ko = "Force Sword 차단",
		["pt-br"] = "Bloquear Force Swords",
		["zh-cn"] = "拦截 Force Sword",
		["zh-tw"] = "攔截 Force Sword",
	},
	block_force_swords_description = with_default(WORD_ON, {}),
	block_duelling_swords = {
		en = "Block Duelling Swords",
		de = "Duellschwerter blockieren",
		es = "Bloquear espadas de duelo",
		fr = "Bloquer les épées de duel",
		it = "Blocca le spade da duello",
		pl = "Blokuj miecze do pojedynków",
		ru = "Блокировать дуэльные мечи",
		ja = "デュエリングソードをブロック",
		ko = "듀얼링 소드 차단",
		["pt-br"] = "Bloquear espadas de duelo",
		["zh-cn"] = "拦截决斗剑",
		["zh-tw"] = "攔截決鬥劍",
	},
	block_duelling_swords_description = with_default(WORD_ON, {}),
	block_guns = {
		en = "Block Laspistols",
		de = "Laspistolen blockieren",
		es = "Bloquear Laspistols",
		fr = "Bloquer les Laspistols",
		it = "Blocca le Laspistol",
		pl = "Blokuj Laspistole",
		ru = "Блокировать Laspistol",
		ja = "Laspistol をブロック",
		ko = "Laspistol 차단",
		["pt-br"] = "Bloquear Laspistols",
		["zh-cn"] = "拦截 Laspistol",
		["zh-tw"] = "攔截 Laspistol",
	},
	block_guns_description = with_default(WORD_ON, {}),
	block_plasma = {
		en = "Block Plasma Guns (any class)",
		de = "Plasmagewehre blockieren (jede Klasse)",
		es = "Bloquear armas de plasma (cualquier clase)",
		fr = "Bloquer les fusils à plasma (toute classe)",
		it = "Blocca i fucili al plasma (qualsiasi classe)",
		pl = "Blokuj karabiny plazmowe (dowolna klasa)",
		ru = "Блокировать плазменные ружья (любой класс)",
		ja = "プラズマガンをブロック（全クラス）",
		ko = "플라즈마 건 차단 (모든 직업)",
		["pt-br"] = "Bloquear armas de plasma (qualquer classe)",
		["zh-cn"] = "拦截等离子枪（所有职业）",
		["zh-tw"] = "攔截電漿槍（所有職業）",
	},
	block_plasma_description = with_default(WORD_ON, {
		en = "Blocks the fire at maximum heat so a Plasma Gun can't self-detonate. Works on any class; bracing and venting still work.",
		de = "Blockiert bei maximaler Hitze den Schuss, damit ein Plasmagewehr sich nicht selbst sprengt. Für jede Klasse; Anlegen und Entlüften funktionieren weiter.",
		es = "Bloquea el disparo con el calor al máximo para que un arma de plasma no se autodetone. Cualquier clase; apuntar y ventilar siguen funcionando.",
		fr = "Bloque le tir à chaleur maximale pour qu'un fusil à plasma ne s'autodétruise pas. Toute classe ; visée et purge restent possibles.",
		it = "Blocca il fuoco a calore massimo così un fucile al plasma non si autodistrugge. Qualsiasi classe; mira e sfiato funzionano ancora.",
		pl = "Blokuje strzał przy maksymalnym przegrzaniu, by karabin plazmowy się nie wysadził. Dowolna klasa; celowanie i wentylacja działają.",
		ru = "Блокирует выстрел при максимальном перегреве, чтобы плазменное ружьё не взорвалось. Любой класс; прицеливание и стравливание работают.",
		ja = "最大ヒート時の射撃を止め、プラズマガンの自爆を防ぎます。全クラス対応。構えとベントは通常どおり使えます。",
		ko = "최대 과열 상태의 발사를 막아 플라즈마 건의 자폭을 방지합니다. 모든 직업; 견착과 배출은 그대로 작동합니다.",
		["pt-br"] = "Bloqueia o disparo com o calor no máximo para uma arma de plasma não se autodestruir. Qualquer classe; mirar e ventilar continuam funcionando.",
		["zh-cn"] = "在过热达到上限时拦截开火，防止等离子枪自爆。适用于所有职业；仍可举枪和散热。",
		["zh-tw"] = "在過熱達到上限時攔截開火，防止電漿槍自爆。適用於所有職業；仍可舉槍和散熱。",
	}),
	block_crystalline = {
		en = string.format("Block %s overloads", CRYSTALLINE_WILL),
		de = string.format("%s-Overloads blockieren", CRYSTALLINE_WILL),
		es = string.format("Bloquear overloads con %s", CRYSTALLINE_WILL),
		fr = string.format("Bloquer les overloads avec %s", CRYSTALLINE_WILL),
		it = string.format("Blocca gli overload con %s", CRYSTALLINE_WILL),
		pl = string.format("Blokuj overloady z %s", CRYSTALLINE_WILL),
		ru = string.format("Блокировать Overload с %s", CRYSTALLINE_WILL),
		ja = string.format("%s の Overload をブロック", CRYSTALLINE_WILL),
		ko = string.format("%s Overload 차단", CRYSTALLINE_WILL),
		["pt-br"] = string.format("Bloquear overloads com %s", CRYSTALLINE_WILL),
		["zh-cn"] = string.format("拦截 %s 的 Overload", CRYSTALLINE_WILL),
		["zh-tw"] = string.format("攔截 %s 的 Overload", CRYSTALLINE_WILL),
	},
	block_crystalline_description = with_default(WORD_OFF, {
		en = string.format("%s makes overload non-lethal, so by default these casts are left alone for self-explode builds. Turn this on to block them like any other overload. The indicator still warns either way.", CRYSTALLINE_WILL),
		de = string.format("%s macht den Overload nicht tödlich, daher bleiben diese Aktionen standardmäßig unangetastet, damit Selbstexplosions-Builds funktionieren. Aktiviere dies, um sie wie jeden anderen Overload zu blockieren. Die Anzeige warnt weiterhin.", CRYSTALLINE_WILL),
		es = string.format("%s hace que el overload no sea letal, así que por defecto estos lanzamientos se dejan pasar para las builds de autoexplosión. Actívalo para bloquearlos como cualquier otro overload. El indicador sigue avisando igualmente.", CRYSTALLINE_WILL),
		fr = string.format("%s rend l'overload non létal ; par défaut, ces actions sont donc laissées passer pour les builds d'auto-explosion. Activez ceci pour les bloquer comme tout autre overload. L'indicateur alerte quand même.", CRYSTALLINE_WILL),
		it = string.format("%s rende l'overload non letale, quindi per impostazione predefinita queste azioni vengono lasciate passare per le build ad autoesplosione. Attivalo per bloccarle come qualsiasi altro overload. L'indicatore avvisa comunque.", CRYSTALLINE_WILL),
		pl = string.format("%s sprawia, że overload nie jest śmiertelny, więc domyślnie te akcje są przepuszczane dla buildów z samowysadzaniem. Włącz to, aby blokować je jak każdy inny overload. Wskaźnik i tak ostrzega.", CRYSTALLINE_WILL),
		ru = string.format("С %s Overload не смертелен, поэтому по умолчанию эти действия пропускаются для билдов с самоподрывом. Включите, чтобы блокировать их как любой другой Overload. Индикатор всё равно предупреждает.", CRYSTALLINE_WILL),
		ja = string.format("%s があれば Overload は致命的ではないため、既定ではこれらのアクションは自爆ビルドのためにそのまま通します。オンにすると他の Overload と同様にブロックします。インジケーターはどちらの場合も警告します。", CRYSTALLINE_WILL),
		ko = string.format("%s이 있으면 Overload가 치명적이지 않으므로 기본적으로 이러한 시전은 자폭 빌드를 위해 그대로 둡니다. 켜면 다른 Overload처럼 차단합니다. 표시기는 어느 경우든 계속 경고합니다.", CRYSTALLINE_WILL),
		["pt-br"] = string.format("%s torna o overload não letal, então por padrão essas ações são deixadas passar para builds de autoexplosão. Ative para bloqueá-las como qualquer outro overload. O indicador avisa de qualquer forma.", CRYSTALLINE_WILL),
		["zh-cn"] = string.format("%s 让 Overload 不致命，因此默认会放行这些动作以支持自爆流派。开启后会像其他 Overload 一样拦截它们。指示器仍会警告。", CRYSTALLINE_WILL),
		["zh-tw"] = string.format("%s 讓 Overload 不致命，因此預設會放行這些動作以支援自爆流派。開啟後會像其他 Overload 一樣攔截它們。指示器仍會警告。", CRYSTALLINE_WILL),
	}),

	-- Auto Recovery
	auto_ability = {
		en = "Auto ability use",
		de = "Automatischer Fähigkeitseinsatz",
		es = "Uso automático de habilidad",
		fr = "Utilisation auto de la capacité",
		it = "Uso automatico dell'abilità",
		pl = "Automatyczne użycie zdolności",
		ru = "Автоприменение способности",
		ja = "アビリティ自動使用",
		ko = "능력 자동 사용",
		["pt-br"] = "Uso automático de habilidade",
		["zh-cn"] = "自动使用技能",
		["zh-tw"] = "自動使用技能",
	},
	auto_ability_description = with_default(WORD_ON, {
		en = string.format("Fire %s, %s or %s the moment it is ready while your %s is at maximum.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE, PERIL),
		de = string.format("Setzt %s, %s oder %s ein, sobald es bereit ist, während dein %s am Maximum ist.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE, PERIL),
		es = string.format("Usa %s, %s o %s en cuanto esté lista mientras tu %s está al máximo.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE, PERIL),
		fr = string.format("Déclenche %s, %s ou %s dès qu'elle est prête tant que votre %s est au maximum.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE, PERIL),
		it = string.format("Attiva %s, %s o %s appena è pronta mentre il tuo %s è al massimo.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE, PERIL),
		pl = string.format("Używa %s, %s lub %s, gdy tylko będzie gotowe, gdy twój %s jest na maksimum.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE, PERIL),
		ru = string.format("Применяет %s, %s или %s, как только она готова, пока ваш %s на максимуме.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE, PERIL),
		ja = string.format("%s が最大の間、使用可能になった瞬間に %s、%s または %s を発動します。", PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ko = string.format("%s이 최대인 동안 %s, %s 또는 %s가 준비되는 즉시 발동합니다.", PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["pt-br"] = string.format("Aciona %s, %s ou %s assim que estiver pronta enquanto seu %s estiver no máximo.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE, PERIL),
		["zh-cn"] = string.format("当 %s 达到上限时，%s、%s 或 %s 一就绪便立即发动。", PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["zh-tw"] = string.format("當 %s 達到上限時，%s、%s 或 %s 一就緒便立即發動。", PERIL, PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
	}),
	when_to_use = {
		en = "When to use",
		de = "Wann einsetzen",
		es = "Cuándo usar",
		fr = "Quand l'utiliser",
		it = "Quando usarla",
		pl = "Kiedy używać",
		ru = "Когда применять",
		ja = "使用タイミング",
		ko = "사용 시점",
		["pt-br"] = "Quando usar",
		["zh-cn"] = "使用时机",
		["zh-tw"] = "使用時機",
	},
	when_to_use_description = with_default(WORD_REACTIVE, {
		en = "Reactive (default) holds the ability for the instant an overload triggers. Proactive fires it as soon as it is off cooldown, waiting only for your current action to finish (e.g. it lets a flame staff cast end, then casts).",
		de = "Reaktiv (Standard) hält die Fähigkeit für den Moment zurück, in dem ein Overload auslöst. Proaktiv setzt sie ein, sobald sie bereit ist, und wartet nur, bis deine aktuelle Aktion endet (z. B. lässt sie einen Flammenstab-Zauber auslaufen und setzt dann ein).",
		es = "Reactivo (predeterminado) reserva la habilidad para el instante en que se desencadena un overload. Proactivo la usa en cuanto sale del enfriamiento, esperando solo a que termine tu acción actual (p. ej., deja que acabe un lanzamiento del bastón de fuego y entonces la usa).",
		fr = "Réactif (par défaut) garde la capacité pour l'instant où un overload se déclenche. Proactif la déclenche dès qu'elle est disponible, en attendant seulement la fin de votre action en cours (p. ex. il laisse un tir de bâton de feu se terminer, puis l'utilise).",
		it = "Reattivo (predefinito) tiene l'abilità per l'istante in cui scatta un overload. Proattivo la usa appena è fuori ricarica, aspettando solo che finisca la tua azione attuale (es. lascia terminare un lancio del bastone di fuoco, poi la usa).",
		pl = "Reaktywny (domyślnie) trzyma zdolność na moment, w którym wyzwala się overload. Proaktywny używa jej, gdy tylko wyjdzie z odnowienia, czekając tylko na zakończenie bieżącej akcji (np. pozwala skończyć rzut ognistą laską, po czym jej używa).",
		ru = "Реактивно (по умолчанию) приберегает способность на момент, когда срабатывает Overload. Проактивно применяет её, как только она выйдет из отката, ожидая лишь завершения текущего действия (напр., даёт закончить каст огненного посоха, затем применяет).",
		ja = "リアクティブ（既定）はアビリティを Overload が発生する瞬間まで温存します。プロアクティブはクールダウンが明けた瞬間に、現在のアクションが終わるのだけを待って発動します（例：フレイムスタッフのキャストが止まるのを待ってから発動）。",
		ko = "반응형(기본값)은 Overload가 발동하는 순간을 위해 능력을 아껴 둡니다. 선제형은 재사용 대기시간이 끝나는 즉시, 현재 행동이 끝나기만 기다렸다가 발동합니다(예: 화염 스태프 시전이 멈출 때까지 기다렸다가 발동).",
		["pt-br"] = "Reativo (padrão) guarda a habilidade para o instante em que um overload dispara. Proativo a aciona assim que sai da recarga, esperando apenas sua ação atual terminar (ex.: deixa um lançamento do cajado de fogo acabar e então aciona).",
		["zh-cn"] = "响应式（默认）会把技能留到 Overload 触发的瞬间。主动式则在技能冷却结束后立即施放，只等你当前的动作结束（例如等火焰法杖的施放停止后再施放）。",
		["zh-tw"] = "回應式（預設）會把技能留到 Overload 觸發的瞬間。主動式則在技能冷卻結束後立即施放，只等你當前的動作結束（例如等火焰法杖的施放停止後再施放）。",
	}),
	min_peril = {
		en = string.format("Minimum %s threshold", PERIL),
		de = string.format("Mindest-%s-Schwelle", PERIL),
		es = string.format("Umbral mínimo de %s", PERIL),
		fr = string.format("Seuil minimum de %s", PERIL),
		it = string.format("Soglia minima di %s", PERIL),
		pl = string.format("Minimalny próg %s", PERIL),
		ru = string.format("Минимальный порог %s", PERIL),
		ja = string.format("%s の最小しきい値", PERIL),
		ko = string.format("최소 %s 임계값", PERIL),
		["pt-br"] = string.format("Limite mínimo de %s", PERIL),
		["zh-cn"] = string.format("最低%s阈值", PERIL),
		["zh-tw"] = string.format("最低%s閾值", PERIL),
	},
	min_peril_description = with_default("0", {
		en = string.format("In Proactive mode, only fire the ability once %s is at least this percentage (0-100). 0 fires regardless. Reactive is unaffected.", PERIL),
		de = string.format("Im Proaktiv-Modus wird die Fähigkeit erst eingesetzt, wenn %s mindestens diesen Prozentsatz erreicht (0-100). 0 setzt sie immer ein. Reaktiv bleibt unberührt.", PERIL),
		es = string.format("En modo Proactivo, solo usa la habilidad cuando %s alcanza al menos este porcentaje (0-100). 0 la usa siempre. Reactivo no se ve afectado.", PERIL),
		fr = string.format("En mode Proactif, la capacité ne se déclenche que lorsque le %s atteint au moins ce pourcentage (0-100). 0 la déclenche toujours. Le mode Réactif n'est pas affecté.", PERIL),
		it = string.format("In modalità Proattiva, l'abilità si attiva solo quando il %s raggiunge almeno questa percentuale (0-100). 0 la attiva sempre. La modalità Reattiva non è influenzata.", PERIL),
		pl = string.format("W trybie Proaktywnym zdolność uruchamia się dopiero, gdy %s osiągnie co najmniej ten procent (0-100). 0 uruchamia zawsze. Tryb Reaktywny pozostaje bez zmian.", PERIL),
		ru = string.format("В Проактивном режиме способность применяется, только когда %s достигает хотя бы этого процента (0-100). 0 — применять всегда. На Реактивный режим не влияет.", PERIL),
		ja = string.format("プロアクティブでは、%s がこの割合（0～100）以上のときだけアビリティを発動します。0 なら常に発動。リアクティブには影響しません。", PERIL),
		ko = string.format("선제형에서는 %s이 이 비율(0-100) 이상일 때만 능력을 발동합니다. 0이면 항상 발동합니다. 반응형에는 영향을 주지 않습니다.", PERIL),
		["pt-br"] = string.format("No modo Proativo, a habilidade só é acionada quando o %s atinge pelo menos esta porcentagem (0-100). 0 aciona sempre. O modo Reativo não é afetado.", PERIL),
		["zh-cn"] = string.format("主动式下，仅当%s达到至少该百分比（0-100）时才发动技能。0 表示始终发动。不影响响应式。", PERIL),
		["zh-tw"] = string.format("主動式下，僅當%s達到至少該百分比（0-100）時才發動技能。0 表示始終發動。不影響回應式。", PERIL),
	}),
	recover_window = {
		en = "Cooldown tolerance (seconds)",
		de = "Abklingzeit-Toleranz (Sekunden)",
		es = "Tolerancia de enfriamiento (segundos)",
		fr = "Tolérance de recharge (secondes)",
		it = "Tolleranza di ricarica (secondi)",
		pl = "Tolerancja odnowienia (sekundy)",
		ru = "Допуск перезарядки (секунды)",
		ja = "クールダウン許容値（秒）",
		ko = "재사용 대기시간 허용치 (초)",
		["pt-br"] = "Tolerância de recarga (segundos)",
		["zh-cn"] = "冷却容差（秒）",
		["zh-tw"] = "冷卻容差（秒）",
	},
	recover_window_description = with_default("0.0", {
		en = string.format("Still count as SAFE while %s, %s or %s is this close to ready - regardless of choice, you can still stop the overload in time.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		de = string.format("Gilt weiterhin als SICHER, solange %s, %s oder %s so kurz vor der Bereitschaft steht - unabhängig von der Wahl stoppst du den Overload noch rechtzeitig.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		es = string.format("Sigues contando como SEGURO mientras a %s, %s o %s le falte este tiempo para estar listo - sea cual sea tu elección, aún puedes detener el overload a tiempo.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		fr = string.format("Reste considéré comme SÛR tant que %s, %s ou %s est à ce délai d'être prêt - quel que soit votre choix, vous pouvez encore stopper l'overload à temps.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		it = string.format("Conta ancora come SICURO finché a %s, %s o %s manca questo tempo per essere pronto - a prescindere dalla scelta, puoi ancora fermare l'overload in tempo.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		pl = string.format("Nadal liczy się jako BEZPIECZNIE, dopóki %s, %s lub %s jest tak blisko gotowości - niezależnie od wyboru wciąż zdążysz zatrzymać overload.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ru = string.format("Всё ещё считается БЕЗОПАСНО, пока %s, %s или %s осталось столько до готовности - независимо от выбора вы успеете остановить Overload.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ja = string.format("%s、%s または %s の再使用までこの秒数以内なら 安全 と見なします。どれを選んでいても Overload を間に合って止められます。", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		ko = string.format("%s, %s 또는 %s이 이만큼 안에 준비되면 계속 안전 으로 간주합니다. 어느 것을 선택했든 제때 Overload를 멈출 수 있습니다.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["pt-br"] = string.format("Ainda conta como SEGURO enquanto %s, %s ou %s estiver a este tempo de ficar pronto - independentemente da escolha, você ainda interrompe o overload a tempo.", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["zh-cn"] = string.format("只要 %s、%s 或 %s 距离就绪不超过这么久，就仍视为 安全。无论选择哪个，你都能及时中止 Overload。", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
		["zh-tw"] = string.format("只要 %s、%s 或 %s 距離就緒不超過這麼久，就仍視為 安全。無論選擇哪個，你都能及時中止 Overload。", PSYKINETICS_WRATH, VENTING_SHRIEK, SCRIERS_GAZE),
	}),
	auto_fire_before_unsafe = {
		en = "Auto fire before unsafe",
	},
	auto_fire_before_unsafe_description = with_default(WORD_ON, {
		en = string.format("Fires a charging staff's charged shot just before %s reaches UNSAFE, so you land the cast instead of it being blocked and quelled. Works on all staffs, including the flame staff.", PERIL),
	}),
	auto_quell = {
		en = "Automatic quelling",
		de = "Automatisches Entladen",
		es = "Sofocado automático",
		fr = "Apaisement automatique",
		it = "Sfogo automatico",
		pl = "Automatyczne wygaszanie",
		ru = "Автоматическое усмирение",
		ja = "自動クエル",
		ko = "자동 진정",
		["pt-br"] = "Dissipação automática",
		["zh-cn"] = "自动平息",
		["zh-tw"] = "自動平息",
	},
	auto_quell_description = with_default(WORD_ON, {
		en = string.format("Holds %s to quell %s while UNSAFE. Never during %s.", RELOAD, PERIL, WARP_UNBOUND),
		de = string.format("Hält bei UNSICHER %s gedrückt, um %s zu entladen. Nie während %s.", RELOAD, PERIL, WARP_UNBOUND),
		es = string.format("Mantiene %s pulsado para sofocar %s mientras estés en PELIGRO. Nunca durante %s.", RELOAD, PERIL, WARP_UNBOUND),
		fr = string.format("Maintient %s pour apaiser le %s en état de DANGER. Jamais pendant %s.", RELOAD, PERIL, WARP_UNBOUND),
		it = string.format("Tiene premuto %s per sfogare il %s quando sei in PERICOLO. Mai durante %s.", RELOAD, PERIL, WARP_UNBOUND),
		pl = string.format("Przytrzymuje %s, aby wygasić %s w stanie NIEBEZPIECZNIE. Nigdy podczas %s.", RELOAD, PERIL, WARP_UNBOUND),
		ru = string.format("Удерживает %s, чтобы усмирить %s в состоянии ОПАСНО. Никогда во время %s.", RELOAD, PERIL, WARP_UNBOUND),
		ja = string.format("危険 の間、%s を押し続けて %s をクエルします。%s 中は作動しません。", RELOAD, PERIL, WARP_UNBOUND),
		ko = string.format("위험 상태일 때 %s를 눌러 %s를 진정시킵니다. %s 중에는 작동하지 않습니다.", RELOAD, PERIL, WARP_UNBOUND),
		["pt-br"] = string.format("Segura %s para dissipar %s enquanto estiver em PERIGO. Nunca durante %s.", RELOAD, PERIL, WARP_UNBOUND),
		["zh-cn"] = string.format("处于 危险 时按住 %s 平息 %s。%s 期间不触发。", RELOAD, PERIL, WARP_UNBOUND),
		["zh-tw"] = string.format("處於 危險 時按住 %s 平息 %s。%s 期間不觸發。", RELOAD, PERIL, WARP_UNBOUND),
	}),
	auto_quell_interrupt = {
		en = "Interrupt on player action",
		de = "Bei Spieleraktion unterbrechen",
		es = "Interrumpir al actuar",
		fr = "Interrompre si vous agissez",
		it = "Interrompi quando agisci",
		pl = "Przerwij przy akcji gracza",
		ru = "Прерывать при действии игрока",
		ja = "プレイヤーの操作で中断",
		ko = "플레이어 행동 시 중단",
		["pt-br"] = "Interromper ao agir",
		["zh-cn"] = "玩家操作时中断",
		["zh-tw"] = "玩家操作時中斷",
	},
	auto_quell_interrupt_description = with_default(WORD_ON, {
		en = "Stop quelling the moment you attack, dodge, use an ability or take any other non-movement action. Moving and looking around never interrupt it.",
		de = "Bricht das Entladen sofort ab, sobald du angreifst, ausweichst, eine Fähigkeit einsetzt oder eine andere Aktion außer Bewegung ausführst. Bewegen und Umsehen unterbrechen es nie.",
		es = "Deja de sofocar en cuanto atacas, esquivas, usas una habilidad o realizas cualquier otra acción que no sea moverte. Moverte y mirar alrededor nunca lo interrumpen.",
		fr = "Arrête l'apaisement dès que vous attaquez, esquivez, utilisez une capacité ou effectuez toute autre action hors déplacement. Se déplacer et regarder autour ne l'interrompent jamais.",
		it = "Interrompe lo sfogo non appena attacchi, schivi, usi un'abilità o compi qualsiasi altra azione che non sia il movimento. Muoverti e guardarti intorno non lo interrompono mai.",
		pl = "Przerywa wygaszanie w chwili, gdy atakujesz, unikasz, używasz zdolności lub wykonujesz dowolną inną akcję poza ruchem. Poruszanie się i rozglądanie nigdy go nie przerywają.",
		ru = "Прекращает усмирение, как только вы атакуете, уклоняетесь, применяете способность или совершаете любое другое действие, кроме передвижения. Движение и обзор камерой его не прерывают.",
		ja = "攻撃、回避、アビリティ使用など、移動以外の操作をした瞬間にクエルを中断します。移動と視点操作では中断されません。",
		ko = "공격, 회피, 능력 사용 등 이동이 아닌 행동을 하는 순간 진정을 중단합니다. 이동과 시점 조작으로는 중단되지 않습니다.",
		["pt-br"] = "Para de dissipar assim que você ataca, esquiva, usa uma habilidade ou realiza qualquer outra ação que não seja se mover. Mover-se e olhar ao redor nunca o interrompem.",
		["zh-cn"] = "当你攻击、闪避、使用技能或进行任何移动以外的操作时，立即中断平息。移动和转动视角不会中断它。",
		["zh-tw"] = "當你攻擊、閃避、使用技能或進行任何移動以外的操作時，立即中斷平息。移動和轉動視角不會中斷它。",
	}),
	auto_quell_hold = {
		en = "Extra quell hold (seconds)",
		de = "Zusätzliches Entladen (Sekunden)",
		es = "Sofocado adicional (segundos)",
		fr = "Apaisement supplémentaire (secondes)",
		it = "Sfogo aggiuntivo (secondi)",
		pl = "Dodatkowe wygaszanie (sekundy)",
		ru = "Доп. усмирение (секунды)",
		ja = "追加クエル時間（秒）",
		ko = "추가 진정 시간 (초)",
		["pt-br"] = "Dissipação extra (segundos)",
		["zh-cn"] = "额外平息时长（秒）",
		["zh-tw"] = "額外平息時長（秒）",
	},
	auto_quell_hold_description = with_default("0.0", {
		en = "Keep quelling this long after UNSAFE clears, instead of stopping at the edge. 0 = stop immediately.",
		de = "Entlädt nach dem Ende von UNSICHER noch so lange weiter, statt am Limit zu stoppen. 0 = sofort stoppen.",
		es = "Sigue sofocando este tiempo después de dejar de estar en PELIGRO, en vez de parar al borde. 0 = parar de inmediato.",
		fr = "Continue d'apaiser pendant ce délai après la fin du DANGER, au lieu de s'arrêter à la limite. 0 = arrêt immédiat.",
		it = "Continua a sfogare per questo tempo dopo la fine del PERICOLO, invece di fermarsi al limite. 0 = ferma subito.",
		pl = "Wygasza jeszcze tak długo po ustaniu stanu NIEBEZPIECZNIE, zamiast zatrzymywać się na krawędzi. 0 = zatrzymaj natychmiast.",
		ru = "Продолжает усмирение столько после снятия ОПАСНО, вместо остановки на грани. 0 = остановиться сразу.",
		ja = "危険 が解除された後もこの秒数だけクエルを続けます（限界ぎりぎりで止めない）。0 = 即座に停止。",
		ko = "위험 이 해제된 뒤에도 이만큼 더 진정을 계속합니다(한계선에서 멈추지 않음). 0 = 즉시 중지.",
		["pt-br"] = "Continua dissipando por este tempo depois que o PERIGO acaba, em vez de parar no limite. 0 = parar imediatamente.",
		["zh-cn"] = "脱离 危险 后再继续平息这么久，而不是卡在临界点停手。0 = 立即停止。",
		["zh-tw"] = "脫離 危險 後再繼續平息這麼久，而不是卡在臨界點停手。0 = 立即停止。",
	}),

	-- Max Gaze Quell Watchdog Setting
	max_gaze_quell_duration = {
		en = "Max Gaze Quell Duration (seconds)",
	},
	max_gaze_quell_duration_description = with_default("1.0", {
		en = "If a Scryer's Gaze quell channel lasts longer than this duration, quelling will immediately abort and fire through to 100% to exit Gaze.",
	}),

	auto_plasma_vent = {
		en = "Automatic plasma venting",
		de = "Automatisches Plasma-Entlüften",
		es = "Ventilación automática de plasma",
		fr = "Purge automatique du plasma",
		it = "Sfiato automatico del plasma",
		pl = "Automatyczne wentylowanie plazmy",
		ru = "Автоматическое стравливание плазмы",
		ja = "プラズマ自動排熱",
		ko = "플라즈마 자동 배출",
		["pt-br"] = "Ventilação automática de plasma",
		["zh-cn"] = "等离子枪自动散热",
		["zh-tw"] = "電漿槍自動散熱",
	},
	auto_plasma_vent_description = with_default(WORD_ON, {
		en = "Holds the weapon special to vent Plasma Gun heat while UNSAFE (any class). Venting costs a little health, so it only kicks in when you are about to overheat.",
		de = "Hält bei UNSICHER die Waffen-Spezialfähigkeit, um die Hitze des Plasmagewehrs abzulassen (für jede Klasse). Entlüften kostet etwas Leben und greift daher erst kurz vor der Überhitzung.",
		es = "Mantiene la habilidad especial del arma para ventilar el calor del arma de plasma mientras estés en PELIGRO (cualquier clase). Ventilar cuesta un poco de salud, así que solo se activa cuando estás a punto de sobrecalentarte.",
		fr = "Maintient la capacité spéciale de l'arme pour purger la chaleur du fusil à plasma en état de DANGER (toute classe). La purge coûte un peu de vie, elle ne se déclenche donc qu'au bord de la surchauffe.",
		it = "Tiene premuta l'abilità speciale dell'arma per sfiatare il calore del fucile al plasma quando sei in PERICOLO (qualsiasi classe). Lo sfiato costa un po' di salute, quindi si attiva solo quando stai per surriscaldarti.",
		pl = "Przytrzymuje zdolność specjalną broni, aby wypuścić ciepło karabinu plazmowego w stanie NIEBEZPIECZNIE (dowolna klasa). Wentylowanie kosztuje trochę zdrowia, więc uruchamia się dopiero tuż przed przegrzaniem.",
		ru = "Удерживает особую способность оружия, чтобы стравить жар плазменного ружья в состоянии ОПАСНО (любой класс). Стравливание стоит немного здоровья, поэтому срабатывает лишь на грани перегрева.",
		ja = "危険 の間、武器のスペシャルを押し続けてプラズマガンの熱を排出します（全クラス）。排熱は体力を少し消費するため、過熱寸前でのみ作動します。",
		ko = "위험 상태일 때 무기 특수 기능을 눌러 플라즈마 건의 열을 배출합니다(모든 직업). 배출은 체력을 조금 소모하므로 과열 직전에만 작동합니다.",
		["pt-br"] = "Segura a habilidade especial da arma para ventilar o calor da arma de plasma enquanto estiver em PERIGO (qualquer classe). Ventilar custa um pouco de vida, então só age quando você está prestes a superaquecer.",
		["zh-cn"] = "处于 危险 时按住武器特殊操作来散去等离子枪的热量（适用于所有职业）。散热会消耗少量生命，因此仅在即将过热时触发。",
		["zh-tw"] = "處於 危險 時按住武器特殊操作來散去電漿槍的熱量（適用於所有職業）。散熱會消耗少量生命，因此僅在即將過熱時觸發。",
	}),
	auto_plasma_vent_interrupt = {
		en = "Interrupt on player action",
		de = "Bei Spieleraktion unterbrechen",
		es = "Interrumpir al actuar",
		fr = "Interrompre si vous agissez",
		it = "Interrompi quando agisci",
		pl = "Przerwij przy akcji gracza",
		ru = "Прерывать при действии игрока",
		ja = "プレイヤーの操作で中断",
		ko = "플레이어 행동 시 중단",
		["pt-br"] = "Interromper ao agir",
		["zh-cn"] = "玩家操作时中断",
		["zh-tw"] = "玩家操作時中斷",
	},
	auto_plasma_vent_interrupt_description = with_default(WORD_ON, {
		en = "Stop venting the moment you attack, dodge, use an ability or take any other non-movement action. Moving and looking around never interrupt it.",
		de = "Bricht das Entlüften sofort ab, sobald du angreifst, ausweichst, eine Fähigkeit einsetzt oder eine andere Aktion außer Bewegung ausführst. Bewegen und Umsehen unterbrechen es nie.",
		es = "Deja de ventilar en cuanto atacas, esquivas, usas una habilidad o realizas cualquier otra acción que no sea moverte. Moverte y mirar alrededor nunca lo interrumpen.",
		fr = "Arrête la purge dès que vous attaquez, esquivez, utilisez une capacité ou effectuez toute autre action hors déplacement. Se déplacer et regarder autour ne l'interrompent jamais.",
		it = "Interrompe lo sfiato non appena attacchi, schivi, usi un'abilità o compi qualsiasi altra azione che non sia il movimento. Muoverti e guardarti intorno non lo interrompono mai.",
		pl = "Przerywa wentylowanie w chwili, gdy atakujesz, unikasz, używasz zdolności lub wykonujesz dowolną inną akcję poza ruchem. Poruszanie się i rozglądanie nigdy go nie przerywają.",
		ru = "Прекращает стравливание, как только вы атакуете, уклоняетесь, применяете способность или совершаете любое другое действие, кроме передвижения. Движение и обзор камерой его не прерывают.",
		ja = "攻撃、回避、アビリティ使用など、移動以外の操作をした瞬間に排熱を中断します。移動と視点操作では中断されません。",
		ko = "공격, 회피, 능력 사용 등 이동이 아닌 행동을 하는 순간 배출을 중단합니다. 이동과 시점 조작으로는 중단되지 않습니다.",
		["pt-br"] = "Para de ventilar assim que você ataca, esquiva, usa uma habilidade ou realiza qualquer outra ação que não seja se mover. Mover-se e olhar ao redor nunca o interrompem.",
		["zh-cn"] = "当你攻击、闪避、使用技能或进行任何移动以外的操作时，立即中断散热。移动和转动视角不会中断它。",
		["zh-tw"] = "當你攻擊、閃避、使用技能或進行任何移動以外的操作時，立即中斷散熱。移動和轉動視角不會中斷它。",
	}),
	auto_plasma_vent_hold = {
		en = "Extra vent hold (seconds)",
		de = "Zusätzliches Entlüften (Sekunden)",
		es = "Ventilación adicional (segundos)",
		fr = "Purge supplémentaire (secondes)",
		it = "Sfiato aggiuntivo (secondi)",
		pl = "Dodatkowe wentylowanie (sekundy)",
		ru = "Доп. стравливание (секунды)",
		ja = "追加排熱時間（秒）",
		ko = "추가 배출 시간 (초)",
		["pt-br"] = "Ventilação extra (segundos)",
		["zh-cn"] = "额外散热时长（秒）",
		["zh-tw"] = "額外散熱時長（秒）",
	},
	auto_plasma_vent_hold_description = with_default("0.0", {
		en = "Keep venting this long after UNSAFE clears, instead of stopping at the edge. 0 = stop immediately.",
		de = "Entlüftet nach dem Ende von UNSICHER noch so lange weiter, statt am Limit zu stoppen. 0 = sofort stoppen.",
		es = "Sigue ventilando este tiempo después de dejar de estar en PELIGRO, en vez de parar al borde. 0 = parar de inmediato.",
		fr = "Continue de purger pendant ce délai après la fin du DANGER, au lieu de s'arrêter à la limite. 0 = arrêt immédiat.",
		it = "Continua a sfiatare per questo tempo dopo la fine del PERICOLO, invece di fermarsi al limite. 0 = ferma subito.",
		pl = "Wentyluje jeszcze tak długo po ustaniu stanu NIEBEZPIECZNIE, zamiast zatrzymywać się na krawędzi. 0 = zatrzymaj natychmiast.",
		ru = "Продолжает стравливание столько после снятия ОПАСНО, вместо остановки на грани. 0 = остановиться сразу.",
		ja = "危険 が解除された後もこの秒数だけ排熱を続けます（限界ぎりぎりで止めない）。0 = 即座に停止。",
		ko = "위험 이 해제된 뒤에도 이만큼 더 배출을 계속합니다(한계선에서 멈추지 않음). 0 = 즉시 중지.",
		["pt-br"] = "Continua ventilando por este tempo depois que o PERIGO acaba, em vez de parar no limite. 0 = parar imediatamente.",
		["zh-cn"] = "脱离 危险 后再继续散热这么久，而不是卡在临界点停手。0 = 立即停止。",
		["zh-tw"] = "脫離 危險 後再繼續散熱這麼久，而不是卡在臨界點停手。0 = 立即停止。",
	}),

	-- HUD Indicator
	show_unsafe = {
		en = "Show UNSAFE",
		de = "UNSICHER anzeigen",
		es = "Mostrar PELIGRO",
		fr = "Afficher DANGER",
		it = "Mostra PERICOLO",
		pl = "Pokaż NIEBEZPIECZNIE",
		ru = "Показывать ОПАСНО",
		ja = "「危険」を表示",
		ko = "위험 표시",
		["pt-br"] = "Mostrar PERIGO",
		["zh-cn"] = "显示 危险",
		["zh-tw"] = "顯示 危險",
	},
	show_unsafe_description = with_default(WORD_ON, {}),
	unsafe_word = {
		en = "UNSAFE word",
		de = "UNSICHER-Wort",
		es = "Palabra PELIGRO",
		fr = "Mot DANGER",
		it = "Parola PERICOLO",
		pl = "Słowo NIEBEZPIECZNIE",
		ru = "Слово ОПАСНО",
		ja = "「危険」の語",
		ko = "위험 단어",
		["pt-br"] = "Palavra PERIGO",
		["zh-cn"] = "危险 用词",
		["zh-tw"] = "危險 用詞",
	},
	unsafe_word_description = with_default(TXT_UNSAFE, {}),
	unsafe_r = {
		en = "UNSAFE red", de = "UNSICHER Rot", es = "PELIGRO rojo", fr = "DANGER rouge", it = "PERICOLO rosso",
		pl = "NIEBEZPIECZNIE czerwony", ru = "ОПАСНО красный", ja = "危険 赤", ko = "위험 빨강",
		["pt-br"] = "PERIGO vermelho", ["zh-cn"] = "危险 红", ["zh-tw"] = "危險 紅",
	},
	unsafe_r_description = with_default("235", {}),
	unsafe_g = {
		en = "UNSAFE green", de = "UNSICHER Grün", es = "PELIGRO verde", fr = "DANGER vert", it = "PERICOLO verde",
		pl = "NIEBEZPIECZNIE zielony", ru = "ОПАСНО зелёный", ja = "危険 緑", ko = "위험 초록",
		["pt-br"] = "PERIGO verde", ["zh-cn"] = "危险 绿", ["zh-tw"] = "危險 綠",
	},
	unsafe_g_description = with_default("45", {}),
	unsafe_b = {
		en = "UNSAFE blue", de = "UNSICHER Blau", es = "PELIGRO azul", fr = "DANGER bleu", it = "PERICOLO blu",
		pl = "NIEBEZPIECZNIE niebieski", ru = "ОПАСНО синий", ja = "危険 青", ko = "위험 파랑",
		["pt-br"] = "PERIGO azul", ["zh-cn"] = "危险 蓝", ["zh-tw"] = "危險 藍",
	},
	unsafe_b_description = with_default("45", {}),
	show_safe = {
		en = "Show SAFE",
		de = "SICHER anzeigen",
		es = "Mostrar SEGURO",
		fr = "Afficher SÛR",
		it = "Mostra SICURO",
		pl = "Pokaż BEZPIECZNIE",
		ru = "Показывать БЕЗОПАСНО",
		ja = "「安全」を表示",
		ko = "안전 표시",
		["pt-br"] = "Mostrar SEGURO",
		["zh-cn"] = "显示 安全",
		["zh-tw"] = "顯示 安全",
	},
	show_safe_description = with_default(WORD_OFF, {}),
	safe_word = {
		en = "SAFE word",
		de = "SICHER-Wort",
		es = "Palabra SEGURO",
		fr = "Mot SÛR",
		it = "Parola SICURO",
		pl = "Słowo BEZPIECZNIE",
		ru = "Слово БЕЗОПАСНО",
		ja = "「安全」の語",
		ko = "안전 단어",
		["pt-br"] = "Palavra SEGURO",
		["zh-cn"] = "安全 用词",
		["zh-tw"] = "安全 用詞",
	},
	safe_word_description = with_default(TXT_SAFE, {}),
	safe_r = {
		en = "SAFE red", de = "SICHER Rot", es = "SEGURO rojo", fr = "SÛR rouge", it = "SICURO rosso",
		pl = "BEZPIECZNIE czerwony", ru = "БЕЗОПАСНО красный", ja = "安全 赤", ko = "안전 빨강",
		["pt-br"] = "SEGURO vermelho", ["zh-cn"] = "安全 红", ["zh-tw"] = "安全 紅",
	},
	safe_r_description = with_default("60", {}),
	safe_g = {
		en = "SAFE green", de = "SICHER Grün", es = "SEGURO verde", fr = "SÛR vert", it = "SICURO verde",
		pl = "BEZPIECZNIE zielony", ru = "БЕЗОПАСНО зелёный", ja = "安全 緑", ko = "안전 초록",
		["pt-br"] = "SEGURO verde", ["zh-cn"] = "安全 绿", ["zh-tw"] = "安全 綠",
	},
	safe_g_description = with_default("220", {}),
	safe_b = {
		en = "SAFE blue", de = "SICHER Blau", es = "SEGURO azul", fr = "SÛR bleu", it = "SICURO blu",
		pl = "BEZPIECZNIE niebieski", ru = "БЕЗОПАСНО синий", ja = "安全 青", ko = "안전 파랑",
		["pt-br"] = "SEGURO azul", ["zh-cn"] = "安全 蓝", ["zh-tw"] = "安全 藍",
	},
	safe_b_description = with_default("70", {}),
	font_size = {
		en = "Font size", de = "Schriftgröße", es = "Tamaño de fuente", fr = "Taille de police", it = "Dimensione del carattere",
		pl = "Rozmiar czcionki", ru = "Размер шрифта", ja = "フォントサイズ", ko = "글꼴 크기",
		["pt-br"] = "Tamanho da fonte", ["zh-cn"] = "字体大小", ["zh-tw"] = "字型大小",
	},
	font_size_description = with_default("42", {}),
	pos_x = {
		en = "Horizontal position", de = "Horizontale Position", es = "Posición horizontal", fr = "Position horizontale",
		it = "Posizione orizzontale", pl = "Pozycja pozioma", ru = "Положение по горизонтали", ja = "水平位置",
		ko = "가로 위치", ["pt-br"] = "Posição horizontal", ["zh-cn"] = "水平位置", ["zh-tw"] = "水平位置",
	},
	pos_x_description = with_default("0", {
		en = "Offset from screen centre. Negative = left, positive = right.",
		de = "Versatz von der Bildschirmmitte. Negativ = links, positiv = rechts.",
		es = "Desplazamiento desde el centro de la pantalla. Negativo = izquierda, positivo = derecha.",
		fr = "Décalage depuis le centre de l'écran. Négatif = gauche, positif = droite.",
		it = "Scostamento dal centro dello schermo. Negativo = sinistra, positivo = destra.",
		pl = "Przesunięcie od środka ekranu. Ujemne = w lewo, dodatnie = w prawo.",
		ru = "Смещение от центра экрана. Отрицательное = влево, положительное = вправо.",
		ja = "画面中央からのずれ。マイナス = 左、プラス = 右。",
		ko = "화면 중앙 기준 오프셋. 음수 = 왼쪽, 양수 = 오른쪽.",
		["pt-br"] = "Deslocamento a partir do centro da tela. Negativo = esquerda, positivo = direita.",
		["zh-cn"] = "相对屏幕中心的偏移。负值 = 向左，正值 = 向右。",
		["zh-tw"] = "相對螢幕中心的偏移。負值 = 向左，正值 = 向右。",
	}),
	pos_y = {
		en = "Vertical position", de = "Vertikale Position", es = "Posición vertical", fr = "Position verticale",
		it = "Posizione verticale", pl = "Pozycja pionowa", ru = "Положение по вертикаli", ja = "垂直位置",
		ko = "세로 위치", ["pt-br"] = "Posição vertical", ["zh-cn"] = "垂直位置", ["zh-tw"] = "垂直位置",
	},
	pos_y_description = with_default("200", {
		en = "Offset from screen centre. Negative = up, positive = down.",
		de = "Versatz von der Bildschirmmitte. Negativ = oben, positiv = unten.",
		es = "Desplazamiento desde el centro de la pantalla. Negativo = arriba, positivo = abajo.",
		fr = "Décalage depuis le centre de l'écran. Négatif = haut, positif = bas.",
		it = "Scostamento dal centro dello schermo. Negativo = su, positivo = giù.",
		pl = "Przesunięcie od środka ekranu. Ujemne = w górę, dodatnie = w dół.",
		ru = "Смещение от центра экрана. Отрицательное = вверх, положительное = вниз.",
		ja = "画面中央からのずれ。マイナス = 上、プラス = 下。",
		ko = "화면 중앙 기준 오프셋. 음수 = 위, 양수 = 아래.",
		["pt-br"] = "Deslocamento a partir do centro da tela. Negativo = cima, positivo = baixo.",
		["zh-cn"] = "相对屏幕中心的偏移。负值 = 向上，正值 = 向下。",
		["zh-tw"] = "相對螢幕中心的偏移。負值 = 向上，正值 = 向下。",
	}),

	-- Dropdown option labels (word presets are English by design; DMF falls back to en)
	opt_when_reactive = WORD_REACTIVE,
	opt_when_proactive = WORD_PROACTIVE,
	opt_safe_default = { en = "Default (SAFE)" },
	opt_unsafe_default = { en = "Default (UNSAFE)" },
	opt_word_cast = { en = "CAST" },
	opt_word_go = { en = "GO" },
	opt_word_clear = { en = "CLEAR" },
	opt_word_ok = { en = "OK" },
	opt_word_ready = { en = "READY" },
	opt_word_blocked = { en = "BLOCKED" },
	opt_word_dontcast = { en = "DON'T CAST" },
	opt_word_stop = { en = "STOP" },
	opt_word_danger = { en = "DANGER" },
	opt_word_wait = { en = "WAIT" },
	opt_word_hold = { en = "HOLD" },
}