local mod = get_mod("WarpHorror")

return {
    name = mod:localize("mod_name"),
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "prevent_psyker_explosion",
                type = "group",
                sub_widgets = {
                    {
                        setting_id    = "prevent_psyker_explosion_enable",
                        type          = "checkbox",
                        default_value = true,
                        text          = mod:localize("prevent_psyker_explosion_enable"),
                        description   = mod:localize("prevent_psyker_explosion_enable_description"),
                    },
                    {
                        setting_id      = "peril_threshold",
                        type            = "numeric",
                        range           = { 0.5, 1.0 },
                        default_value   = 0.95,
                        decimals_number = 2,
                        step_size_value = 0.01,
                        text            = mod:localize("peril_threshold"),
                        description     = mod:localize("peril_threshold_description"),
                    },
                },
            },
            {
                setting_id = "warp_unbound_bug_fix",
                type = "group",
                sub_widgets = {
                    {
                        setting_id    = "warp_unbound_bug_fix_enable",
                        type          = "checkbox",
                        default_value = true,
                        text          = mod:localize("warp_unbound_bug_fix_enable"),
                        description   = mod:localize("warp_unbound_bug_fix_enable_description"),
                    },
                    {
                        setting_id      = "debounce_enter_percentage",
                        type            = "numeric",
                        range           = { 0.9, 1.0 },
                        default_value   = 0.96,
                        decimals_number = 2,
                        step_size_value = 0.01,
                        text            = mod:localize("debounce_enter_percentage"),
                        description     = mod:localize("debounce_enter_percentage_description"),
                    },
                    {
                        setting_id      = "debounce_exit_time",
                        type            = "numeric",
                        range           = { 0, 1.0 },
                        default_value   = 0.5,
                        decimals_number = 1,
                        step_size_value = 0.1,
                        text            = mod:localize("debounce_exit_time"),
                        description     = mod:localize("debounce_exit_time_description"),
                    },
                },
            },
{
                setting_id = "auto_quell",
                type = "group",
                sub_widgets = {
                    {
                        setting_id    = "auto_quell_enable",
                        type          = "checkbox",
                        default_value = false,
                        text          = mod:localize("auto_quell_enable"),
                        description   = mod:localize("auto_quell_enable_description"),
                    },
                    {
                        setting_id      = "auto_quell_threshold",
                        type            = "numeric",
                        range           = { 0.0, 1.0 },
                        default_value   = 0.95,
                        decimals_number = 2,
                        step_size_value = 0.01,
                        text            = mod:localize("auto_quell_threshold"),
                        description     = mod:localize("auto_quell_threshold_description"),
                    },
                    {
                        setting_id      = "auto_quell_duration",
                        type            = "numeric",
                        range           = { 0.0, 2.5 },
                        default_value   = 1.0,
                        decimals_number = 2,
                        step_size_value = 0.1,
                        text            = mod:localize("auto_quell_duration"),
                        description     = mod:localize("auto_quell_duration_description"),
                    },
                },
            },
            {
                setting_id = "auto_ability",
                type = "group",
                sub_widgets = {
                    {
                        setting_id    = "auto_gaze_enable",
                        type          = "checkbox",
                        default_value = false,
                        text          = mod:localize("auto_gaze_enable"),
                        description   = mod:localize("auto_gaze_enable_description"),
                    },
                    {
                        setting_id    = "auto_vent_enable",
                        type          = "checkbox",
                        default_value = false,
                        text          = mod:localize("auto_vent_enable"),
                        description   = mod:localize("auto_vent_enable_description"),
                    },
                },
            },
            {
                setting_id = "venting_shriek_explosion_prevention",
                type = "group",
                sub_widgets = {
                    {
                        setting_id      = "venting_shriek_explosion_threshold",
                        type            = "numeric",
                        range           = { 0.90, 1.0 },
                        default_value   = 0.98,
                        decimals_number = 2,
                        step_size_value = 0.01,
                        text            = mod:localize("venting_shriek_explosion_threshold"),
                        description     = mod:localize("venting_shriek_explosion_threshold_description"),
                    },
                },
            },
            {
                setting_id = "warp_siphon_integration",
                type = "group",
                sub_widgets = {
                    {
                        setting_id    = "warp_siphon_integration_enable",
                        type          = "checkbox",
                        default_value = false,
                        text          = mod:localize("warp_siphon_integration_enable"),
                        description   = mod:localize("warp_siphon_integration_enable_description"),
                    },
                    {
                        setting_id      = "warp_siphon_peril_threshold",
                        type            = "numeric",
                        range           = { 0.5, 1.0 },
                        default_value   = 0.95,
                        decimals_number = 2,
                        step_size_value = 0.01,
                        text            = mod:localize("warp_siphon_peril_threshold"),
                        description     = mod:localize("warp_siphon_peril_threshold_description"),
                    },
                    {
                        setting_id      = "warp_siphon_min_souls",
                        type            = "numeric",
                        range           = { 0, 10 },
                        default_value   = 4,
                        decimals_number = 0,
                        step_size_value = 1,
                        text            = mod:localize("warp_siphon_min_souls"),
                        description     = mod:localize("warp_siphon_min_souls_description"),
                    },
                    {
                        setting_id    = "warp_siphon_auto_quell_fallback",
                        type          = "checkbox",
                        default_value = true,
                        text          = mod:localize("warp_siphon_auto_quell_fallback"),
                        description   = mod:localize("warp_siphon_auto_quell_fallback_description"),
                    },
                },
            },
        },
    },
}