-- barrels_localization.lua
return {
mod_name = {
en = "Barrels",
de = "Fässer",
fr = "Tonneaux",
ru = "Бочки",
["zh-cn"] = "桶",
es = "Barriles",
ja = "バレル",
},
mod_description = {
en = "Reports on ignited and detonated barrels, including kills and friendly damage.",
de = "Berichtet über entzündete und detonierte Fässer, einschließlich Kills und Verbündetenschaden.",
fr = "Signale les tonneaux enflammés et explosés, y compris les éliminations et les dégâts alliés.",
ru = "Сообщает о подожженных и взорванных бочках, включая убийства и урон союзникам.",
["zh-cn"] = "报告已点燃和已爆炸的桶，包括击杀和对友军的伤害。",
es = "Informa sobre barriles incendiados y detonados, incluidas bajas y daño aliado.",
ja = "点火および爆破されたバレルに加え、キル数と味方へのダメージも報告します。",
},
explosive_fire_barrel = {
en = "Fire Barrel",
de = "Feuerfass",
fr = "Tonneau en feu",
ru = "Горящая бочка",
["zh-cn"] = "火桶",
es = "Barril de fuego",
ja = "ファイアバレル",
},
explosive_explosion_barrel = {
en = "Explosive Barrel",
de = "Sprengfass",
fr = "Tonneau explosif",
ru = "Взрывная бочка",
["zh-cn"] = "爆炸桶",
es = "Barril explosivo",
ja = "爆発バレル",
},
explosive_common = {
en = "Barrel",
de = "Fass",
fr = "Tonneau",
ru = "Бочка",
["zh-cn"] = "桶",
es = "Barril",
ja = "バレル",
},
report_mode = {
en = "Report Mode",
de = "Berichtsmodus",
fr = "Mode de rapport",
ru = "Режим отчёта",
["zh-cn"] = "报告模式",
es = "Modo de informe",
ja = "報告モード",
},
report_mode_option_default = {
en = "Pop up (Default)",
de = "Pop-up (Standard)",
fr = "Pop-up (par défaut)",
ru = "Всплывающее окно (по умолчанию)",
["zh-cn"] = "弹出窗口（默认）",
es = "Ventana emergente (predeterminado)",
ja = "ポップアップ（デフォルト）",
},
report_mode_option_chat = {
en = "Chat",
de = "Chat",
fr = "Chat",
ru = "Чат",
["zh-cn"] = "聊天",
es = "Chat",
ja = "チャット",
},
report_mode_option_kill_feed = {
en = "Kill feed",
de = "Kill-Feed",
fr = "Fil de tués",
ru = "Лента убийств",
["zh-cn"] = "击杀消息",
es = "Línea de muertes",
ja = "キルフィード",
},
show_skulls = {
en = "Show skulls",
de = "Schädel anzeigen",
fr = "Afficher les crânes",
ru = "Показывать черепа",
["zh-cn"] = "显示骷髅",
es = "Mostrar calaveras",
ja = "ドクロを表示",
},
show_skulls_tooltip = {
en = "When on, shows skull icons next to the output",
de = "Zeigt bei Aktivierung Totenkopf-Symbole neben der Ausgabe an",
fr = "Lorsque activé, affiche des icônes de crâne à côté de la sortie",
ru = "При включении отображает значки черепа рядом с выводом",
["zh-cn"] = "启用时，在输出旁边显示骷髅图标",
es = "Cuando está activado, muestra iconos de calavera junto a la salida",
ja = "オンにすると、出力の横にドクロアイコンを表示します",
},
show_damage = {
en = "Show damage",
de = "Schaden anzeigen",
fr = "Afficher les dégâts",
ru = "Показывать урон",
["zh-cn"] = "显示伤害",
es = "Mostrar daño",
ja = "ダメージを表示",
},
show_damage_tooltip = {
en = "When on, shows damage, downs and kills on other players and bots.",
de = "Zeigt bei Aktivierung Schaden, Niederschläge und Tötungen bei anderen Spielern und Bots an.",
fr = "Lorsque activé, affiche les dégâts, mises à terre et éliminations sur les autres joueurs et bots.",
ru = "При включении отображает урон, нокауты и убийства других игроков и ботов.",
["zh-cn"] = "启用时，显示对其他玩家和机器人的伤害、击倒和击杀。",
es = "Cuando está activado, muestra daño, derribos y muertes de otros jugadores y bots.",
ja = "オンにすると、他のプレイヤーやボットへのダメージ、ダウン、キルを表示します。",
},
}
