-- barrels_localization.lua
return {
 mod_name = {
 en = "Barrels",
 de = "Fässer",
 fr = "Tonneaux",
 ru = "Бочки",
 ["zh-cn"] = "桶",
 es = "Barriles",
 ja = "バレル",
 },
 mod_description = {
 en = "Reports on ignited and detonated barrels.",
 de = "Berichtet über entzündete und detonierte Fässer.",
 fr = "Informe sur les tonneaux enflammés et explosés.",
 ru = "Отслеживает воспламененные и взорванные бочки.",
 ["zh-cn"] = "报告已点燃和已爆炸的桶。",
 es = "Informa sobre barriles incendiados y detonados.",
 ja = "点火および爆破されたバレルを报告します。",
 },
 explosive_fire_barrel = {
 en = "Fire Barrel",
 de = "Feuerfass",
 fr = "Tonneau en feu",
 ru = "Горящая бочка",
 ["zh-cn"] = "火桶",
 es = "Barril de fuego",
 ja = "ファイアバレル",
 },
 explosive_explosion_barrel = {
 en = "Explosive Barrel",
 de = "Sprengfass",
 fr = "Tonneau explosif",
 ru = "Взрывная бочка",
 ["zh-cn"] = "爆炸桶",
 es = "Barril explosivo",
 ja = "爆発バレル",
 },
 explosive_common = {
 en = "Barrel",
 de = "Fass",
 fr = "Tonneau",
 ru = "Бочка",
 ["zh-cn"] = "桶",
 es = "Barril",
 ja = "バレル",
 },
 report_mode = {
 en = "Report Mode",
 de = "Berichtsmodus",
 fr = "Mode de rapport",
 ru = "Режим отчёта",
 ["zh-cn"] = "报告模式",
 es = "Modo de informe",
 ja = "報告モード",
 },
 report_mode_option_default = {
 en = "Pop up (Default)",
 de = "Pop-up (Standard)",
 fr = "Pop-up (par défaut)",
 ru = "Всплывающее окно (по умолчанию)",
 ["zh-cn"] = "弹出窗口（默认）",
 es = "Ventana emergente (predeterminado)",
 ja = "ポップアップ（デフォルト）",
 },
 report_mode_option_chat = {
 en = "Chat",
 de = "Chat",
 fr = "Chat",
 ru = "Чат",
 ["zh-cn"] = "聊天",
 es = "Chat",
 ja = "チャット",
 },
 report_mode_option_kill_feed = {
 en = "Kill feed",
 de = "Kill-Feed",
 fr = "Fil de tués",
 ru = "Лента убийств",
 ["zh-cn"] = "击杀消息",
 es = "Línea de muertes",
 ja = "キルフィード",
 },
 show_skulls = {
 en = "Show skulls",
 de = "Schädel anzeigen",
 fr = "Afficher les crânes",
 ru = "Показывать черепа",
 ["zh-cn"] = "显示骷髅",
 es = "Mostrar calaveras",
 ja = "ドクロを表示",
 },
 show_skulls_tooltip = {
 en = "When on, shows skull icons next to the output",
 de = "Zeigt bei Aktivierung Totenkopf-Symbole neben der Ausgabe an",
 fr = "Lorsque activé, affiche des icônes de crâne à côté de la sortie",
 ru = "При включении отображает значки черепа рядом с выводом",
 ["zh-cn"] = "启用时，在输出旁边显示骷髅图标",
 es = "Cuando está activado, muestra iconos de calavera junto a la salida",
 ja = "オンにすると、出力の横にドクロアイコンを表示します",
 },
 show_damage = {
 en = "Show damage",
 de = "Schaden anzeigen",
 fr = "Afficher les dégâts",
 ru = "Показывать урон",
 ["zh-cn"] = "显示伤害",
 es = "Mostrar daño",
 ja = "ダメージを表示",
 },
 show_damage_tooltip = {
 en = "When on, shows damage to other players and bots.",
 de = "Zeigt bei Aktivierung den Schaden an andere Spieler und Bots an.",
 fr = "Lorsque activé, affiche les dégâts infligés aux autres joueurs et aux bots.",
 ru = "При включении отображает урон другим игрокам и ботам.",
 ["zh-cn"] = "启用时，显示对其他玩家和机器人的伤害。",
 es = "Cuando está activado, muestra el daño a otros jugadores y bots.",
 ja = "オンにすると、他のプレイヤーやボットへのダメージを表示します。",
 },
}
