return {
    ui_001={en="Abhuman Muster",["zh-cn"]="蛮子动员兵",["zh-tw"]="蠻子動員兵"},
    ui_002={en="Abhuman Explosions",["zh-cn"]="蛮子爆燃",["zh-tw"]="蠻子爆燃"},
    ui_003={en="Barrel Grounds",["zh-cn"]="纷乱爆燃",["zh-tw"]="紛亂爆燃"},
    ui_004={en="Barren",["zh-cn"]="资源匮乏",["zh-tw"]="資源匱乏"},
    ui_005={en="Barren (revised)",["zh-cn"]="资源匮乏（新版）",["zh-tw"]="資源匱乏（新版）"},
    ui_006={en="Stimm Operation",["zh-cn"]="兴奋剂行动",["zh-tw"]="興奮劑行動"},
    ui_007={en="Communication Hack",["zh-cn"]="通讯入侵",["zh-tw"]="通訊入侵"},
    ui_008={en="Elite Army",["zh-cn"]="不屈入侵",["zh-tw"]="不屈入侵"},
    ui_009={en="Endless Hordes",["zh-cn"]="无尽敌群",["zh-tw"]="無盡敵群"},
    ui_010={en="Leftover Supplies",["zh-cn"]="残余物资",["zh-tw"]="殘餘物資"},
    ui_011={en="Moebian 21st",["zh-cn"]="莫比亚21团",["zh-tw"]="莫比亞21團"},
    ui_012={en="Nurgle Explosions",["zh-cn"]="纳垢爆发",["zh-tw"]="納垢爆發"},
    ui_013={en="Plasma Smugglers",["zh-cn"]="等离子走私者",["zh-tw"]="等離子走私者"},
    ui_014={en="Rotten Armour",["zh-cn"]="腐化装甲",["zh-tw"]="腐化裝甲"},
    ui_015={en="Saints Operation",["zh-cn"]="圣徒行动",["zh-tw"]="聖徒行動"},
    ui_016={en="Skulls Event",["zh-cn"]="颅骨事件",["zh-tw"]="顱骨事件"},
    ui_017={en="Skulls and Guns",["zh-cn"]="颅骨武装",["zh-tw"]="顱骨武裝"},
    ui_018={en="Stolen Rations",["zh-cn"]="失窃口粮",["zh-tw"]="失竊口糧"},
    ui_019={en="Destroy Rations",["zh-cn"]="销毁口粮",["zh-tw"]="銷毀口糧"},
    ui_020={en="Recover Rations",["zh-cn"]="回收口粮",["zh-tw"]="回收口糧"},
    ui_021={en="Havoc",["zh-cn"]="浩劫",["zh-tw"]="浩劫"},
    ui_022={en="Auric",["zh-cn"]="金级词条",["zh-tw"]="金級詞條"},
    ui_023={en="Events",["zh-cn"]="活动",["zh-tw"]="活動"},
    ui_024={en="Factions",["zh-cn"]="阵营规则",["zh-tw"]="陣營規則"},
    ui_025={en=" (adapted)",["zh-cn"]="（适配版）",["zh-tw"]="（適配版）"},
    ui_026={en=" (vanilla)",["zh-cn"]="（原版）",["zh-tw"]="（原版）"},
    ui_027={en=" (Weakened)",["zh-cn"]="（虚弱）",["zh-tw"]="（虛弱）"},
    ui_028={en="Enter ",["zh-cn"]="请输入 ",["zh-tw"]="請輸入 "},
    ui_029={en=" (whole numbers)",["zh-cn"]=" 范围内的整数",["zh-tw"]=" 範圍內的整數"},
    ui_030={en=" (numeric value)",["zh-cn"]=" 范围内的数字",["zh-tw"]=" 範圍內的數字"},
    ui_031={en="OK",["zh-cn"]="确定",["zh-tw"]="確定"},
    ui_032={en="Cancel",["zh-cn"]="取消",["zh-tw"]="取消"},
    ui_033={en="Enter/click outside: save. Esc: cancel.\nPaste supported. Updates linked values.",["zh-cn"]="回车或点击外部确认 · Esc 取消\n支持粘贴；确认后更新联动数值",["zh-tw"]="Enter 或點擊外部確認 · Esc 取消\n支援貼上；確認後更新連動數值"},
    ui_034={en="Mission setup",["zh-cn"]="任务设置",["zh-tw"]="任務設定"},
    ui_035={en="Conditions",["zh-cn"]="词条配置",["zh-tw"]="詞條配置"},
    ui_036={en="Spawn multipliers",["zh-cn"]="生成倍率",["zh-tw"]="生成倍率"},
    ui_037={en="Advanced director",["zh-cn"]="高级生成器",["zh-tw"]="高階生成器"},
    ui_038={en="Click to type. Enter or click outside to save; Esc to cancel.",["zh-cn"]="点击数字直接输入；回车或点击外部确认，Esc 取消。",["zh-tw"]="點擊數字直接輸入；Enter 或點擊外部確認，Esc 取消。"},
    ui_039={en="All",["zh-cn"]="全部",["zh-tw"]="全部"},
    ui_040={en="Selected",["zh-cn"]="已选",["zh-tw"]="已選"},
    ui_041={en="Add all conditions",["zh-cn"]="添加全部词条",["zh-tw"]="新增全部詞條"},
    ui_042={en="Add this category",["zh-cn"]="添加当前分类",["zh-tw"]="新增當前分類"},
    ui_043={en="Clear selection",["zh-cn"]="清空所选",["zh-tw"]="清空所選"},
    ui_044={en="Remove category",["zh-cn"]="移除当前分类",["zh-tw"]="移除當前分類"},
    ui_045={en="Environment",["zh-cn"]="环境选择",["zh-tw"]="環境選擇"},
    ui_046={en="Choose one environment. Options depend on the selected mission.",["zh-cn"]="环境单选；列表随所选任务更新。",["zh-tw"]="環境單選；列表隨所選任務更新。"},
    ui_047={en="Choose one environment and multiple conditions. Only environments supported by this mission are listed.",["zh-cn"]="环境单选，词条可多选；仅列出当前任务支持的环境。",["zh-tw"]="環境單選，詞條可多選；僅列出當前任務支援的環境。"},
    ui_048={en="No conditions in this category. Select All to browse.",["zh-cn"]="此分类中暂无词条。选择“全部”可继续添加。",["zh-tw"]="此分類中暫無詞條。選擇“全部”可繼續新增。"},
    ui_049={en="Adapted",["zh-cn"]="扩展",["zh-tw"]="擴充套件"},
    ui_050={en=" · Adapted condition",["zh-cn"]=" · 参考扩展",["zh-tw"]=" · 參考擴充套件"},
    ui_051={en="Bulk edits affect the current filter. Environment stays selected. Hover for details; set difficulty on the Mission page.",["zh-cn"]="批量操作仅影响当前词条筛选，不改变环境。悬停查看说明，难度仍在任务页设置。",["zh-tw"]="批次操作僅影響當前詞條篩選，不改變環境。懸停檢視說明，難度仍在任務頁設定。"},
    ui_052={en="Advanced director active · Multipliers apply here; edit caps on the Advanced page",["zh-cn"]="当前使用高级生成器 · 本页倍率生效，上限由高级页设置",["zh-tw"]="當前使用高階生成器 · 本頁倍率生效，上限由高階頁設定"},
    ui_053={en="Native spawning active · Original pools and caps apply",["zh-cn"]="当前使用原版生成器 · 保留原有单位池与容量",["zh-tw"]="當前使用原版生成器 · 保留原有單位池與容量"},
    ui_054={en="Spawn mode →",["zh-cn"]="切换生成模式 →",["zh-tw"]="切換生成模式 →"},
    ui_055={en="Enemy type",["zh-cn"]="敌人类型",["zh-tw"]="敵人類型"},
    ui_056={en="Scaling mode",["zh-cn"]="调整方式",["zh-tw"]="調整方式"},
    ui_057={en="Common / hordes",["zh-cn"]="普通敌人 / 尸潮",["zh-tw"]="普通敵人 / 屍潮"},
    ui_058={en="Elites",["zh-cn"]="精英敌人",["zh-tw"]="精英敵人"},
    ui_059={en="Specialists",["zh-cn"]="特感",["zh-tw"]="特感"},
    ui_060={en="Quantity",["zh-cn"]="数量",["zh-tw"]="數量"},
    ui_061={en="Speed",["zh-cn"]="速度",["zh-tw"]="速度"},
    ui_062={en="Mixed",["zh-cn"]="混合",["zh-tw"]="混合"},
    ui_063={en="Quantity increases batch size. Speed reduces intervals and travel distances. Mixed splits the multiplier between both.\n",["zh-cn"]="数量：增加每批数量。速度：缩短间隔和推进距离。混合：将倍率分配给二者。\n",["zh-tw"]="數量：增加每批數量。速度：縮短間隔和推進距離。混合：將倍率分配給二者。\n"},
    ui_064={en="Changing a multiplier updates its caps. The highest multiplier sets the total cap: 240 / 330 / 420 / 510 / 600.\nAdvanced caps remain editable; changing multipliers resets matching presets. Changes apply next mission.",["zh-cn"]="调整倍率直接更新对应容量。总上限按四类最高倍率取 240 / 330 / 420 / 510 / 600。\n高级页直接显示已保存的上限；仍可手动修改，切换倍率时重设对应档位。新设置下局生效。",["zh-tw"]="調整倍率直接更新對應容量。總上限按四類最高倍率取 240 / 330 / 420 / 510 / 600。\n高階頁直接顯示已儲存的上限；仍可手動修改，切換倍率時重設對應檔位。新設定下局生效。"},
    ui_065={en="Native caps still apply. Map defenders have no respawn timer.",["zh-cn"]="原版容量仍然生效；地图驻守没有重生计时器。",["zh-tw"]="原版容量仍然生效；地圖駐守沒有重生計時器。"},
    ui_066={en="%d / %d   ·   %d selected",["zh-cn"]="%d / %d   ·   已选 %d 个词条",["zh-tw"]="%d / %d   ·   已選 %d 個詞條"},
    ui_067={en="Havoc difficulty",["zh-cn"]="浩劫难度与配置",["zh-tw"]="浩劫難度與配置"},
    ui_068={en="Conditions / environment · ",["zh-cn"]="词条与环境  ·  已选 ",["zh-tw"]="詞條與環境  ·  已選 "},
    ui_069={en=" selected",["zh-cn"]=" 项",["zh-tw"]=" 項"},
    ui_070={en="Enemy spawning →",["zh-cn"]="调整敌人生成 →",["zh-tw"]="調整敵人生成 →"},
    ui_071={en="Choose environments on the Conditions page.\nSet mission and difficulty here.",["zh-cn"]="环境选择已移至“词条配置”页。\n本页保留任务与难度设置。",["zh-tw"]="環境選擇已移至“詞條配置”頁。\n本頁保留任務與難度設定。"},
    ui_072={en="Condition edits rebuild generators; multipliers reset matching caps · Changes apply next mission",["zh-cn"]="增删词条会重建生成器；调整倍率会重设对应上限  ·  新配置下局应用",["zh-tw"]="增刪詞條會重建生成器；調整倍率會重設對應上限  ·  新配置下局應用"},
}
